<h1 class="admin-title">Admin Panel</h1>

<div class="admin-dashboard">
  <div class="online-users-container">
    <h2>Active Users</h2>
    <p><?= $usersOnline ?></p>
  </div>

  <div class="purchase-container">
    <h2>Total Purchases</h2>
    <p><?= $purchases ?></p>
  </div>

  <div class="reports-container">
    <h2>Pending Reports</h2>
    <p><?= $pendingReports ?></p>
    <button><a href="adminReports">View Reports</a></button>
  </div>

  <div class="system-status-container">
    <h2>System Status</h2>
    <p>All systems operational.</p>
    <button>View Logs</button>
  </div>
</div>

<div class="admin-actions-container">
  <h2>Last Admin Actions</h2>
  
  <ul id="admin-actions-list">
    <?php foreach ($adminActions as $action) : ?>
      <?php if ($action['action_type'] === 'Added Character') : ?>
        <li>
          <strong><?= htmlspecialchars($action['user_username']) ?></strong> 
          performed <em><?= htmlspecialchars($action['action_type']) ?></em> 
          and added <strong><?= htmlspecialchars($action['target_game_username']) ?></strong> 
          at <?= htmlspecialchars($action['timestamp']) ?>.
        </li>
      <?php elseif ($action['action_type'] === 'Ban') : ?>
        <li>
          <strong><?= htmlspecialchars($action['user_username']) ?></strong> 
          performed <em><?= htmlspecialchars($action['action_type']) ?></em> 
          on <strong><?= htmlspecialchars($action['ban_username']) ?></strong> 
          (ID: <?= htmlspecialchars($action['ban_userId']) ?>, email : <strong><?= htmlspecialchars($action['ban_email']) ?></strong>)
          at <?= htmlspecialchars($action['timestamp']) ?>.
        </li>
      <?php else : ?>
      <li>
        <strong><?= htmlspecialchars($action['user_username']) ?></strong> 
        performed <em><?= htmlspecialchars($action['action_type']) ?></em> 
        on <strong><?= htmlspecialchars($action['target_username']) ?></strong> 
        (ID: <?= htmlspecialchars($action['target_user_id']) ?>) 
        at <?= htmlspecialchars($action['timestamp']) ?>.
      </li>
      <?php endif; ?>
    <?php endforeach; ?>
  </ul>
</div>

