<section id="CSAE">
        <h1><?= $this->_('csae_headline') ?></h1>
        <p><?= $this->_('csae_text1.1') ?><strong><?= $this->_('csae_text1.2') ?></strong><?= $this->_('csae_text1.3') ?><strong><?= $this->_('csae_text1.4') ?></strong> <?= $this->_('csae_text1.5') ?></p>
        
        <h2 id="prohibited"><?= $this->_('csae_headline2') ?></h2>
        <p><?= $this->_('csae_text2') ?></p>
        <ul>
            <li><?= $this->_('csae_text3') ?></li>
            <li><?= $this->_('csae_text4') ?></li>
            <li><?= $this->_('csae_text5') ?></li>
        </ul>
        
        <h2 id="reporting"><?= $this->_('csae_headline3') ?></h2>
        <p><?= $this->_('csae_text6.1') ?><a href="mailto:contact@ur-sg.com"><?= $this->_('csae_text6.2') ?></a>.</p>
        
        <h2 id="law"><?= $this->_('csae_headline4') ?></h2>
        <p><?= $this->_('csae_text7') ?></p>
        
        <p><?= $this->_('csae_text8.1') ?><a href="mailto:contact@ur-sg.com"><?= $this->_('csae_text8.2') ?></a>.</p>
</section>