<!-- <section class="download_app">
    <p>Download the app</p>
    <a href=""><img id ="apple_logo"src="public/images/appstore.png" alt="appstore"></a>
    <a href=""><img id="google_logo" src="public/images/googleplay.png" alt="googleplay"></a>
</section> -->

<a href="https://discord.gg/Bfpkws74V3" target="_blank" aria-label="Click to join our discord server">
    <section class="discord">
        <div class="discord_row">
        <i class="fa-brands fa-discord"></i>
            <h2>Your soulmate on Discord!</h2>
        </div>
    </section>
</a>


<!-- <div class="separator"></div><br> -->

<section class="frequently_asked_question">
    <h2>Frequently Asked questions</h2>
        <div class="faq_row">
            <div class="faq_row_box">
                <h3>Why do I need a Google account?</h3>
                    <p>To ensure a fair and secure user experience, each URSG account must be linked to a unique Google account. Even after linking your Google account, you'll need to confirm your email address and provide some additional information to fully access our website. We may introduce more login options in the future.
                    <p>    
            </div>

            <div class="faq_row_box">
                <h3>How does it work?</h3>
                    <p>First, you need to sign up and tell us more about yourself and what you're looking for. This will help us match you with people who are a good fit for you. Once matched, you can chat with them through our platform or add them directly to play games.
                    <p>    
            </div>
        </div>
        <br>
</section>

<a href="https://ko-fi.com/yoursoulmategamer" target="_blank" aria-label="Click to support us on kofi">
    <section class="kofi">
        <div class="kofi_row">
            <img src="public/images/kofi_s_logo_nolabel.png" alt="kofi logo" loading="lazy">
            <h2>Support us on Ko-fi!</h2>
        </div>
    </section>
</a>

<!-- Cookies -->
<dialog id="dialogCookie">
    <h2><i class="fa-solid fa-cookie"></i> Cookie Management</h2>
    <div class="dialogCookieRowButtons">
        <button id="btn_optionsCookie">Cookies</button>
        <button id="btn_aboutCookie">About cookies</button>
    </div>
    <div class="dialogCookieRow" id="optionsCookies">
        <h3>Strictly necessary</h3>
        <p class="cookieState">Always active</p>
    </div>
    <div class="dialogCookieRow" id="aboutCookies">
        <p>Cookies are small text files stored on your device by your web browser. They help websites remember information about your visit, such as login details or preferences, to improve your browsing experience.</p>
    </div>
    <button id="saveCookies">Save</button>
</dialog>

<script src="public/js/home.js"></script>