<section class="download_app">
    <p>Download the app</p>
    <a href=""><img id ="apple_logo"src="public/images/appstore.png" alt="appstore"></a>
    <a href=""><img id="google_logo" src="public/images/googleplay.png" alt="googleplay"></a>
</section>

<div class="separator"></div><br>

<section class="frequently_asked_question">
    <h2>Frequently Asked questions</h2>
        <div class="faq_row">
            <div class="faq_row_box">
                <h3>Why do I need a Google account?</h3>
                    <p>You can only create one URSG account per Google account, it's a way of
                        making sure no one can make too many accounts which is against our rules. But 
                        even after connecting with your Google account you still need to confirm email and 
                        fill some informations to fully access our website.
                        More ways of connecting might be added later.
                    <p>    
            </div>

            <div class="faq_row_box">
                <h3>How does it work?</h3>
                    <p>First of all you need to sign up, tell us more about you and what you are looking for, and you'll be able to match with people fitting you. You can use our chat to talk with them or add them directly.
                    <p>    
            </div>
        </div><br>
</section>