<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <link href="public/css/style.css?14" rel="stylesheet">
    <title><?= $page_title ?></title>

    <!-- Primary Meta Tags -->
    <meta name="title" content="URSG - Your Soulmate Gamer">
    <meta name="description" content="It is time to find your soulmate. And there is no better place than here. Meet and play together League of Legends, Valorant or more.">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://ur-sg.com/">
    <meta property="og:title" content="<?= $page_title ?> - Your Soulmate Gamer">
    <meta property="og:description" content="It is time to find your soulmate. And there is no better place than here. Meet and play together League of Legends, Valorant or more.">
    <meta property="og:image" content="https://ur-sg.com/public/images/ursg-preview-small.png">
    <meta property="og:locale" content="en_US">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://ur-sg.com/">
    <meta property="twitter:title" content="<?= $page_title ?> - Your Soulmate Gamer">
    <meta property="twitter:description" content="It is time to find your soulmate. And there is no better place than here. Meet and play together League of Legends, Valorant or more.">
    <meta property="twitter:image" content="https://ur-sg.com/public/images/ursg-preview-small.png">

    <!-- SEO and Browser Configuration -->
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="canonical" href="<?= $current_url ?>">
    <link rel="icon" type="image/png" href="public/images/favicon/favicon.ico">
    <link rel="icon" type="image/png" sizes="32x32" href="public/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="public/images/favicon/favicon-16x16.png">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="public/js/dark-mode.js?<?= time(); ?>"></script>
</head>


