<?php require "views/layout.phtml"; ?>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P3XDDBJQ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<?php if (isset($_SESSION['mode'])) : ?>
    <body class="<?= ($_SESSION['mode'] === 'dark') ? 'dark-mode' : '' ?>">
<?php else : ?>
    <body>
<?php endif; ?>

<header>
    <nav>
        <div class="nav_swiping">
            <a href="/"><img title="Home" class="scale" src="public/images/favicon/favicon.ico" alt="logo_ursg"></a>
            <div class="nav-swiping-row">
                <a href="/playerfinder"><img title="Player Finder" class="scaleNoRound" src="public/images/playerfinder.png" alt="swipe"></a>
                <a href="/?triggerSignUp=true" class="swiping_noheader_signup">Sign up</a>
                <div class="toggle-container">
                    <div title="Dark mode" id="toggle-button" class="toggle-button"></div>
                </div>
            </div>
        </div>
    </nav>
</header>
    <main>
        <?php if(isset($_GET['message'])) :?>
            <span class="form-error"><?= $_GET['message'] ?></span>
        <?php endif; ?>
        <?php require $template.".phtml"; ?> 
    </main>

<footer>
    <div class="footer_grey">
        <div class="top_footer">
            <p>Copyright © 2025 URSG</p>
            <p>Your Soulmate gamer</p>
        </div>

        <div class="mid_footer">
        <p><a href="/legalNotice">Legal notice/Privacy policy, </a><a href="/termsOfService">ToS, </a><a href="/CSAE">CSAE</a></p>
        <a href="/siteMap"> Site map</a>
        </div>

        <div class="social_footer">
            <a href="https://discord.gg/Bfpkws74V3" target="_blank">
                <img src="public/images/discord2.png" alt="logo discord" loading="lazy"></a>
            <a href="https://twitter.com/Dosylia" target="_blank">
                <img src="public/images/twitter2.png" alt="logo twitter/x" loading="lazy"></a>
        </div>

        <div class="bot_footer">
            <p>Made by :  <a target="_blank" href="https://www.dosylia.com/">Dosylia</a></p>
            <p>Artwork by :  <a target="_blank" href="https://twitter.com/ShadowLilithArt/">ShadowLilithArt</a></p>       
        </div>
    </div>   
</footer>

    <!-- Triggers for tracking scritps -->
    <script>
        window.addEventListener('DOMContentLoaded', function () {
            // Send page view event
            if (typeof sendPageView === 'function') {
                sendPageView('swiping_page');
            }
            // Check if user is returning and send event
            if (typeof sendReturningUserEvent === 'function') {
                sendReturningUserEvent();
            }
        });
     </script>

</body>

</html>