<?php require "views/layout.phtml"; ?> 
<body>

<header>
    <section class="main_section">
        <div class="top_main_section"> 
            <div class="top_left_main_section">
                <a href="/">
                    <img class="logo_ursg" src="public/images/logo_ursg_white.png" alt="logo">
                </a>
            </div> 

            <div class="top_right_main_section">
                <div class="toggle-container">
                            <div title="Dark mode" id="toggle-button" class="toggle-button"></div>
                </div>
            <nav>
                <!-- PHP TO SHOW ALL DIFFERENT BUTTONS DEPENDING ON SESSION -->
                                        
                <?php if($this->isConnectGoogle() && $this->isConnectWebsite() && $this->isConnectLeague() && $this->isConnectLeagueLf()) :?>  <!-- Connected to all -->
                    <a href="/logout" id="fix_mobile_signup" class="signup_button" title="Log in"> <!-- Log out button -->
                            Log out
                    </a>
                    <a href="/userProfile?<?= ucfirst($user['user_username'])?>" title="Profile" class="fix_mobile_signup signup_button notranslate"> <!-- User page / name = username -->
                        <?= ucfirst($user['user_username']) ?>
                    </a>  
                <?php elseif ($this->isConnectGoogle() && $this->isConnectWebsite() && $this->isConnectLeague() && !$this->isConnectLeagueLf()): ?>  <!-- No session for looking for -->
                    <a href="/logout"  class="fix_mobile_signup signup_button" title="Log in"> <!-- Log out button -->
                        Log out
                    </a>
                    <a href="/signup" title="Sign up" class="fix_mobile_signup signup_button notranslate"> <!-- User page / name = username -->
                        <?= ucfirst($user['user_username']) ?>
                    </a>   
                <?php elseif ($this->isConnectGoogle() && $this->isConnectWebsite() && !$this->isConnectLeague() && !$this->isConnectLeagueLf()): ?>  <!-- No session for looking for and league -->
                    <a href="/logout" class="fix_mobile_signup signup_button" title="Log in"> <!-- Log out button -->
                        Log out
                    </a>
                    <a href="/signup" title="Profile" class="fix_mobile_signup signup_button notranslate"> <!-- User page / name = username -->
                        <?= ucfirst($user['user_username']) ?>
                    </a>   
                <?php elseif ($this->isConnectGoogle() && !$this->isConnectWebsite()) : ?>
                    <a href="/logout" class="fix_mobile_signup signup_button" title="Log in"> <!-- Log out button -->
                        Log out
                    </a>
                    <a href="/signup" title="Profile" class="fix_mobile_signup signup_button notranslate"> <!-- User page / Diff name-->
                        <?= ucfirst($googleUser['google_fullName']) ?>
                    </a>
                <?php else : ?>
                    <input value="Sign up/Log in" type="text" title="Sign up/Sign in" id="signup_button">
                <?php endif; ?>
            </nav>
        </div>
    </div>

        <div class="mid_main_section">
            <p><?= $title ?></p>
            <?php if ($this->isConnectGoogle() && $this->isConnectWebsite() && $this->isConnectLeague() && $this->isConnectLeagueLf()) : ?>
                <a href="/swiping" class="mid_main_section_button2">Swipe now</a>
            <?php elseif ($this->isConnectGoogle()) : ?>
                <a href="/signup" class="mid_main_section_button2">Join now</a>
            <?php else : ?>
                <input class="mid_main_section_button" value="Join now" >
            <?php endif; ?>
        </div>   
    </section>

    <dialog id="favDialog">
        <!-- Display of Log in button, cancel and terms of use -->
        <section class="loginsignin">
            <h2>Sign up/Log in</h2><br><br>
                <p>When clicking on sign in,<br> you agree to <a href="/legalNotice">our terms of use</a>.</p><br>
                <script  src="public/js/ajaxGoogle.js"></script>
            <div class="social_buttons2">
                <div id="g_id_onload"
                    data-client_id="666369513537-r75otamfu9qqsnaklgqiromr7bhiehft.apps.googleusercontent.com"
                    data-context="signin"
                    data-ux_mode="popup"
                    data-callback="handleCredentialResponse"
                    data-auto_prompt="false"
                    data-use_fedcm_for_prompt="true">
                </div>

                
                <div class="g_id_signin"
                    data-type="standard"
                    data-shape="rectangular"
                    data-theme="outline"
                    data-text="signin_with"
                    data-size="large"
                    data-logo_alignment="left">
                </div>
                <script src="https://accounts.google.com/gsi/client" defer async></script>
            </div><br>
            <!-- Get out of pop up -->
            <button id="cancelBtn">Cancel</button>
            <br><br>
        </section>

        <!-- Display of buttons to download app on App store/Google Store -->
        <!-- <section class="download_app_dialog">  
            <p>Download the app</p>
            <div class="download_app_dialog_logos">
                <a href=""><img id="apple_logo" src="public/images/appstore.png" alt="appstore"></a>
                <a href=""><img id="google_logo" src="public/images/googleplay.png" alt="googleplay"></a>
            </div>  
        </section> -->
    </dialog>
</header>

    <main>
        <?php if(isset($_GET['message'])) :?>
            <span class="form-error"><?= $_GET['message'] ?></span>
        <?php endif; ?>
        <?php require $template.".phtml"; ?> 
    </main>


<footer>
    <div class="footer_black">
        <div class="top_footer">
            <p>Copyright © 2023 URSG</p>
            <p>Your Soulmate gamer</p>
        </div>

        <div class="mid_footer">
        <p><a href="/legalNotice">Legal notice, </a><a href="/termsOfService">ToS</a></p>
            <a href="/siteMap"> Site map</a>
        </div>

        <div class="social_footer">
            <a href="https://discord.gg/Bfpkws74V3" target="_blank">
                <img src="public/images/discord2.png" alt="logo discord"></a>
            <a href="https://twitter.com/Dosylia" target="_blank">
                <img src="public/images/twitter2.png" alt="logo twitter/x"></a>
        </div>

        <div class="bot_footer">
            <p>Made by :  <a href="https://www.dosylia.com/">Dosylia</a></p>
            <p>Artwork by :  <a href="https://twitter.com/ShadowLilithArt/">ShadowLilithArt</a></p>       
        </div>
    </div>   
</footer>

<script src="public/js/dialogGoogle.js"></script>
</body>


</html>