<?php require "views/layout.phtml"; ?> 

<header>
    <section class="main_section_small" proload>
        <div class="overlay"></div>
        <!-- Top of website start -->
        <div class="top_main_section"> 
            <div class="top_left_main_section">
                <a href="/">
                    <img class="logo_ursg" src="public/images/logo_ursg_white.png" alt="logo">
                </a>
            </div> 
            <!-- Nav of website start here -->
            <nav>
                <div class="top_right_main_section">
                    <div class="toggle-container">
                            <div title="Dark mode" id="toggle-button" class="toggle-button"></div>
                    </div>

                    <!-- PHP TO SHOW ALL DIFFERENT BUTTONS DEPENDING ON SESSION -->
                      
                    <?php if($this->isConnectGoogle() && $this->isConnectWebsite() && $this->isConnectLeague() && $this->isConnectLeagueLf()) :?>  <!-- Connected to all -->
                            <a href="/logout"><!-- Log out button -->
                                <button type="button" title="Log out" id="fix_mobile_signup" class="signup_button" >Log out</button>
                            </a>
                            <a href="/userProfile&username=<?= ucfirst($user['user_username'])?>"> <!-- User page / name = username -->
                                <button title="Profile" id="fix_mobile_signup" class="signup_button"><?= ucfirst($user['user_username']) ?></button>
                            </a>
                        <?php elseif ($this->isConnectGoogle() && $this->isConnectWebsite() && $this->isConnectLeague() && !$this->isConnectLeagueLf()): ?>  <!-- No session looking for  -->
                            <a href="/logout"><!-- Log out button -->
                                <button type="button" title="Log out" id="fix_mobile_signup" class="signup_button" >Log out</button>
                            </a>
                            <a href="/signup=<?= ucfirst($user['user_username'])?>"> <!-- User page / name = username -->
                                <button title="Profile" id="fix_mobile_signup" class="signup_button"><?= ucfirst($user['user_username']) ?></button>
                            </a>   
                        <?php elseif ($this->isConnectGoogle() && $this->isConnectWebsite() && !$this->isConnectLeague() && !$this->isConnectLeagueLf()): ?>  <!-- No session looking for, league  -->
                            <a href="/logout"><!-- Log out button -->
                                <button type="button" title="Log out" id="fix_mobile_signup" class="signup_button" >Log out</button>
                            </a>
                            <a href="/signup=<?= ucfirst($user['user_username'])?>"> <!-- User page / name = username -->
                                <button title="Profile" id="fix_mobile_signup" class="signup_button"><?= ucfirst($user['user_username']) ?></button>
                            </a>   
                        <?php elseif ($this->isConnectGoogle() && !$this->isConnectWebsite()) : ?>
                            <a href="/signup"> <!-- User page / Diff name-->
                                <button id="fix_mobile_signup" title="Profile" class="signup_button"><?= ucfirst($googleUser['google_fullName']) ?></button>
                            </a>
                            <a href="/logout"><!-- Log out button -->
                                <button type="button" title="Log out" id="fix_mobile_signup" class="signup_button" >Log out</button>
                            </a>
                        <?php endif; ?>
                </div>
            </div>

                <div class="mid_main_section_signup">
                    <p><?= $title ?></p>
                    <?php if ($this->isConnectGoogle() && $this->isConnectWebsite() && $this->isConnectLeague() && $this->isConnectLeagueLf()) : ?>
                        <a href="/swiping">
                            <button id="mid_main_section_button2">Swipe now</button> 
                        </a>
                    <?php elseif ($this->isConnectGoogle()) : ?>
                        <a href="/signup">
                            <button id="mid_main_section_button2">Join now</button> 
                        </a>
                    <?php else : ?>
                        <input id="mid_main_section_button" value="Join now" >
                    <?php endif; ?>
                </div>
            </nav>           
    </section>
</header>

    <main>
        <?php if(isset($_GET['message'])) :?>
            <span class="form-error"><?= $_GET['message'] ?></span>
        <?php endif; ?>
        <?php require $template.".phtml"; ?> 
    </main>
</body>

<footer>
    <div class="footer_black">
        <div class="top_footer">
            <p>Copyright © 2023 URSG</p>
            <p>Your Soulmate gamer</p>
        </div>

        <div class="mid_footer">
        <a href="/legalNotice">Legal notice</a>
        <a href="/siteMap"> Site map</a>
        </div>

        <div class="social_footer">
            <a href="https://discord.gg/Bfpkws74V3" target="_blank">
                <img src="public/images/discord2.png" alt="logo discord" loading="lazy"></a>
            <a href="https://twitter.com/Dosylia" target="_blank">
                <img src="public/images/twitter2.png" alt="logo twitter/x" loading="lazy"></a>
        </div>

        <div class="bot_footer">
            <p>Made by :  <a href="https://www.dosylia.com/">Dosylia</a></p>
            <p>Artwork by :  <a href="https://twitter.com/ShadowLilithArt/">ShadowLilithArt</a></p>       
        </div>
    </div>   
</footer>

