<!DOCTYPE html>
<html lang="en">

<head>
<script src="https://accounts.google.com/gsi/client" async defer></script>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title><?php echo $page_title; ?></title>
    <meta property="og:title" content="URSG - Your Soulmate Gamer">
    <meta property="og:description" content="It is time to find your soulmate. And there is no better place than here.">
    <meta property="og:url" content="https://ur-sg.com/"> 
    <meta property="og:image" content="public/images/logo_ursg.png">
    <meta name="description" content="URSG - Your Soulmate Gamer is a website to help you spend good quality time with the right person.">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link href="public/css/style.css" rel="stylesheet">
    <link rel="canonical" href="<?php echo $current_url; ?>" />
    <link rel="icon" type="image/png" href="public/images/favicon/favicon.ico">
    <link rel="icon" type="image/png" sizes="32x32" href="public/images/favicon/favicon-32x32.png"> 
    <link rel="icon" type="image/png" sizes="16x16" href="public/images/favicon/favicon-16x16.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Geologica&display=swap" rel="stylesheet">
    <meta property="og:type" content="website">
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://ur-sg.com/">
    <meta property="twitter:title" content="URSG - Your Soulmate Gamer">
    <meta property="twitter:description" content="It is time to find your soulmate. And there is no better place than here."> 
    <meta property="twitter:image" content="public/images/logo_ursg.png">
    <meta http-equiv="X-XSS-Protection" content="1; mode=block">
  <meta http-equiv="X-Content-Type-Options" content="nosniff">
  <meta http-equiv="Strict-Transport-Security" content="max-age=31536000; includeSubDomains">
</head>

