<?php
    if (!isset($page_css) || !is_array($page_css)) {
        $page_css = [];
    }
    array_unshift($page_css, 'layout_swiping');
    require "views/layout.phtml"; 
?>

<?php 
    if (!isset($_COOKIE['auth_token'])) {
        header("Location: /logout");
        return;
    }
?>

<?php if (isset($_SESSION['mode'])) : ?>
    <body class="<?= ($_SESSION['mode'] === 'dark') ? 'dark-mode' : '' ?>">
<?php else : ?>
    <body>
<?php endif; ?>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P3XDDBJQ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<script src="public/js/swiping/notifications_system.js?<?= time(); ?>"></script>
<input id="userUsername" type="hidden" name="userId" value="<?= $_SESSION['username']; ?>">
<input id="userId" type="hidden" name="userId" value="<?= $_SESSION['userId']; ?>">

<header>
    <nav>
        <div class="nav_swiping">
            <div>
                <a href="/"><img title="Home" class="scale" src="public/images/favicon/android-chrome-512x512.png" alt="logo_ursg"></a>
            </div>

            <div class="nav-swiping-row">
                <a href="/swiping"><img title="Swipe" class="scaleNoRound" src="public/images/swipe-icon.png" alt="swipe"></a>
                <a href="/playerfinder"><img title="Player Finder" class="scaleNoRound" src="public/images/playerfinder.png" alt="swipe"></a>
                <div class="chat_nav">
                    <a href="/persoChat&firstFriend=yes"><img title="Chat" class="scaleNoRound" src="public/images/chat-4-128.png" alt="chat"></a>
                    <span id="unread_messages_container"></span>
                </div>

                <div class="currency" title="<?= $user['user_currency'] ?>">
                    <a href="/store">
                        <p>
                            <img src="public/images/soulhard.png" alt="soulhard">
                            <span id="currency">0</span> 
                        </p>
                    </a>
                    <span id="displayMoneyWon"></span>
                </div>

                <div class="chat_profile">
                    <?php if (isset($user['user_picture']) && $user['user_picture'] !== null) : ?>
                        <a id="open_menu_profile"><img class="scale" src="public/upload/<?= $user['user_picture']; ?>" alt="Profile picture of user<?= $user['user_username'] ?>" ></a>
                    <?php else : ?>
                        <a id="open_menu_profile"><img class="scale" src="public/images/defaultprofilepicture.jpg" alt="default profile picture" ></a>
                    <?php endif; ?>
                    <span id="notification-center-ctn">
                        <i class="fa-solid fa-bell" id="notification-bell" data-listener-attached="true"><span class="notif-badge" id="notif-badge" style="display: none;"></span></i>
                    </span>
                    <span id="pending_friend_requests_container"></span>
                </div>

                <div>
                    <a href="/settings"><i class="fa-solid fa-cog scale scaleNoRound"></i></a>
                </div>
            </div>
        </div>
    </nav>
</header>
    <main>
        <div id="overlay"></div>
        <?php if (isset($_GET['message'])) : ?>
            <span class="form-error"><?= $_GET['message'] ?></span>
        <?php endif; ?>
        <?php require $template . ".phtml"; ?>
        <span class="notification-span"></span>
        <!-- Pop up to promote URSG tournament -->
        <div id="tournament-modal" class="modal tournament-modal-hidden">
            <div class="modal-content" style="z-index: 1000000;">
                <span id="close-modal-tournament" class="close">&times;</span>
                <h2>URSG Tournament</h2>
                <p style="margin-bottom: 6px;">Gather your team and join our exciting URSG tournament to showcase your skills!</p>
                <p style="margin-bottom: 30px;">Pricepool of 60€+ depending on the amount of teams</p>
                <img class="tournament-image" src="public/images/ursg-tournament.png" alt="URSG Tournament">
                <a href="https://t.co/W0SlBkwxlc" target="_blank" class="tournament-button">Join Now</a>
            </div>
        </div>
    </main>  
    <script src="public/js/swiping/swiping_menu.js?<?= time(); ?>"></script>
    <script src="public/js/swiping/get_notifications.js?<?= time(); ?>"></script>  
    <script src="public/js/swiping/get_currency.js?<?= time(); ?>"></script>
    <script src="public/js/swiping/tournament_modal.js?<?= time(); ?>"></script>
    <!-- Triggers for tracking scritps -->
    <script>
        window.addEventListener('DOMContentLoaded', function () {
            // Send page view event
            if (typeof sendPageView === 'function') {
                sendPageView('swiping_page');
            }
            // Check if user is returning and send event
            if (typeof sendReturningUserEvent === 'function') {
                sendReturningUserEvent();
            }
        });    
     </script>
</body>

<script nonce="TAJKETR">
  document.addEventListener("DOMContentLoaded", function() {
      let token = <?php echo json_encode($_SESSION['masterTokenWebsite'] ?? null); ?>;
      if (token) {
          localStorage.setItem('masterTokenWebsite', token);
      }
  });
</script>

</html>