<?php require "views/layout.phtml"; ?> 
<header>
    <nav>
        <div class="nav_swiping">
            <a href="index.php"><img title="Home" class="scale" src="public/images/favicon/favicon.ico" alt="logo_ursg"></a>
            <div class="toggle-container">
                <div title="Dark mode" id="toggle-button" class="toggle-button"></div>
            </div>
        </div>
    </nav>
</header>

<?php if (isset($_SESSION['mode'])) : ?>
    <body class="<?= ($_SESSION['mode'] === 'dark') ? 'dark-mode' : '' ?>">
<?php else : ?>
    <body>
<? endif; ?>
    <main>
        <?php if(isset($_GET['message'])) :?>
            <span class="form-error"><?= $_GET['message'] ?></span>
        <?php endif; ?>
        <?php require $template.".phtml"; ?> 
    </main>
</body>

<footer>
    <div class="footer_grey">
        <div class="top_footer">
            <p>Copyright © 2023 URSG</p>
            <p>Your Soulmate gamer</p>
        </div>

        <div class="mid_footer">
            <a href="mentionslegales">Privacy Policy</a>
            <a href="sitemap.php"> Site map</a>
        </div>

        <div class="social_footer">
            <a href="#">
                <img src="public/images/discord2.png" alt="logo discord"></a>
            <a href="#">
                <img src="public/images/twitter2.png" alt="logo twitter/x"></a>
        </div>

        <div class="bot_footer">
            <p>Made by :  <a target="_blank" href="https://www.dosylia.com/">Dosylia</a></p>
            <p>Artwork by :  <a target="_blank" href="https://twitter.com/ShadowLilithArt/">ShadowLilithArt</a></p>       
        </div>
    </div>   
</footer>

<script src="public/js/swiping/swiping_menu.js"></script>