<?php require "views/layout.phtml"; ?> 

<header>
    <section class="main_section" proload>
        <div class="overlay"></div>
        <!-- Top of website start -->
        <div class="top_main_section"> 
            <div class="top_left_main_section">
                <a href="index.php">
                    <img class="logo_ursg" src="public/images/logo_ursg_white.png" alt="logo">
                </a>
            </div> 
            <!-- Nav of website start here -->
            <nav>
                <div class="top_right_main_section">
                    <div class="toggle-container">
                            <div title="Dark mode" id="toggle-button" class="toggle-button"></div>
                    </div>

                    <!-- PHP TO SHOW ALL DIFFERENT BUTTONS DEPENDING ON SESSION -->
                      
                    <?php if($this->isConnectWebsite()) :?>
                            <a href="index.php?action=logout"><!-- Log out button -->
                                <button title="Log out" id="fix_mobile_signup" class="signup_button" >Log out</button>
                            </a>
                            <a href="index.php?action=userpage&username=<?= ucfirst($user['user_username'])?>"> <!-- User page / name = username -->
                                <button title="Profile" id="fix_mobile_signup" class="signup_button"><?= ucfirst($user['user_username']) ?></button>
                            </a>
                        <?php elseif ($this->isConnectGoogle() && !$this->isConnectWebsite()) : ?>
                            <a href="index.php?action=logout"> <!-- Log out button -->
                                <button id="fix_mobile_signup" class="signup_button" title="Log in" >Log out</button>
                            </a>
                            <a href="index.php?action=userpage&username=<?= ucfirst($user['user_usersUid'])?>"> <!-- User page / Diff name-->
                                <button id="fix_mobile_signup" title="Profile" class="signup_button"><?= ucfirst($googleUser['google_fullName']) ?></button>
                            </a>
                        <?php else : ?>
                            <button title="Sign up/Sign in" id="signup_button"> Sign up/Log in</button>
                        <?php endif; ?>
                </div>
            </div>

                <div class="mid_main_section">
                    <p><?= $title ?></p>
                    <br><br><br><br>

                    <?php if ($this->isConnectGoogle() && $this->isConnectWebsite()) : ?>
                        <a href="index.php?action=swiping">
                            <button id="mid_main_section_button2">Swipe now</button> 
                        </a>
                    <?php else : ?>
                        <button id="mid_main_section_button">Join now</button> 
                    <?php endif; ?>
                </div>
            </nav>           
    </section>

    <!-- POP UP FOR LOG IN -->
    <dialog id="favDialog">
        <!-- Display of Log in button, cancel and terms of use -->
        <section class="loginsignin">
            <h2>Sign up/Log in</h2><br><br>
                <p>When clicking on sign in,<br> you agree to <a href="">our terms of use</a>.</p><br>
                <script src="public/js/ajaxGoogle.js"></script>
            <div class="social_buttons2">
                <div id="buttonDiv"></div>
            </div><br>
            <!-- Get out of pop up -->
            <button id="cancelBtn">Cancel</button>
            <br><br>
        </section>

        <!-- Display of buttons to download app on App store/Google Store -->
        <section class="download_app_dialog">  
            <p>Download the app</p>
            <div class="download_app_dialog_logos">
                <a href=""><img id="apple_logo" src="public/images/appstore.png" alt="appstore"></a>
                <a href=""><img id="google_logo" src="public/images/googleplay.png" alt="googleplay"></a>
            </div>  
        </section>
    </dialog>
</header>

<body>
    <main>
        <?php if(isset($_GET['message'])) :?>
            <span class="form-error"><?= $_GET['message'] ?></span>
        <?php endif; ?>
        <?php require $template.".phtml"; ?> 
    </main>
</body>

<footer>
    <div class="footer_black">
        <div class="top_footer">
            <p>Copyright © 2023 URSG</p>
            <p>Your Soulmate gamer</p>
        </div>

        <div class="mid_footer">
            <a href="mentionslegales">Privacy Policy</a>
            <a href="sitemap.php"> Site map</a>
        </div>

        <div class="social_footer">
            <a href="#">
                <img src="public/images/discord2.png" alt="logo discord"></a>
            <a href="#">
                <img src="public/images/twitter2.png" alt="logo twitter/x"></a>
        </div>

        <div class="bot_footer">
            <p>Made by :  <a href="https://www.dosylia.com/">Dosylia</a></p>
            <p>Artwork by :  <a href="https://twitter.com/ShadowLilithArt/">ShadowLilithArt</a></p>       
        </div>
    </div>   
</footer>


<script src="https://accounts.google.com/gsi/client" async defer></script>
<script src="public/js/dialogGoogle.js"></script>

