<?php require "views/layout.phtml"; ?>
<?php if (isset($_SESSION['mode'])) : ?>
    <body class="<?= ($_SESSION['mode'] === 'dark') ? 'dark-mode' : '' ?>">
<?php else : ?>
    <body>
<?php endif; ?>

<input id="userUsername" type="hidden" name="userId" value="<?= $_SESSION['username']; ?>">
<input id="userId" type="hidden" name="userId" value="<?= $_SESSION['userId']; ?>">

<header class="admin-header">
  <nav class="admin-nav">
    <ul>
      <li><a href="/">Home Website</a></li>
      <li><a href="admin">Home Admin</a></li>
      <li><a href="adminUsers">Users</a></li>
      <li><a href="adminGame">Game</a></li>
      <li><a href="adminReports">Reports</a></li>
      <li><a href="adminStats">Statistics</a></li>
      <li><a href="adminSettings">Settings</a></li>
    </ul>
  </nav>
</header>
    <main>
        <?php if (isset($_GET['message'])) : ?>
            <span class="form-error"><?= $_GET['message'] ?></span>
        <?php endif; ?>
        <?php require $template . ".phtml"; ?>
        <span class="notification-span"></span>
    </main>
</body>

</html>