<?php require "views/layout.phtml"; ?>
<?php if (isset($_SESSION['mode'])) : ?>
    <body class="<?= ($_SESSION['mode'] === 'dark') ? 'dark-mode' : '' ?>">
<?php else : ?>
    <body>
<?php endif; ?>

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P3XDDBJQ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<input id="userUsername" type="hidden" name="userId" value="<?= $_SESSION['username']; ?>">
<input id="userId" type="hidden" name="userId" value="<?= $_SESSION['userId']; ?>">

<header class="admin-header">
  <nav class="admin-nav">
    <ul>
      <li><a href="/">Home Website</a></li>
      <li><a href="admin">Home Admin</a></li>
      <li><a href="adminUsers">Users</a></li>
      <?php if ($this->isAdmin() || $this->isModerator()) : ?>
        <li><a href="adminGame">Game</a></li>
        <li><a href="adminReports">Reports</a></li>
        <li><a href="adminStore">Store</a></li>
        <li><a href="adminDiscordBot">Discord Bot</a></li>
      <?php endif; ?>
      <?php if ($this->isAdmin() || $this->isMarketing()) : ?>
        <li><a href="adminPartnerPage">Partners</a></li>
      <?php endif; ?>
      <!-- <li><a href="adminStats">Statistics</a></li>
      <li><a href="adminSettings">Settings</a></li> -->
    </ul>
  </nav>
</header>
    <main>
        <?php if (isset($_GET['message'])) : ?>
            <span class="form-error"><?= $_GET['message'] ?></span>
        <?php endif; ?>
        <?php require $template . ".phtml"; ?>
        <span class="notification-span"></span>
    </main>
</body>

</html>