<section id="legalNotice">
    <h1><?= $this->_('legal_notice_header') ?></h1>
        <p class="date"><?= $this->_('last_updated') ?></p>
        <p><?= $this->_('legal_notice_text1') ?></p>
        <p><?= $this->_('legal_notice_text2') ?> <a href="https://www.termsfeed.com/privacy-policy-generator/">Privacy Policy Generator</a>.</p>

        <h2><?= $this->_('legal_notice_header2') ?> </h2>

        <p><?= $this->_('legal_notice_text3') ?></p>
        <p><strong><?= $this->_('legal_notice_email') ?></strong> contact@ur-sg.com</p>
        <p><strong><?= $this->_('legal_notice_address') ?></strong> Lyon, France.</p>
        
        <h2><?= $this->_('legal_notice_header3') ?></h2>
        
        <h3><?= $this->_('legal_notice_interpretation') ?></h3>
        <p><?= $this->_('legal_notice_text4') ?></p>
        
        <h3><?= $this->_('legal_notice_definitions') ?></h3>
        <p><?= $this->_('legal_notice_text5') ?></p>
        <ul>
            <li><strong><?= $this->_('legal_notice_account') ?></strong> <?= $this->_('legal_notice_account_text') ?></li>
            <li><strong><?= $this->_('legal_notice_affiliate') ?></strong> <?= $this->_('legal_notice_affiliate_text') ?></li>
            <li><strong><?= $this->_('legal_notice_company') ?></strong> <?= $this->_('legal_notice_company_text') ?></li>
            <li><strong><?= $this->_('legal_notice_cookies') ?></strong> <?= $this->_('legal_notice_cookies_text') ?></li>
            <li><strong><?= $this->_('legal_notice_country') ?></strong> <?= $this->_('legal_notice_country_text') ?></li>
            <li><strong><?= $this->_('legal_notice_device') ?></strong> <?= $this->_('legal_notice_device_text') ?></li>
            <li><strong><?= $this->_('legal_notice_personal_data') ?></strong> <?= $this->_('legal_notice_personal_data_text') ?></li>
            <li><strong><?= $this->_('legal_notice_service') ?></strong> <?= $this->_('legal_notice_service_text') ?></li>
            <li><strong><?= $this->_('legal_notice_service_provider') ?></strong> <?= $this->_('legal_notice_service_provider_text') ?></li>
            <li><strong><?= $this->_('legal_notice_third_party') ?></strong> <?= $this->_('legal_notice_third_party_text') ?></li>
            <li><strong><?= $this->_('legal_notice_usage_data') ?></strong> <?= $this->_('legal_notice_usage_data_text') ?></li>
            <li><strong><?= $this->_('legal_notice_website') ?></strong> <?= $this->_('legal_notice_website_text') ?><a href="https://ur-sg.com">https://ur-sg.com</a></li>
            <li><strong><?= $this->_('legal_notice_you') ?></strong> <?= $this->_('legal_notice_you_text') ?></li>
        </ul>
        
        <h2><?= $this->_('legal_notice_collecting_data_header') ?></h2>
        
        <h3><?= $this->_('legal_notice_collecting_data_header2') ?></h3>
        
        <h4><?= $this->_('legal_notice_collecting_data_header3') ?></h4>
        <p><?= $this->_('legal_notice_collecting_data_text1') ?></p>
        <ul>
            <li><?= $this->_('legal_notice_email_address') ?></li>
            <li><?= $this->_('legal_notice_usage_data') ?></li>
        </ul>
        
        <h4><?= $this->_('legal_notice_usage_data') ?></h4>
        <p><?= $this->_('legal_notice_usage_data_text1') ?></p>
        <p><?= $this->_('legal_notice_usage_data_text2') ?></p>
        <p><?= $this->_('legal_notice_usage_data_text3') ?></p>
        <p><?= $this->_('legal_notice_usage_data_text4') ?></p>
        
        <h4><?= $this->_('legal_notice_third_party_text1') ?></h4>
        <p><?= $this->_('legal_notice_third_party_text2') ?></p>
        <ul>
            <li>Google</li>
            <li>Facebook</li>
            <li>Instagram</li>
            <li>Twitter</li>
            <li>LinkedIn</li>
        </ul>
        <p><?= $this->_('legal_notice_third_party_text3') ?></p>
        <p><?= $this->_('legal_notice_third_party_text4') ?></p>
        
        <h4><?= $this->_('legal_notice_tracking_header') ?></h4>
        <p><?= $this->_('legal_notice_tracking_text1') ?></p>
        <ul>
            <li><strong><?= $this->_('legal_notice_tracking_cookies') ?></strong> <?= $this->_('legal_notice_tracking_cookies_text') ?></li>
            <li><strong><?= $this->_('legal_notice_tracking_web_beacons') ?></strong> <?= $this->_('legal_notice_tracking_web_beacons_text') ?></li>
        </ul>
        <p><?= $this->_('legal_notice_tracking_text2') ?><a href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies">TermsFeed website</a> <?= $this->_('legal_notice_tracking_text3') ?></p>
        <p><?= $this->_('legal_notice_tracking_text4') ?></p>
        <ul>
            <li><strong><?= $this->_('legal_notice_tracking_text5') ?></strong>
                <ul>
                    <li><strong><?= $this->_('legal_notice_cookies_type') ?></strong> <?= $this->_('legal_notice_tracking_text9') ?></li>
                    <li><strong><?= $this->_('legal_notice_cookies_administered_by') ?></strong> <?= $this->_('legal_notice_tracking_text8') ?></li>
                    <li><strong><?= $this->_('legal_notice_cookies_purpose') ?></strong> <?= $this->_('legal_notice_tracking_text11') ?></li>
                </ul>
            </li>
            <li><strong><?= $this->_('legal_notice_tracking_text6') ?></strong>
                <ul>
                    <li><strong><?= $this->_('legal_notice_cookies_type') ?></strong> <?= $this->_('legal_notice_tracking_text10') ?></li>
                    <li><strong><?= $this->_('legal_notice_cookies_administered_by') ?></strong> <?= $this->_('legal_notice_tracking_text8') ?></li>
                    <li><strong><?= $this->_('legal_notice_cookies_purpose') ?></strong> <?= $this->_('legal_notice_tracking_text12') ?></li>
                </ul>
            </li>
            <li><strong><?= $this->_('legal_notice_tracking_text7') ?></strong>
                <ul>
                    <li><strong><?= $this->_('legal_notice_cookies_type') ?></strong> <?= $this->_('legal_notice_tracking_text10') ?></li>
                    <li><strong><?= $this->_('legal_notice_cookies_administered_by') ?></strong> <?= $this->_('legal_notice_tracking_text8') ?></li>
                    <li><strong><?= $this->_('legal_notice_cookies_purpose') ?></strong> <?= $this->_('legal_notice_tracking_text13') ?></li>
                </ul>
            </li>
        </ul>
        
        <h2><?= $this->_('legal_notice_use_of_data_header') ?></h2>
        <p><?= $this->_('legal_notice_use_of_data_text1') ?></p>
        <ul>
            <li><strong><?= $this->_('legal_notice_use_of_data_text2') ?></strong><?= $this->_('legal_notice_use_of_data_text3') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text4') ?></strong> <?= $this->_('legal_notice_use_of_data_text5') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text6') ?></strong> <?= $this->_('legal_notice_use_of_data_text7') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text8') ?></strong> <?= $this->_('legal_notice_use_of_data_text9') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text10') ?></strong> <?= $this->_('legal_notice_use_of_data_text11') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text12') ?></strong> <?= $this->_('legal_notice_use_of_data_text13') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text14') ?></strong> <?= $this->_('legal_notice_use_of_data_text15') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text16') ?></strong> <?= $this->_('legal_notice_use_of_data_text17') ?></li>
        </ul>

        <p><?= $this->_('legal_notice_use_of_data_header2') ?></p>
        <ul>
            <li><strong><?= $this->_('legal_notice_use_of_data_text18') ?></strong> <?= $this->_('legal_notice_use_of_data_text19') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text20') ?></strong> <?= $this->_('legal_notice_use_of_data_text21') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text22') ?></strong> <?= $this->_('legal_notice_use_of_data_text23') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text24') ?></strong> <?= $this->_('legal_notice_use_of_data_text25') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text26') ?></strong> <?= $this->_('legal_notice_use_of_data_text27') ?></li>
            <li><strong><?= $this->_('legal_notice_use_of_data_text28') ?></strong> <?= $this->_('legal_notice_use_of_data_text29') ?></li>
        </ul>

        <h2><?= $this->_('legal_notice_retention_personal_data_header') ?></h2>
        <p><?= $this->_('legal_notice_retention_personal_data_text1') ?></p>
        <p><?= $this->_('legal_notice_retention_personal_data_text2') ?></p>

        <h2><?= $this->_('legal_notice_retention_personal_data_header2') ?></h2>
        <p><?= $this->_('legal_notice_retention_personal_data_text3') ?></p>
        <p><?= $this->_('legal_notice_retention_personal_data_text4') ?></p>
        <p><?= $this->_('legal_notice_retention_personal_data_text5') ?></p>

        <h2><?= $this->_('legal_notice_retention_personal_data_header3') ?></h2>
        <p><?= $this->_('legal_notice_retention_personal_data_text6') ?></p>
        <p><?= $this->_('legal_notice_retention_personal_data_text7') ?></p>
        <p><?= $this->_('legal_notice_retention_personal_data_text8') ?></p>
        <p><?= $this->_('legal_notice_retention_personal_data_text9') ?></p>

        <h2><?= $this->_('legal_notice_retention_personal_data_header4') ?></h2>
        <h3><?= $this->_('legal_notice_retention_personal_data_header5') ?></h3>
        <p><?= $this->_('legal_notice_retention_personal_data_text10') ?></p>

        <h3><?= $this->_('legal_notice_retention_personal_data_header6') ?></h3>
        <p><?= $this->_('legal_notice_retention_personal_data_text11') ?></p>

        <h3><?= $this->_('legal_notice_retention_personal_data_header7') ?></h3>
        <p><?= $this->_('legal_notice_retention_personal_data_text12') ?></p>
        <ul>
            <li><?= $this->_('legal_notice_retention_personal_data_text13') ?></li>
            <li><?= $this->_('legal_notice_retention_personal_data_text14') ?></li>
            <li><?= $this->_('legal_notice_retention_personal_data_text15') ?></li>
            <li><?= $this->_('legal_notice_retention_personal_data_text16') ?></li>
            <li><?= $this->_('legal_notice_retention_personal_data_text17') ?></li>
        </ul>

        <h2><?= $this->_('legal_notice_retention_personal_data_header8') ?></h2>
        <p><?= $this->_('legal_notice_retention_personal_data_text18') ?></p>

        <h2><?= $this->_('legal_notice_retention_personal_data_header9') ?></h2>
        <p><?= $this->_('legal_notice_retention_personal_data_text19') ?></p>
        <p><?= $this->_('legal_notice_retention_personal_data_text20') ?></p>

        <h2><?= $this->_('legal_notice_links_header') ?></h2>
        <p><?= $this->_('legal_notice_links_text1') ?></p>
        <p><?= $this->_('legal_notice_links_text2') ?></p>

        <h2><?= $this->_('legal_notice_changes_header') ?></h2>
        <p><?= $this->_('legal_notice_changes_text1') ?></p>
        <p><?= $this->_('legal_notice_changes_text2') ?></p>
        <p><?= $this->_('legal_notice_changes_text3') ?></p>

        <h2><?= $this->_('legal_notice_riot_header') ?></h2>
        <p><?= $this->_('legal_notice_riot_text') ?></p>

        <h2><?= $this->_('legal_notice_contact_header') ?></h2>
        <p><?= $this->_('legal_notice_contact_text1') ?></p>
        <ul>
            <li><?= $this->_('legal_notice_contact_text2') ?> contact@ur-sg.com</li>
        </ul>
</section>