<section class="siteMap">
        <h1>Site Map</h1>
        <table>
            <thead>
                <tr>
                    <th>URL</th>
                    <th>Last Modified</th>
                    <th>Priority</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($xml->url as $url): ?>
                    <tr>
                        <td><a href="<?= $url->loc ?>" target="_blank"><?= $url->loc ?></a></td>
                        <td><?= $url->lastmod ?></td>
                        <td><?= $url->priority ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

         <a target="_blank" href="https://pixabay.com/users/floraphonic-38928062/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=185287">Sound Effect by floraphonic</a> from <a href="https://pixabay.com/sound-effects//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=185287">Pixabay</a>
    </section>