<section id="termsOfService">
    <h1>Terms of Service</h1>

        <h2>Acceptance of Terms</h2>
        <p>By accessing or using our service, you agree to be bound by these terms.</p>

        <h2>User Obligations</h2>
        <p> You agree to use the service only for lawful purposes and in accordance with these terms.</p>

        <h2>Intellectual Property</h2>
        <p>All content provided on the service is owned by or licensed to URSG.</p>

        <h2>Limitation of Liability</h2>
        <p>URSG shall not be liable for any damages arising from the use of the service.</p>

        <h2>Termination</h2>
        <p>We may terminate or suspend your account at any time for any reason, without notice.</p>

        <h2>Governing Law</h2>
        <p>These terms shall be governed by the laws of France.</p>

        <h2>Contact Us</h2>
        <p>If you have any questions about these Terms of Service, please contact us at contact@ur-sg.com.</p>
</section>