<div class="form_container"> 
    <form class="form_signup" method="post" action="/createLookingFor">

    <?php if (isset($_GET['error'])) : ?>
        <p class="errorsForm"><?= $_GET['error'] ?></p>
        <?php endif; ?>

        <label for="gender">Gender you are looking for</label>
        <select id="gender" name="gender" required>
            <option value="" disabled selected>Choose a gender...</option>
            <option value="Male">Male</option>
            <option value="Female">Female</option>
            <option value="Non Binary">Non binary</option>
            <option value="Male and Female">Male and Female</option>
            <option value="All">All</option>
        </select>

            <label for="kindofgamer">What kind of gamer are you looking for?</label>
        <select id="kindofgamer" name="kindofgamer" required>
            <option value="" disabled selected>Chose what kind you are looking for...</option>
            <option value="Chill">Chill / Normal games</option>
            <option value="Competition">Competition / Ranked</option>
            <option value="Competition and Chill">Competition/Ranked and chill</option>
        </select>

        <div class="checkbox-container">
            <label for="skipSelection">Skip agent selection</label>
            <input type="checkbox" id="skipSelection" name="skipSelection" value="1">
        </div>
                
        <div id="championSelection">
            <h2>Pick 3 mains you would like to play with</h2>
                <label for="main1">Main 1</label>
                <button type="button" id="btnMain1">Select main 1</button>
                <div id="popupMain1">
                        <input type="text" id="search1" autocomplete="no-autofill" placeholder="Search..." class="notranslate">
                        <ul class="main1Ul">
                            <?php include 'views/signup/options_champion_valorant.phtml' ?>
                        <ul>
                </div>

                <input type="hidden" id="main1" name="main1" value="" class="notranslate">

                <label for="main2">Main 2</label>
                <button type="button" id="btnMain2">Select main 2</button>
                <div id="popupMain2">
                        <input type="text" id="search2" autocomplete="no-autofill" placeholder="Search..." class="notranslate">
                        <ul class="main2Ul">
                            <?php include 'views/signup/options_champion_valorant.phtml' ?>
                        <ul>
                </div>

                <input type="hidden" id="main2" name="main2" value="" class="notranslate">

                <label for="main3">Main 3</label>
                <button type="button" id="btnMain3">Select main 3</button>
                <div id="popupMain3">
                        <input type="text" id="search3" autocomplete="no-autofill" placeholder="Search..." class="notranslate">
                        <ul class="main3Ul">
                            <?php include 'views/signup/options_champion_valorant.phtml' ?>
                        <ul>
                </div>

                <input type="hidden" id="main3" name="main3" value="" class="notranslate">


                    <script src="public/js/champions.js"></script>
        </div>

            <label for="rank_valorant">Rank you are looking for</label>
            <select id="rank_valorant" name="rank_valorant">
            <option value="" disabled selected>Select rank...</option>
            <option value="Unranked" data-image="public/images/valorant_ranks/Unranked.png">Unranked</option>
            <option value="Iron" data-image="public/images/valorant_ranks/Iron.png">Iron</option>
            <option value="Bronze" data-image="public/images/valorant_ranks/Bronze.png">Bronze</option>
            <option value="Silver" data-image="public/images/valorant_ranks/Silver.png">Silver</option>
            <option value="Gold" data-image="public/images/valorant_ranks/Gold.png">Gold</option>
            <option value="Platinum" data-image="public/images/valorant_ranks/Platinum.png">Platinum</option>
            <option value="Diamond" data-image="public/images/valorant_ranks/Diamond.png">Diamond</option>
            <option value="Ascendant" data-image="public/images/valorant_ranks/Ascendant.png">Ascendant</option>
            <option value="Immortal" data-image="public/images/valorant_ranks/Immortal.png">Immortal</option>
            <option value="Radiant" data-image="public/images/valorant_ranks/Radiant.png">Radiant</option>
            <option value="Any" data-image="public/images/valorant_ranks/Any.png">Any</option>
            </select>

            <div id="selected-ranks-valorant"></div>

            <script src="public/js/ranks-valorant.js"></script>

            <label for="role_valorant">Role you are looking for</label>
            <select id="role_valorant" name="role_valorant">
            <option value="Controller" data-image="public/images/valorant_roles/Controller.webp">Controller</option>
            <option value="Duelist" data-image="public/images/valorant_roles/Duelist.webp">Duelist</option>
            <option value="Initiator" data-image="public/images/valorant_roles/Initiator.webp">Initiator</option>
            <option value="Sentinel" data-image="public/images/valorant_roles/Sentinel.webp">Sentinel</option>
            <option value="Fill" data-image="public/images/roles/fill.png">Fill</option>
            <option value="Any" data-image="public/images/valorant_ranks/Any.png">Any</option>
            </select>

            <div id="selected-roles-valorant"></div>

            <script src="public/js/roles-valorant.js"></script>

            <input type="hidden" name="game" value="Valorant"> 

            <?php if($this->isConnectWebsite()) : ?>
            <input type="hidden" name="userId" value="<?= $_SESSION['userId'] ?>">  
        <?php endif ; ?>

        <input name="submit" id="send-button" type="submit" value="Send">
    </form>
    <img class="picture_with_form" src="public/images/jett.png" alt="Jett from Valorant">
</div>

<script type="module" src="public/js/valorantinfo.js"></script>

