<li value="Astra" data-image="public/images/valorant_champions/Astra_icon.webp">
<img src="public/images/valorant_champions/Astra_icon.webp" alt="Astra Icon" loading="lazy"> Astra
</li>
<li value="Breach" data-image="public/images/valorant_champions/Breach_icon.webp">
<img src="public/images/valorant_champions/Breach_icon.webp" alt="Breach Icon" loading="lazy"> Breach
</li>
<li value="Brimstone" data-image="public/images/valorant_champions/Brimstone_icon.webp">
<img src="public/images/valorant_champions/Brimstone_icon.webp" alt="Brimstone Icon" loading="lazy"> Brimstone
</li>
<li value="Chamber" data-image="public/images/valorant_champions/Chamber_icon.webp">
<img src="public/images/valorant_champions/Chamber_icon.webp" alt="Chamber Icon" loading="lazy"> Chamber
</li>
<li value="Cypher" data-image="public/images/valorant_champions/Cypher_icon.webp">
<img src="public/images/valorant_champions/Cypher_icon.webp" alt="Cypher Icon" loading="lazy"> Cypher
</li>
<li value="Fade" data-image="public/images/valorant_champions/Fade_icon.webp">
<img src="public/images/valorant_champions/Fade_icon.webp" alt="Fade Icon" loading="lazy"> Fade
</li>
<li value="Gekko" data-image="public/images/valorant_champions/Gekko_icon.webp">
<img src="public/images/valorant_champions/Gekko_icon.webp" alt="Gekko Icon" loading="lazy"> Gekko
</li>
<li value="Harbor" data-image="public/images/valorant_champions/Harbor_icon.webp">
<img src="public/images/valorant_champions/Harbor_icon.webp" alt="Harbor Icon" loading="lazy"> Harbor
</li>
<li value="Kayo" data-image="public/images/valorant_champions/Kayo_icon.webp">
<img src="public/images/valorant_champions/Kayo_icon.webp" alt="Kayo Icon" loading="lazy"> Kayo
</li>
<li value="Jett" data-image="public/images/valorant_champions/Jett_icon.webp">
<img src="public/images/valorant_champions/Jett_icon.webp" alt="Jett Icon" loading="lazy"> Jett
</li>
<li value="Killjoy" data-image="public/images/valorant_champions/Killjoy_icon.webp">
<img src="public/images/valorant_champions/Killjoy_icon.webp" alt="Killjoy Icon" loading="lazy"> Killjoy
</li>
<li value="Neon" data-image="public/images/valorant_champions/Neon_icon.webp">
<img src="public/images/valorant_champions/Neon_icon.webp" alt="Neon Icon" loading="lazy"> Neon
</li>
<li value="Omen" data-image="public/images/valorant_champions/Omen_icon.webp">
<img src="public/images/valorant_champions/Omen_icon.webp" alt="Omen Icon" loading="lazy"> Omen
</li>
<li value="Phoenix" data-image="public/images/valorant_champions/Phoenix_icon.webp">
<img src="public/images/valorant_champions/Phoenix_icon.webp" alt="Phoenix Icon" loading="lazy"> Phoenix
</li>
<li value="Raze" data-image="public/images/valorant_champions/Raze_icon.webp">
<img src="public/images/valorant_champions/Raze_icon.webp" alt="Raze Icon" loading="lazy"> Raze
</li>
<li value="Reyna" data-image="public/images/valorant_champions/Reyna_icon.webp">
<img src="public/images/valorant_champions/Reyna_icon.webp" alt="Reyna Icon" loading="lazy"> Reyna
</li>
<li value="Sage" data-image="public/images/valorant_champions/Sage_icon.webp">
<img src="public/images/valorant_champions/Sage_icon.webp" alt="Sage Icon" loading="lazy"> Sage
</li>
<li value="Skye" data-image="public/images/valorant_champions/Skye_icon.webp">
<img src="public/images/valorant_champions/Skye_icon.webp" alt="Skye Icon" loading="lazy"> Skye
</li>
<li value="Sova" data-image="public/images/valorant_champions/Sova_icon.webp">
<img src="public/images/valorant_champions/Sova_icon.webp" alt="Sova Icon" loading="lazy"> Sova
</li>
<li value="Viper" data-image="public/images/valorant_champions/Viper_icon.webp">
<img src="public/images/valorant_champions/Viper_icon.webp" alt="Viper Icon" loading="lazy"> Viper
</li>
<li value="Yoru" data-image="public/images/valorant_champions/Yoru_icon.webp">
<img src="public/images/valorant_champions/Yoru_icon.webp" alt="Yoru Icon" loading="lazy"> Yoru
</li>