        <li value="Aatrox" data-image="public/images/champions/Aatrox.png"><img src="public/images/champions/Aatrox.png"
                alt=""></li>
        <li value="Ahri" data-image="public/images/champions/Ahri.png"><img src="public/images/champions/Ahri.png"
                alt=""></li>
        <li value="Akali" data-image="public/images/champions/Akali.png"><img src="public/images/champions/Akali.png"
                alt=""></li>
        <li value="Alistar" data-image="public/images/champions/Alistar.png"><img
                src="public/images/champions/Alistar.png" alt=""></li>
        <li value="Amumu" data-image="public/images/champions/Amumu.png"><img src="public/images/champions/Amumu.png"
                alt=""></li>
        <li value="Anivia" data-image="public/images/champions/Anivia.png"><img src="public/images/champions/Anivia.png"
                alt=""></li>
        <li value="Annie" data-image="public/images/champions/Annie.png"><img src="public/images/champions/Annie.png"
                alt=""></li>
        <li value="Aphelios" data-image="public/images/champions/Aphelios.png"><img
                src="public/images/champions/Aphelios.png" alt=""></li>
        <li value="Ashe" data-image="public/images/champions/Ashe.png"><img src="public/images/champions/Ashe.png"
                alt=""></li>
        <li value="Aurelion Sol" data-image="public/images/champions/AurelionSol.png"><img
                src="public/images/champions/AurelionSol.png" alt=""></li>
        <li value="Aurora" data-image="public/images/champions/Aurora.png"><img
        src="public/images/champions/Aurora.png" alt=""></li>
        <li value="Azir" data-image="public/images/champions/Azir.png"><img src="public/images/champions/Azir.png"
                alt=""></li>
        <li value="Bard" data-image="public/images/champions/Bard.png"><img src="public/images/champions/Bard.png"
                alt=""></li>
        <li value="Belveth" data-image="public/images/champions/Belveth.png"><img
                src="public/images/champions/Belveth.png" alt=""></li>
        <li value="Blitzcrank" data-image="public/images/champions/Blitzcrank.png"><img
                src="public/images/champions/Blitzcrank.png" alt=""></li>
        <li value="Brand" data-image="public/images/champions/Brand.png"><img src="public/images/champions/Brand.png"
                alt=""></li>
        <li value="Braum" data-image="public/images/champions/Braum.png"><img src="public/images/champions/Braum.png"
        alt=""></li>
        <li value="Briar" data-image="public/images/champions/Briar.png"><img src="public/images/champions/Briar.png"
        alt=""></li>
        <li value="Caitlyn" data-image="public/images/champions/Caitlyn.png"><img
                src="public/images/champions/Caitlyn.png" alt=""></li>
        <li value="Camille" data-image="public/images/champions/Camille.png"><img
                src="public/images/champions/Camille.png" alt=""></li>
        <li value="Cassiopeia" data-image="public/images/champions/Cassiopeia.png"><img
                src="public/images/champions/Cassiopeia.png" alt=""></li>
        <li value="ChoGath" data-image="public/images/champions/Chogath.png"><img
                src="public/images/champions/Chogath.png" alt=""></li>
        <li value="Corki" data-image="public/images/champions/Corki.png"><img src="public/images/champions/Corki.png"
                alt=""></li>
        <li value="Darius" data-image="public/images/champions/Darius.png"><img src="public/images/champions/Darius.png"
                alt=""></li>
        <li value="Diana" data-image="public/images/champions/Diana.png"><img src="public/images/champions/Diana.png"
                alt=""></li>
        <li value="Dr. Mundo" data-image="public/images/champions/DrMundo.png"><img
                src="public/images/champions/DrMundo.png" alt=""></li>
        <li value="Draven" data-image="public/images/champions/Draven.png"><img src="public/images/champions/Draven.png"
                alt=""></li>
        <li value="Ekko" data-image="public/images/champions/Ekko.png"><img src="public/images/champions/Ekko.png"
                alt=""></li>
        <li value="Elise" data-image="public/images/champions/Elise.png"><img src="public/images/champions/Elise.png"
                alt=""></li>
        <li value="Evelynn" data-image="public/images/champions/Evelynn.png"><img
                src="public/images/champions/Evelynn.png" alt=""></li>
        <li value="Ezreal" data-image="public/images/champions/Ezreal.png"><img src="public/images/champions/Ezreal.png"
                alt=""></li>
        <li value="Fiddlesticks" data-image="public/images/champions/Fiddlesticks.png"><img
                src="public/images/champions/Fiddlesticks.png" alt=""></li>
        <li value="Fiora" data-image="public/images/champions/Fiora.png"><img src="public/images/champions/Fiora.png"
                alt=""></li>
        <li value="Fizz" data-image="public/images/champions/Fizz.png"><img src="public/images/champions/Fizz.png"
                alt=""></li>
        <li value="Galio" data-image="public/images/champions/Galio.png"><img src="public/images/champions/Galio.png"
                alt=""></li>
        <li value="Gangplank" data-image="public/images/champions/Gangplank.png"><img
                src="public/images/champions/Gangplank.png" alt=""></li>
        <li value="Garen" data-image="public/images/champions/Garen.png"><img src="public/images/champions/Garen.png"
                alt=""></li>
        <li value="Gnar" data-image="public/images/champions/Gnar.png"><img src="public/images/champions/Gnar.png"
                alt=""></li>
        <li value="Gragas" data-image="public/images/champions/Gragas.png"><img src="public/images/champions/Gragas.png"
                alt=""></li>
        <li value="Graves" data-image="public/images/champions/Graves.png"><img src="public/images/champions/Graves.png"
                alt=""></li>
        <li value="Gwen" data-image="public/images/champions/Gwen.png"><img src="public/images/champions/Gwen.png"
                alt=""></li>
        <li value="Hecarim" data-image="public/images/champions/Hecarim.png"><img
                src="public/images/champions/Hecarim.png" alt=""></li>
        <li value="Heimerdinger" data-image="public/images/champions/Heimerdinger.png"><img
                src="public/images/champions/Heimerdinger.png" alt=""></li>
        <li value="Hwei" data-image="public/images/champions/Hwei.png"><img
        src="public/images/champions/Hwei.png" alt=""></li>
        <li value="Illaoi" data-image="public/images/champions/Illaoi.png"><img src="public/images/champions/Illaoi.png"
                alt=""></li>
        <li value="Irelia" data-image="public/images/champions/Irelia.png"><img src="public/images/champions/Irelia.png"
                alt=""></li>
        <li value="Ivern" data-image="public/images/champions/Ivern.png"><img src="public/images/champions/Ivern.png"
                alt=""></li>
        <li value="Janna" data-image="public/images/champions/Janna.png"><img src="public/images/champions/Janna.png"
                alt=""></li>
        <li value="Jarvan IV" data-image="public/images/champions/JarvanIV.png"><img
                src="public/images/champions/JarvanIV.png" alt=""></li>
        <li value="Jax" data-image="public/images/champions/Jax.png"><img src="public/images/champions/Jax.png" alt="">
        </li>
        <li value="Jayce" data-image="public/images/champions/Jayce.png"><img src="public/images/champions/Jayce.png"
                alt=""></li>
        <li value="Jhin" data-image="public/images/champions/Jhin.png"><img src="public/images/champions/Jhin.png"
                alt=""></li>
        <li value="Jinx" data-image="public/images/champions/Jinx.png"><img src="public/images/champions/Jinx.png"
                alt=""></li>
        <li value="KaiSa" data-image="public/images/champions/Kaisa.png"><img src="public/images/champions/Kaisa.png"
                alt=""></li>
        <li value="Kalista" data-image="public/images/champions/Kalista.png"><img
                src="public/images/champions/Kalista.png" alt=""></li>
        <li value="Karma" data-image="public/images/champions/Karma.png"><img src="public/images/champions/Karma.png"
                alt=""></li>
        <li value="Karthus" data-image="public/images/champions/Karthus.png"><img
                src="public/images/champions/Karthus.png" alt=""></li>
        <li value="Kassadin" data-image="public/images/champions/Kassadin.png"><img
                src="public/images/champions/Kassadin.png" alt=""></li>
        <li value="Katarina" data-image="public/images/champions/Katarina.png"><img
                src="public/images/champions/Katarina.png" alt=""></li>
        <li value="Kayle" data-image="public/images/champions/Kayle.png"><img src="public/images/champions/Kayle.png"
                alt=""></li>
        <li value="Kayn" data-image="public/images/champions/Kayn.png"><img src="public/images/champions/Kayn.png"
                alt=""></li>
        <li value="Kennen" data-image="public/images/champions/Kennen.png"><img src="public/images/champions/Kennen.png"
                alt=""></li>
        <li value="KhaZix" data-image="public/images/champions/Khazix.png"><img
                src="public/images/champions/Khazix.png" alt=""></li>
        <li value="Kindred" data-image="public/images/champions/Kindred.png"><img
                src="public/images/champions/Kindred.png" alt=""></li>
        <li value="Kled" data-image="public/images/champions/Kled.png"><img src="public/images/champions/Kled.png"
                alt=""></li>
        <li value="KogMaw" data-image="public/images/champions/KogMaw.png"><img
                src="public/images/champions/KogMaw.png" alt=""></li>
        <li value="Ksante" data-image="public/images/champions/Ksante.png"><img
                src="public/images/champions/Ksante.png" alt=""></li>
        <li value="LeBlanc" data-image="public/images/champions/Leblanc.png"><img
                src="public/images/champions/Leblanc.png" alt=""></li>
        <li value="Lee Sin" data-image="public/images/champions/LeeSin.png"><img
                src="public/images/champions/LeeSin.png" alt=""></li>
        <li value="Leona" data-image="public/images/champions/Leona.png"><img src="public/images/champions/Leona.png"
                alt=""></li>
        <li value="Lillia" data-image="public/images/champions/Lillia.png"><img src="public/images/champions/Lillia.png"
                alt=""></li>
        <li value="Lissandra" data-image="public/images/champions/Lissandra.png"><img
                src="public/images/champions/Lissandra.png" alt=""></li>
        <li value="Lucian" data-image="public/images/champions/Lucian.png"><img src="public/images/champions/Lucian.png"
                alt=""></li>
        <li value="Lulu" data-image="public/images/champions/Lulu.png"><img src="public/images/champions/Lulu.png"
                alt=""></li>
        <li value="Lux" data-image="public/images/champions/Lux.png"><img src="public/images/champions/Lux.png" alt="">
        </li>
        <li value="Malphite" data-image="public/images/champions/Malphite.png"><img
                src="public/images/champions/Malphite.png" alt=""></li>
        <li value="Malzahar" data-image="public/images/champions/Malzahar.png"><img
                src="public/images/champions/Malzahar.png" alt=""></li>
        <li value="Maokai" data-image="public/images/champions/Maokai.png"><img src="public/images/champions/Maokai.png"
                alt=""></li>
        <li value="Master Yi" data-image="public/images/champions/MasterYi.png"><img
                src="public/images/champions/MasterYi.png" alt=""></li>
        <li value="Milio" data-image="public/images/champions/Milio.png"><img src="public/images/champions/Milio.png"
                alt=""></li>
        <li value="Miss Fortune" data-image="public/images/champions/MissFortune.png"><img
                src="public/images/champions/MissFortune.png" alt=""></li>
        <li value="Mordekaiser" data-image="public/images/champions/Mordekaiser.png"><img
                src="public/images/champions/Mordekaiser.png" alt=""></li>
        <li value="Morgana" data-image="public/images/champions/Morgana.png"><img
                src="public/images/champions/Morgana.png" alt=""></li>
        <li value="Naafiri" data-image="public/images/champions/Naafiri.png"><img src="public/images/champions/Naafiri.png" alt=""></li>
        <li value="Nami" data-image="public/images/champions/Nami.png"><img src="public/images/champions/Nami.png" alt=""></li>
        <li value="Nasus" data-image="public/images/champions/Nasus.png"><img src="public/images/champions/Nasus.png"
                alt=""></li>
        <li value="Nautilus" data-image="public/images/champions/Nautilus.png"><img
                src="public/images/champions/Nautilus.png" alt=""></li>
        <li value="Neeko" data-image="public/images/champions/Neeko.png"><img src="public/images/champions/Neeko.png"
                alt=""></li>
        <li value="Nidalee" data-image="public/images/champions/Nidalee.png"><img
                src="public/images/champions/Nidalee.png" alt=""></li>
        <li value="Nocturne" data-image="public/images/champions/Nocturne.png"><img
                src="public/images/champions/Nocturne.png" alt=""></li>
        <li value="Nunu & Willump" data-image="public/images/champions/Nunu.png"><img
                src="public/images/champions/Nunu.png" alt=""></li>
        <li value="Olaf" data-image="public/images/champions/Olaf.png"><img src="public/images/champions/Olaf.png"
                alt=""></li>
        <li value="Orianna" data-image="public/images/champions/Orianna.png"><img
                src="public/images/champions/Orianna.png" alt=""></li>
        <li value="Ornn" data-image="public/images/champions/Ornn.png"><img src="public/images/champions/Ornn.png"
                alt=""></li>
        <li value="Pantheon" data-image="public/images/champions/Pantheon.png"><img
                src="public/images/champions/Pantheon.png" alt=""></li>
        <li value="Poppy" data-image="public/images/champions/Poppy.png"><img src="public/images/champions/Poppy.png"
                alt=""></li>
        <li value="Pyke" data-image="public/images/champions/Pyke.png"><img src="public/images/champions/Pyke.png"
                alt=""></li>
        <li value="Qiyana" data-image="public/images/champions/Qiyana.png"><img src="public/images/champions/Qiyana.png"
                alt=""></li>
        <li value="Quinn" data-image="public/images/champions/Quinn.png"><img src="public/images/champions/Quinn.png"
                alt=""></li>
        <li value="Rakan" data-image="public/images/champions/Rakan.png"><img src="public/images/champions/Rakan.png"
                alt=""></li>
        <li value="Rammus" data-image="public/images/champions/Rammus.png"><img src="public/images/champions/Rammus.png"
                alt=""></li>
        <li value="RekSai" data-image="public/images/champions/RekSai.png"><img
                src="public/images/champions/RekSai.png" alt=""></li>
        <li value="Renata" data-image="public/images/champions/Renata.png"><img
                src="public/images/champions/Renata.png" alt=""></li>
        <li value="Renekton" data-image="public/images/champions/Renekton.png"><img
                src="public/images/champions/Renekton.png" alt=""></li>
        <li value="Rengar" data-image="public/images/champions/Rengar.png"><img src="public/images/champions/Rengar.png"
                alt=""></li>
        <li value="Riven" data-image="public/images/champions/Riven.png"><img src="public/images/champions/Riven.png"
                alt=""></li>
        <li value="Rumble" data-image="public/images/champions/Rumble.png"><img src="public/images/champions/Rumble.png"
                alt=""></li>
        <li value="Ryze" data-image="public/images/champions/Ryze.png"><img src="public/images/champions/Ryze.png"
                alt=""></li>
        <li value="Samira" data-image="public/images/champions/Samira.png"><img src="public/images/champions/Samira.png"
                alt=""></li>
        <li value="Sejuani" data-image="public/images/champions/Sejuani.png"><img
                src="public/images/champions/Sejuani.png" alt=""></li>
        <li value="Senna" data-image="public/images/champions/Senna.png"><img src="public/images/champions/Senna.png"
                alt=""></li>
        <li value="Seraphine" data-image="public/images/champions/Seraphine.png"><img
                src="public/images/champions/Seraphine.png" alt=""></li>
        <li value="Sett" data-image="public/images/champions/Sett.png"><img src="public/images/champions/Sett.png"
                alt=""></li>
        <li value="Shaco" data-image="public/images/champions/Shaco.png"><img src="public/images/champions/Shaco.png"
                alt=""></li>
        <li value="Shen" data-image="public/images/champions/Shen.png"><img src="public/images/champions/Shen.png"
                alt=""></li>
        <li value="Shyvana" data-image="public/images/champions/Shyvana.png"><img
                src="public/images/champions/Shyvana.png" alt=""></li>
        <li value="Singed" data-image="public/images/champions/Singed.png"><img src="public/images/champions/Singed.png"
                alt=""></li>
        <li value="Sion" data-image="public/images/champions/Sion.png"><img src="public/images/champions/Sion.png"
                alt=""></li>
        <li value="Sivir" data-image="public/images/champions/Sivir.png"><img src="public/images/champions/Sivir.png"
                alt=""></li>
        <li value="Skarner" data-image="public/images/champions/Skarner.png"><img
                src="public/images/champions/Skarner.png" alt=""></li>
        <li value="Smolder" data-image="public/images/champions/Smolder.png"><img
        src="public/images/champions/Smolder.png" alt=""></li>
        <li value="Sona" data-image="public/images/champions/Sona.png"><img src="public/images/champions/Sona.png"
                alt=""></li>
        <li value="Soraka" data-image="public/images/champions/Soraka.png"><img src="public/images/champions/Soraka.png"
                alt=""></li>
        <li value="Swain" data-image="public/images/champions/Swain.png"><img src="public/images/champions/Swain.png"
                alt=""></li>
        <li value="Sylas" data-image="public/images/champions/Sylas.png"><img src="public/images/champions/Sylas.png"
                alt=""></li>
        <li value="Syndra" data-image="public/images/champions/Syndra.png"><img src="public/images/champions/Syndra.png"
                alt=""></li>
        <li value="Tahm Kench" data-image="public/images/champions/TahmKench.png"><img
                src="public/images/champions/TahmKench.png" alt=""></li>
        <li value="Taliyah" data-image="public/images/champions/Taliyah.png"><img
                src="public/images/champions/Taliyah.png" alt=""></li>
        <li value="Talon" data-image="public/images/champions/Talon.png"><img src="public/images/champions/Talon.png"
                alt=""></li>
        <li value="Taric" data-image="public/images/champions/Taric.png"><img src="public/images/champions/Taric.png"
                alt=""></li>
        <li value="Teemo" data-image="public/images/champions/Teemo.png"><img src="public/images/champions/Teemo.png"
                alt=""></li>
        <li value="Thresh" data-image="public/images/champions/Thresh.png"><img src="public/images/champions/Thresh.png"
                alt=""></li>
        <li value="Tristana" data-image="public/images/champions/Tristana.png"><img
                src="public/images/champions/Tristana.png" alt=""></li>
        <li value="Trundle" data-image="public/images/champions/Trundle.png"><img
                src="public/images/champions/Trundle.png" alt=""></li>
        <li value="Tryndamere" data-image="public/images/champions/Tryndamere.png"><img
                src="public/images/champions/Tryndamere.png" alt=""></li>
        <li value="Twisted Fate" data-image="public/images/champions/TwistedFate.png"><img
                src="public/images/champions/TwistedFate.png" alt=""></li>
        <li value="Twitch" data-image="public/images/champions/Twitch.png"><img src="public/images/champions/Twitch.png"
                alt=""></li>
        <li value="Udyr" data-image="public/images/champions/Udyr.png"><img src="public/images/champions/Udyr.png"
                alt=""></li>
        <li value="Urgot" data-image="public/images/champions/Urgot.png"><img src="public/images/champions/Urgot.png"
                alt=""></li>
        <li value="Varus" data-image="public/images/champions/Varus.png"><img src="public/images/champions/Varus.png"
                alt=""></li>
        <li value="Vayne" data-image="public/images/champions/Vayne.png"><img src="public/images/champions/Vayne.png"
                alt=""></li>
        <li value="Veigar" data-image="public/images/champions/Veigar.png"><img src="public/images/champions/Veigar.png"
                alt=""></li>
        <li value="VelKoz" data-image="public/images/champions/Velkoz.png"><img
                src="public/images/champions/Velkoz.png" alt=""></li>
        <li value="Vi" data-image="public/images/champions/Vi.png"><img src="public/images/champions/Vi.png" alt="">
        </li>
        <li value="Viego" data-image="public/images/champions/Viego.png"><img src="public/images/champions/Viego.png"
                alt=""></li>
        <li value="Viktor" data-image="public/images/champions/Viktor.png"><img src="public/images/champions/Viktor.png"
                alt=""></li>
        <li value="Vladimir" data-image="public/images/champions/Vladimir.png"><img
                src="public/images/champions/Vladimir.png" alt=""></li>
        <li value="Volibear" data-image="public/images/champions/Volibear.png"><img
                src="public/images/champions/Volibear.png" alt=""></li>
        <li value="Warwick" data-image="public/images/champions/Warwick.png"><img
                src="public/images/champions/Warwick.png" alt=""></li>
        <li value="Wukong" data-image="public/images/champions/Wukong.png"><img src="public/images/champions/Wukong.png"
                alt=""></li>
        <li value="Xayah" data-image="public/images/champions/Xayah.png"><img src="public/images/champions/Xayah.png"
                alt=""></li>
        <li value="Xerath" data-image="public/images/champions/Xerath.png"><img src="public/images/champions/Xerath.png"
                alt=""></li>
        <li value="Xin Zhao" data-image="public/images/champions/XinZhao.png"><img
                src="public/images/champions/XinZhao.png" alt=""></li>
        <li value="Yasuo" data-image="public/images/champions/Yasuo.png"><img src="public/images/champions/Yasuo.png"
                alt=""></li>
        <li value="Yone" data-image="public/images/champions/Yone.png"><img src="public/images/champions/Yone.png"
                alt=""></li>
        <li value="Yorick" data-image="public/images/champions/Yorick.png"><img src="public/images/champions/Yorick.png"
                alt=""></li>
        <li value="Yuumi" data-image="public/images/champions/Yuumi.png"><img src="public/images/champions/Yuumi.png"
                alt=""></li>
        <li value="Zac" data-image="public/images/champions/Zac.png"><img src="public/images/champions/Zac.png" alt="">
        </li>
        <li value="Zed" data-image="public/images/champions/Zed.png"><img src="public/images/champions/Zed.png" alt="">
        </li>
        <li value="Zeri" data-image="public/images/champions/Zeri.png"><img src="public/images/champions/Zeri.png"
                alt=""></li>
        <li value="Ziggs" data-image="public/images/champions/Ziggs.png"><img src="public/images/champions/Ziggs.png"
                alt=""></li>
        <li value="Zilean" data-image="public/images/champions/Zilean.png"><img src="public/images/champions/Zilean.png"
                alt=""></li>
        <li value="Zoe" data-image="public/images/champions/Zoe.png"><img src="public/images/champions/Zoe.png" alt="">
        </li>
        <li value="Zyra" data-image="public/images/champions/Zyra.png"><img src="public/images/champions/Zyra.png"
                alt=""></li>
