<div class="form_container"> 
    <form class="form_signup" method="post" action="/createvalorantuser">

    <?php if (isset($_GET['error'])) : ?>
    <p class="errorsForm"><?= $_GET['error'] ?></p>
    <?php endif; ?>

    <h2>Pick your 3 mains</h2>
        <label for="main1">Main 1</label>
        <button type="button" id="btnMain1">Select main 1</button>
        <div id="popupMain1">
                <input type="text" id="search1" autocomplete="no-autofill" placeholder="Search..." class="notranslate">
                <ul class="main1Ul">
                    <?php include 'views/signup/options_champion_valorant.phtml' ?>
                <ul>
        </div>

        <input type="hidden" id="main1" name="main1" value="" class="notranslate">

        <label for="main2">Main 2</label>
        <button type="button" id="btnMain2">Select main 2</button>
        <div id="popupMain2">
                <input type="text" id="search2" autocomplete="no-autofill" placeholder="Search..." class="notranslate">
                <ul class="main2Ul">
                    <?php include 'views/signup/options_champion_valorant.phtml' ?>
                <ul>
        </div>

        <input type="hidden" id="main2" name="main2" value="" class="notranslate">

        <label for="main3">Main 3</label>
        <button type="button" id="btnMain3">Select main 3</button>
        <div id="popupMain3">
                <input type="text" id="search3" autocomplete="no-autofill" placeholder="Search..." class="notranslate">
                <ul class="main3Ul">
                    <?php include 'views/signup/options_champion_valorant.phtml' ?>
                <ul>
        </div>

        <input type="hidden" id="main3" name="main3" value="" class="notranslate">


        <script src="public/js/champions.js"></script>


        <label for="rank_valorant">Your rank</label>
        <select id="rank_valorant" name="rank_valorant">
            <option value="" disabled selected>Select rank...</option>
            <option value="Unranked" data-image="public/images/valorant_ranks/Unranked.png">Unranked</option>
            <option value="Iron" data-image="public/images/valorant_ranks/Iron.png">Iron</option>
            <option value="Bronze" data-image="public/images/valorant_ranks/Bronze.png">Bronze</option>
            <option value="Silver" data-image="public/images/valorant_ranks/Silver.png">Silver</option>
            <option value="Gold" data-image="public/images/valorant_ranks/Gold.png">Gold</option>
            <option value="Platinum" data-image="public/images/valorant_ranks/Platinum.png">Platinum</option>
            <option value="Diamond" data-image="public/images/valorant_ranks/Diamond.png">Diamond</option>
            <option value="Ascendant" data-image="public/images/valorant_ranks/Ascendant.png">Ascendant</option>
            <option value="Immortal" data-image="public/images/valorant_ranks/Immortal.png">Immortal</option>
            <option value="Radiant" data-image="public/images/valorant_ranks/Radiant.png">Radiant</option>
        </select>

        <div id="selected-ranks-valorant"></div>

        <script src="public/js/ranks-valorant.js"></script>

        <label for="role_valorant">Your role</label>
        <select id="role_valorant" name="role_valorant">
            <option value="Controller" data-image="public/images/valorant_roles/Controller.webp">Controller</option>
            <option value="Duelist" data-image="public/images/valorant_roles/Duelist.webp">Duelist</option>
            <option value="Initiator" data-image="public/images/valorant_roles/Initiator.webp">Initiator</option>
            <option value="Sentinel" data-image="public/images/valorant_roles/Sentinel.webp">Sentinel</option>
            <option value="Fill" data-image="public/images/roles/fill.png">Fill</option>
        </select>

        <div id="selected-roles-valorant"></div>

        <script src="public/js/roles-valorant.js"></script>

        <label for="server">Select your server</label>
            <select id="server" name="server">
                <option value="" disabled selected>Select your server...</option>
                <option value="Europe West">Europe West</option>
                <option value="North America">North America</option>
                <option value="Europe Nordic">Europe Nordic & East </option>
                <option value="Brazil">Brazil</option>
                <option value="Latin America North">Latin America North</option>
                <option value="Latin America South">Latin America South</option>
                <option value="Oceania">Oceania</option>
                <option value="Russia">Russia</option>
                <option value="Turkey">Turkey</option>
                <option value="Japan">Japan</option>
                <option value="Korea">Korea</option>
            </select>

        <?php if($this->isConnectWebsite()) : ?>
            <input type="hidden" name="userId" value="<?= $_SESSION['userId'] ?>">  
        <?php endif ; ?>

        <input name="submit" id="send-button" type="submit" value="Send">
    </form>
    <img class="picture_with_form" src="public/images/jett.png" alt="Jett from Valorant">
</div>


<script type="module" src="public/js/signupLol.js"></script>
<script type="module" src="public/js/valorantinfo.js"></script>