<?php
$champions = [
    "Aatrox" => "public/images/champions/Aatrox.png",
    "Ahri" => "public/images/champions/Ahri.png",
    "Akali" => "public/images/champions/Akali.png",
    "Alistar" => "public/images/champions/Alistar.png",
    "Amumu" => "public/images/champions/Amumu.png",
    "Anivia" => "public/images/champions/Anivia.png",
    "Annie" => "public/images/champions/Annie.png",
    "Aphelios" => "public/images/champions/Aphelios.png",
    "Ashe" => "public/images/champions/Ashe.png",
    "Aurelion Sol" => "public/images/champions/AurelionSol.png",
    "Azir" => "public/images/champions/Azir.png",
    "Bard" => "public/images/champions/Bard.png",
    "Belveth" => "public/images/champions/Belveth.png",
    "Blitzcrank" => "public/images/champions/Blitzcrank.png",
    "Brand" => "public/images/champions/Brand.png",
    "Braum" => "public/images/champions/Braum.png",
    "Caitlyn" => "public/images/champions/Caitlyn.png",
    "Camille" => "public/images/champions/Camille.png",
    "Cassiopeia" => "public/images/champions/Cassiopeia.png",
    "ChoGath" => "public/images/champions/Chogath.png",
    "Corki" => "public/images/champions/Corki.png",
    "Darius" => "public/images/champions/Darius.png",
    "Diana" => "public/images/champions/Diana.png",
    "Dr. Mundo" => "public/images/champions/DrMundo.png",
    "Draven" => "public/images/champions/Draven.png",
    "Ekko" => "public/images/champions/Ekko.png",
    "Elise" => "public/images/champions/Elise.png",
    "Evelynn" => "public/images/champions/Evelynn.png",
    "Ezreal" => "public/images/champions/Ezreal.png",
    "Fiddlesticks" => "public/images/champions/Fiddlesticks.png",
    "Fiora" => "public/images/champions/Fiora.png",
    "Fizz" => "public/images/champions/Fizz.png",
    "Galio" => "public/images/champions/Galio.png",
    "Gangplank" => "public/images/champions/Gangplank.png",
    "Garen" => "public/images/champions/Garen.png",
    "Gnar" => "public/images/champions/Gnar.png",
    "Gragas" => "public/images/champions/Gragas.png",
    "Graves" => "public/images/champions/Graves.png",
    "Gwen" => "public/images/champions/Gwen.png",
    "Hecarim" => "public/images/champions/Hecarim.png",
    "Heimerdinger" => "public/images/champions/Heimerdinger.png",
    "Illaoi" => "public/images/champions/Illaoi.png",
    "Irelia" => "public/images/champions/Irelia.png",
    "Ivern" => "public/images/champions/Ivern.png",
    "Janna" => "public/images/champions/Janna.png",
    "Jarvan IV" => "public/images/champions/JarvanIV.png",
    "Jax" => "public/images/champions/Jax.png",
    "Jayce" => "public/images/champions/Jayce.png",
    "Jhin" => "public/images/champions/Jhin.png",
    "Jinx" => "public/images/champions/Jinx.png",
    "KaiSa" => "public/images/champions/Kaisa.png",
    "Kalista" => "public/images/champions/Kalista.png",
    "Karma" => "public/images/champions/Karma.png",
    "Karthus" => "public/images/champions/Karthus.png",
    "Kassadin" => "public/images/champions/Kassadin.png",
    "Katarina" => "public/images/champions/Katarina.png",
    "Kayle" => "public/images/champions/Kayle.png",
    "Kayn" => "public/images/champions/Kayn.png",
    "Kennen" => "public/images/champions/Kennen.png",
    "KhaZix" => "public/images/champions/Khazix.png",
    "Kindred" => "public/images/champions/Kindred.png",
    "Kled" => "public/images/champions/Kled.png",
    "KogMaw" => "public/images/champions/KogMaw.png",
    "Leblanc" => "public/images/champions/Leblanc.png",
    "Lee Sin" => "public/images/champions/LeeSin.png",
    "Leona" => "public/images/champions/Leona.png",
    "Lillia" => "public/images/champions/Lillia.png",
    "Lissandra" => "public/images/champions/Lissandra.png",
    "Lucian" => "public/images/champions/Lucian.png",
    "Lulu" => "public/images/champions/Lulu.png",
    "Lux" => "public/images/champions/Lux.png",
    "Malphite" => "public/images/champions/Malphite.png",
    "Malzahar" => "public/images/champions/Malzahar.png",
    "Maokai" => "public/images/champions/Maokai.png",
    "Master Yi" => "public/images/champions/MasterYi.png",
    "Miss Fortune" => "public/images/champions/MissFortune.png",
    "Mordekaiser" => "public/images/champions/Mordekaiser.png",
    "Morgana" => "public/images/champions/Morgana.png",
    "Nami" => "public/images/champions/Nami.png",
    "Nasus" => "public/images/champions/Nasus.png",
    "Nautilus" => "public/images/champions/Nautilus.png",
    "Neeko" => "public/images/champions/Neeko.png",
    "Nidalee" => "public/images/champions/Nidalee.png",
    "Nocturne" => "public/images/champions/Nocturne.png",
    "Nunu & Willump" => "public/images/champions/NunuWillump.png",
    "Olaf" => "public/images/champions/Olaf.png",
    "Orianna" => "public/images/champions/Orianna.png",
    "Ornn" => "public/images/champions/Ornn.png",
    "Pantheon" => "public/images/champions/Pantheon.png",
    "Poppy" => "public/images/champions/Poppy.png",
    "Pyke" => "public/images/champions/Pyke.png",
    "Qiyana" => "public/images/champions/Qiyana.png",
    "Quinn" => "public/images/champions/Quinn.png",
    "Rakan" => "public/images/champions/Rakan.png",
    "Rammus" => "public/images/champions/Rammus.png",
    "RekSai" => "public/images/champions/RekSai.png",
    "Renekton" => "public/images/champions/Renekton.png",
    "Rengar" => "public/images/champions/Rengar.png",
    "Riven" => "public/images/champions/Riven.png",
    "Rumble" => "public/images/champions/Rumble.png",
    "Ryze" => "public/images/champions/Ryze.png",
    "Samira" => "public/images/champions/Samira.png",
    "Sejuani" => "public/images/champions/Sejuani.png",
    "Senna" => "public/images/champions/Senna.png",
    "Seraphine" => "public/images/champions/Seraphine.png",
    "Sett" => "public/images/champions/Sett.png",
    "Shaco" => "public/images/champions/Shaco.png",
    "Shen" => "public/images/champions/Shen.png",
    "Shyvana" => "public/images/champions/Shyvana.png",
    "Singed" => "public/images/champions/Singed.png",
    "Sion" => "public/images/champions/Sion.png",
    "Sivir" => "public/images/champions/Sivir.png",
    "Skarner" => "public/images/champions/Skarner.png",
    "Sona" => "public/images/champions/Sona.png",
    "Soraka" => "public/images/champions/Soraka.png",
    "Swain" => "public/images/champions/Swain.png",
    "Sylas" => "public/images/champions/Sylas.png",
    "Syndra" => "public/images/champions/Syndra.png",
    "Tahm Kench" => "public/images/champions/TahmKench.png",
    "Taliyah" => "public/images/champions/Taliyah.png",
    "Talon" => "public/images/champions/Talon.png",
    "Taric" => "public/images/champions/Taric.png",
    "Teemo" => "public/images/champions/Teemo.png",
    "Thresh" => "public/images/champions/Thresh.png",
    "Tristana" => "public/images/champions/Tristana.png",
    "Trundle" => "public/images/champions/Trundle.png",
    "Tryndamere" => "public/images/champions/Tryndamere.png",
    "Twisted Fate" => "public/images/champions/TwistedFate.png",
    "Twitch" => "public/images/champions/Twitch.png",
    "Udyr" => "public/images/champions/Udyr.png",
    "Urgot" => "public/images/champions/Urgot.png",
    "Varus" => "public/images/champions/Varus.png",
    "Vayne" => "public/images/champions/Vayne.png",
    "Veigar" => "public/images/champions/Veigar.png",
    "VelKoz" => "public/images/champions/Velkoz.png",
    "Vi" => "public/images/champions/Vi.png",
    "Viego" => "public/images/champions/Viego.png",
    "Viktor" => "public/images/champions/Viktor.png",
    "Vladimir" => "public/images/champions/Vladimir.png",
    "Volibear" => "public/images/champions/Volibear.png",
    "Warwick" => "public/images/champions/Warwick.png",
    "Wukong" => "public/images/champions/Wukong.png",
    "Xayah" => "public/images/champions/Xayah.png",
    "Xerath" => "public/images/champions/Xerath.png",
    "Xin Zhao" => "public/images/champions/XinZhao.png",
    "Yasuo" => "public/images/champions/Yasuo.png",
    "Yone" => "public/images/champions/Yone.png",
    "Yorick" => "public/images/champions/Yorick.png",
    "Yuumi" => "public/images/champions/Yuumi.png",
    "Zac" => "public/images/champions/Zac.png",
    "Zed" => "public/images/champions/Zed.png",
    "Ziggs" => "public/images/champions/Ziggs.png",
    "Zilean" => "public/images/champions/Zilean.png",
    "Zoe" => "public/images/champions/Zoe.png",
    "Zyra" => "public/images/champions/Zyra.png"
];

$ranks = [
    "Iron" => "public/images/ranks/Iron.png",
    "Bronze" => "public/images/ranks/Bronze.png",
    "Silver" => "public/images/ranks/Silver.png",
    "Gold" => "public/images/ranks/Gold.png",
    "Platinum" => "public/images/ranks/Platinum.png",
    "Diamond" => "public/images/ranks/Diamond.png",
    "Master" => "public/images/ranks/Master.png",
    "Grand Master" => "public/images/ranks/Grandmaster.png",
    "Challenger" => "public/images/ranks/Challenger.png"
  ];

  $roles = [
    "Support" => "public/images/roles/support.png",
    "AD Carry" => "public/images/roles/adcarry.png",
    "Mid laner" => "public/images/roles/midlaner.png",
    "Jungler" => "public/images/roles/jungle.png",
    "Top laner" => "public/images/roles/toplaner.png",
    "Fill" => "public/images/roles/fill.png"
  ];
?>


<div class="user_page_main_league">
    <?php if ($user['user_game'] !== 'valorant'): ?>
        <div class="league_of_legends_user">
            <?php if (isset($champions[$lolUser['lol_main1']])): ?>
                <div class="league_of_legends_user_column">
            <img id="league_champions_user" src="<?= $champions[$lolUser['lol_main1']] ?>" alt="<?= $lolUser['lol_main1'] ?>">
            <p id="no_display_phone"><?= $lolUser['lol_main1']; ?></p>
            </div>
            <?php endif; ?>
            <?php if (isset($champions[$lolUser['lol_main2']])): ?>
                <div class="league_of_legends_user_column">
                <img id="league_champions_user" src="<?= $champions[$lolUser['lol_main2']] ?>" alt="<?= $lolUser['lol_main2'] ?>">
                <p id="no_display_phone"><?= $lolUser['lol_main2']; ?></p>
                </div>
            <?php endif; ?>
            <?php if (isset($champions[$lolUser['lol_main3']])): ?>
                <div class="league_of_legends_user_column">                        
                <img id="league_champions_user" src="<?= $champions[$lolUser['lol_main3']] ?>" alt="<?= $lolUser['lol_main3'] ?>">
                <p id="no_display_phone"><?= $lolUser['lol_main3']; ?></p>
                </div>
            <?php endif; ?>
            <?php if (isset($ranks[$lolUser['lol_rank']])): ?>
                <div class="league_of_legends_user_column">
            <img id="league_champions_user" src="<?= $ranks[$lolUser['lol_rank']] ?>" alt="<?= $lolUser['lol_rank'] ?>">
            <p id="no_display_phone"><?= $lolUser['lol_rank'] ?></p>
            </div>  
            <?php endif; ?>
            <?php if (isset($roles[$lolUser['lol_role']])): ?>
                <div class="league_of_legends_user_column">
            <img id="league_champions_user" src="<?= $roles[$lolUser['lol_role']] ?>" alt="<?= $lolUser['lol_role'] ?>">
            <p id="no_display_phone"><?= $lolUser['lol_role'] ?></p>
            </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
