<section class="lol-quiz">
    <h1>What Kind of League of Legends Player Are You?</h1>
    <div id="progressBarContainer" class="w-full bg-gray-300 h-4 rounded-full overflow-hidden mb-4">
      <div id="progressBar" class="bg-blue-500 h-full" style="width: 0%;"></div>
    </div>
  <div id="quiz-container"></div>

  <!-- Navigation -->
  <div id="navigation" class="navigation">
    <button id="backBtn">Back</button>
    <button id="nextBtn">Next</button>
    <button id="confirmBtn" class="hidden">Confirm</button>
  </div>

  <!-- Result -->
  <div id="result" class="hidden">
    <button id="resetBtn" class="mt-4 px-4 py-2 bg-red-500 text-white rounded hidden">
      Restart Quiz
    </button>
    <h2 id="result-title"></h2>
    <p id="result-description"></p>
    <div id="canvas-container" class="w-full" style="position: relative;">
      <canvas id="result-chart"></canvas>
    </div>
  </div>

  <div id="createURSGAccount" class="hidden">
    <h2 class="text-lg font-bold mb-4">Create a URSG Account</h2>
    <p class="mb-4">To save your results, please create an account with us.</p>
    <a href="/signup" class="bg-blue-500 text-white px-4 py-2 rounded">Register</a>
  </div>
</section>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="public/js/swiping/personality_test.js?<?= time(); ?>"></script>