<section class="lol-quiz">
  <h1>QUIZ</h1>
    <hr class="separators-hr" />
    <h2>What Kind of <span class="gold-text">League of Legends</span> Player Are You</h2>
  <div id="quiz-container"></div>

    <div id="progressBarContainer" class="hidden">
      <span id="progressPercent">0%</span>
      <div id="progressBar" class="bg-blue-500 h-full" style="width: 0%;"></div>
    </div>

    <hr class="separators-hr" />
  <!-- Navigation -->
  <div id="navigation" class="navigation" style="display: none;">
    <button id="backBtn">Back</button>
    <button id="nextBtn">Next</button>
    <button id="confirmBtn" class="hidden">Confirm</button>
  </div>

  <!-- Result -->
  <div id="result" class="hidden">
    <button id="resetBtn" class="mt-4 px-4 py-2 bg-red-500 text-white rounded hidden">
      Restart Quiz
    </button>
    <h2 id="result-title"></h2>
    <div class="result-row">
      <img id="result-image" src="" alt="Result Image" />
      <p id="result-description"></p>
    </div>
    <div id="canvas-container" class="w-full" style="position: relative;">
      <svg id="result-chart"></svg>
    </div>
    <div id="showMatchingUser">
      <h3>User made for you</h3>
        <p id="matchingPersonality">
          <img class="avatar" id="matchingUserAvatar" src="" alt="">
          <a class="username_matchingPersonality" id="matchingUserName" target="_blank" href=""><strong class="strong_text"></strong></a>
      </p>
    </div>
  </div>

  <div id="createURSGAccount" class="hidden">
    <h2 >Create a URSG Account</h2>
    <p id="create-account-desc">To save your results, please create an account with us.</p>
    <a href="/?triggerSignUp=true">Go to Sign Up</a>
  </div>
</section>
  <script src="https://d3js.org/d3.v6.min.js"></script>
  <script src="public/js/swiping/personality_test.js?<?= time(); ?>"></script>