<section id="user-container"> <!--Flex column -->
    <div id="user-top-container"> <!--Flex column -->
        <?php if  (($user['user_isVip']) || ($user['user_isPartner']) || ($user['user_isCertified'])) : ?>
            <span id="badge-container">
                <?php if ($user['user_isVip']) : ?>
                        <span class="vip-badge" title="Premium badge"><img src="/public/images/premium-badge.png" alt="Premium"></span>
                <?php endif; ?>
                <?php if ($user['user_isPartner']) : ?>
                        <span class="vip-badge" title="Partner badge"><img src="/public/images/partner-badge.png" alt="Premium"></span>
                <?php endif; ?>  
                <?php if ($user['user_isCertified']) : ?>
                        <span class="vip-badge" title="Certified badge"><img src="/public/images/certified-badge.png" alt="Premium"></span>
                <?php endif; ?>  
            </span>
        <?php endif; ?>
        <span id="edit-profile-container">
        <a href="/updateProfilePage" class="btn_user_updates_profile"><i class="fa-solid fa-info"></i>UPDATE PROFILE</a> 
        <?php if ($user['user_game'] !== 'Valorant'): ?> 
            <a href="/updateLeaguePage" class="btn_user_updates_profile"><i class="fa-solid fa-gamepad"></i>UPDATE LEAGUE OF LEGENDS</a>
        <?php else : ?>
            <a href="/updateValorantPage" class="btn_user_updates_profile"><i class="fa-solid fa-gamepad"></i>UPDATE VALORANT</a> 
        <?php endif; ?>
        <a href="/updateLookingForPage" class="btn_user_updates_profile"><i class="fa-solid fa-heart"></i>UPDATE INTERESTS</a>
        </span>
        <div id="user-top-content"> <!--Flex column -->
            <div id="profile-picture-container">
                <button class="btn_updateProfilePicture" id="opendialog_update_picture"><i class="fa-solid fa-image"></i></button>
                <?php if (isset($user['user_picture']) && $user['user_picture'] !== null): ?>
                    <img id="image_users" src="public/upload/<?= $user['user_picture'] ?>" alt="Picture of <?= $user['user_username'] ?>" />  
                <?php else :?>
                    <img id="image_users" src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                <?php endif; ?>
                
                <?php if ($ownedItems && count($ownedItems) > 0) : ?>
                    <?php
                    $profilePictures = array_filter($ownedItems, function($item) {
                        return $item['items_category'] === 'profile Picture';
                    });
                    ?>
                    <?php if (count($profilePictures) > 0) : ?>
                        <?php foreach ($profilePictures as $item) : ?>
                            <?php if ($item['userItems_isUsed'] === 1) : ?>
                                <img class="frame_around_picture" src="public/images/store/<?= str_replace('.jpg', '.png', $item['items_picture']) ?>" alt="<?= $item['items_name'] ?>">
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>

            <div id="user-info"> <!--Flex row -->
                <h2><?= ucfirst($user['user_username']) ?></h2>
                <p>,<?= ucfirst($user['user_age']) ?></p>
            </div>
    </div>
    <div id="user-bottom-container"> <!--Flex column -->
        <nav id="user-bottom-nav"> <!--Flex row with JS -->
            <button type="button" id="aboutme-btn" class="focused">About me</button>
            <button type="button" id="pictures-btn">Pictures</button>
            <button type="button" id="socials-btn">Socials</button>
            <button type="button" id="requests-btn">Requests</button>
        </nav>
        <hr id="hr-user-bottom-nav">
        <div id="loading-indicator" style="display: none; text-align: center;">
            <img src="public/images/loading.svg" alt="Loading..." />
        </div>
        <div id="aboutme-container"> <!--Flex row with -->
            <button class="btn_updateProfile">Bind Riot account</button>
            <div class="aboutme-match">
                <!-- Left Player -->
                <div class="profile">
                    <img src="http://ddragon.leagueoflegends.com/cdn/15.6.1/img/profileicon/<?= $lolUser['lol_sProfileIcon']?>.png" alt="You">
                    <?php if ($lolUser['lol_verified'] === 1): ?>
                        <p class="profile-level"><?= $lolUser['lol_sLevel']?></p>
                    <?php endif; ?>
                </div>
                <div class="icons you">
                <img src="public/images/ranks/<?= str_replace(' ', '', $lolUser['lol_rank']) ?>.png" alt="Rank">
                <img src="public/images/roles/<?= str_replace(' ', '', $lolUser['lol_role']) ?>.png" alt="Role">
                </div>

                <!-- Dotted Line -->
                <div class="match-divider"></div>

                <!-- Right Player -->
                <div class="icons mate">
                <img src="public/images/ranks/<?= str_replace(' ', '', $lfUser['lf_lolrank']) ?>.png" alt="Rank">
                <img src="public/images/roles/<?= str_replace(' ', '', $lfUser['lf_lolrole']) ?>.png" alt="Role">
                </div>
                <div class="profile profile-mate">
                    ?
                </div>
            </div>

            <!-- Champions Row -->
            <div class="aboutme-match champions-row">
                <div class="champions you">
                    <?php if ($lolUser['lol_verified'] === 1): ?>
                        <div class="lol-account">
                        <p id="lolUserText"><strong><?= $lolUser['lol_account']?></strong><i class="fa-solid fa-copy"></i></p>
                        </div>
                    <?php endif; ?>
                    <img src="public/images/champions/<?= $lolUser['lol_main1']?>.png" alt="Champion">
                    <img src="public/images/champions/<?= $lolUser['lol_main2']?>.png" alt="Champion">
                    <img src="public/images/champions/<?= $lolUser['lol_main3']?>.png" alt="Champion">
                </div>
                <div class="champions mate">
                    <img src="public/images/champions/<?= $lfUser['lf_lolmain1']?>.png" alt="Champion">
                    <img src="public/images/champions/<?= $lfUser['lf_lolmain2']?>.png" alt="Champion">
                    <img src="public/images/champions/<?= $lfUser['lf_lolmain3']?>.png" alt="Champion">
                </div>
            </div>
            <div class="other-data-profile">
                <div class="about_you_users"><br>
                    <div class=""top-part-about style="flex-direction: column;">
                    <div class="gender about-users-containers">
                        <p class="about-users-title"><strong>Gender</strong></p>
                        <?php if ($user['user_gender'] == "Female") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-selected" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                            </p>
                        <?php elseif ($user['user_gender'] == "Male") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-selected" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                            </p>
                        <?php elseif ($user['user_gender'] == "Non Binary" || $user['user_gender'] == "Non binary") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-selected" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                            </p>
                            <?php elseif ($user['user_gender'] == "Trans Man" || $user['user_gender'] == "Trans Man") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/trans-man.jpg" alt="Trans Man" class="about-users-selected" />
                            </p>
                            <?php elseif ($user['user_gender'] == "Trans Woman" || $user['user_gender'] == "Trans Woman") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/trans-woman.jpg" alt="Trans Woman" class="about-users-selected" />
                            </p>
                        <?php endif; ?>
                    </div>
                        <div class="queues about-users-containers">
                        <p class="about-users-title"><strong>Queues</strong></p>
                            <?php if($user['user_kindOfGamer'] == "Chill") :?>
                                <p class="about-users-box"><span class="about-users-selected">Chill      </span><span class="about-users-low-opacity">Competition</span></p>
                            <?php elseif($user['user_kindOfGamer'] == "Competition") :?>
                                <p class="about-users-box"><span class="about-users-low-opacity">Chill</span>      <span class="about-users-selected">Competiton</span></p>
                            <?php else  :?>
                                <p class="about-users-box"><span class="about-users-selected">Chill      </span><span class="about-users-selected">Competiton</span></p>
                            <?php endif; ?>
                        </div>
                        <div class="servers about-users-containers">
                        <p class="about-users-title"><strong>Server</strong></p>
                        <?php if ($user['user_game'] == 'League of Legends'): ?> 
                            <p class="about-users-box about-users-selected"><?= strtoupper($lolUser['lol_server']) ?></p>
                        <?php else : ?>
                            <p class="about-users-box about-users-selected"><?= strtoupper($valorantUser['valorant_server']) ?></p>                   
                        <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="about_you_users"><br>
                    <div class="top-part-about" style="flex-direction: column;">
                        <div class="gender about-users-containers">
                            <p class="about-users-title"><strong>Gender</strong></p>
                            <?php if ($lfUser['lf_gender'] == "Female") : ?>
                                <p class="about-users-box">
                        <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                        <img src="public/images/femenine.png" alt="femenine" class="about-users-selected" />
                        <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                        <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                    </p>
                        <?php elseif ($lfUser['lf_gender'] == "Male") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-selected" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                            </p>
                        <?php elseif ($lfUser['lf_gender'] == "Non Binary" || $lfUser['lf_gender'] == "Non binary") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-selected" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                            </p>
                        <?php elseif ($lfUser['lf_gender'] == "Trans") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-selected" />
                            </p>
                        <?php elseif ($lfUser['lf_gender'] == "Male and Female") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-selected" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-selected" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                            </p>
                        <?php elseif ($lfUser['lf_gender'] == "All") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-selected" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-selected" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-selected" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-selected" />
                            </p>
                        <?php else : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                            </p>
                        <?php endif; ?>
                        </div>
                        <div class="queues about-users-containers">
                        <p class="about-users-title"><strong>Queues</strong></p>
                            <?php if($lfUser['lf_kindofgamer'] == "Chill") :?>
                                <p class="about-users-box"><span class="about-users-selected">Chill      </span><span class="about-users-low-opacity">Competition</span></p>
                            <?php elseif($lfUser['lf_kindofgamer'] == "Competition") :?>
                                <p class="about-users-box"><span class="about-users-low-opacity">Chill</span>      <span class="about-users-selected">Competiton</span></p>
                            <?php else  :?>
                                <p class="about-users-box"><span class="about-users-selected">Chill      </span><span class="about-users-selected">Competiton</span></p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div> <!-- YOU OR MATE  -->
            </div>
            <div class="about-users-bio" style="width: 95%;">
                <p class="about-users-box-bio">
                    <?= htmlspecialchars(htmlspecialchars_decode($user['user_shortBio'], ENT_QUOTES), ENT_QUOTES, 'UTF-8') ?>
                </p>
            </div>
        </div>
        <div id="pictures-container"> <!--Flex row with -->
            <?php if ($user['user_bonusPicture'] !== NULL && $user['user_bonusPicture'] !== "[]"): ?>
                <div class="bonusPicture_ctn">
                        <button class="btn_updateProfile" id="opendialog_bonuspicture">Add a picture</button>
                    <div class="bonusPicture_row">
                        <?php 
                        if (!empty($user['user_bonusPicture'])): 
                            $pictures = json_decode($user['user_bonusPicture'], true);
                            if (!empty($pictures)): 
                                foreach ($pictures as $picture): 
                                    $picturePath = "public/upload/" . htmlspecialchars($picture);
                        ?>
                                    <div class="bonusPicture_wrapper">
                                        <img src="<?= $picturePath ?>" class="user_bonuspicture" alt="User Picture">
                                        <button class="bonusPicture_delete" data-filename="<?= htmlspecialchars($picture) ?>">&times;</button>
                                    </div>
                        <?php 
                                endforeach; 
                            endif;
                        endif; 
                        ?>
                    </div>
                </div>
            <?php endif; ?>
            <dialog id="favDialogBonusPicture">
                <form action="/addBonusPicture&username=<?= urlencode($user['user_username']) ?>" method="post" enctype="multipart/form-data" class="form-picture">
                    <p class="title_generalbox">Add a profile picture or update it</p>
                    <p>Accepted format : JPG, JPEG and PNG</p>
                    <div class="file-input-container">
                        <input type="file" id="file" name="file" class="file-input">
                        <label for="file" class="file-label">Choose a file</label>
                        <span id="file-name" class="file-name">No file selected</span>
                    </div>
                    <input type="submit" name="submit" value="Upload" id="send-button">
                </form>
                <button id="closeButton_user_picture_bonus">X</button>
            </dialog>
        </div>
        <div id="socials-container">
            <?php 
            // Define social platforms and their URLs
            $socials = [
                'twitter' => 'https://twitter.com/',
                'discord' => 'https://discord.com/users/',
                'instagram' => 'https://www.instagram.com/',
                'twitch' => 'https://www.twitch.tv/',
                'bluesky' => 'https://bsky.app/profile/'
            ];

            foreach ($socials as $key => $url) :
                $username = $user["user_$key"] ?? '';
                $imgSrc = "public/images/{$key}_user.png";
            ?>
                <div class="social-container-column" data-platform="<?= $key ?>">
                    <?php if (!empty($username)): ?>  
                        <div class="social-container-right">
                            <a target="_blank" href="<?= $url . htmlspecialchars($username) ?>">
                                <img class="social_picture" src="<?= $imgSrc ?>" alt="<?= $key ?>_user">
                                <p><?= htmlspecialchars($username) ?></p>
                            </a>
                            <i class="fa-solid fa-up-right-from-square"></i>
                        </div>
                        <div class="social-container-left">
                            <i class="fa-solid fa-pen-to-square"></i>
                            <i class="fa-solid fa-link-slash"></i>
                        </div>
                    <?php else: ?>
                        <div class="social-container-right">
                            <img class="social_picture" src="<?= $imgSrc ?>" alt="<?= $key ?>_user">
                            <p class="shadow">UNKNOWN</p>
                        </div>
                        <div class="social-container-left">
                            <i class="fa-solid fa-link"></i> <!-- Link icon -->
                        </div>
                    <?php endif; ?>
                </div>  
            <?php endforeach; ?>
            <div class="coming-soon">
                <p>COMING SOON</p>
            </div>
        </div>
        <div id="requests-container"> <!--Flex row with -->
            <?php if(!empty($friendRequest)) :?>
            <div id="friendRequestData" style="display: none;">
                <?= json_encode($friendRequest); ?>
            </div>
                <span id="friendrequest-backend"></span>
                    <?php foreach ($friendRequest as $request) :?>
                        <div class="friend_request_ctn" data-fr-id="<?= $request['fr_id'] ?>">
                            <p>
                                <a target="_blank" href="/anotherUser&username=<?= urlencode($request['user_username']) ?>">
                                <?php if (isset($request['user_picture']) && $request['user_picture'] !== null): ?>
                                    <img id="image_users_small" src="public/upload/<?= $request['user_picture'] ?>" alt="Picture of <?= $request['user_username'] ?>" />  
                                <?php else :?>
                                    <img id="image_users_small" src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                                <?php endif; ?>
                                    <span class="clickable"><?= $request['user_username'] ?>, <?= $request['user_age'] ?>, <?= $request['user_gender'] ?></span>
                                </a>   
                            </p><br>
                            <div class="friend_request_ctn_btn">
                            <a href="#" class="accept_friend_button" 
                                data-fr-id="<?= $request['fr_id'] ?>" 
                                data-user-id="<?= $user['user_id'] ?>" 
                                data-status="accepted">
                                <button>Accept</button>
                            </a>
                            <a href="#" class="refuse_friend_button" 
                                data-fr-id="<?= $request['fr_id'] ?>"
                                data-user-id="<?= $user['user_id'] ?>"  
                                data-status="rejected">
                                <button>Refuse</button>
                            </a>
                            </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <dialog id="favDialogPicture">
        <form action="/updatePicture&username=<?= urlencode($user['user_username']) ?>" method="post" enctype="multipart/form-data" class="form-picture">
            <p class="title_generalbox">Add a profile picture or update it</p>
            <p>Accepted format : JPG, JPEG and PNG</p>
            <div class="file-input-container">
                <label for="fileProfile" class="file-label">Choose a file</label>
                <input type="file" id="fileProfile" name="fileProfile" class="file-input">
                <span id="file-nameProfile" class="file-name">No file selected</span>
            </div>
            <input type="submit" name="submit" value="Upload" id="send-button">
        </form>
        <p class="title_generalbox">Add a profile picture frame</p>
        <?php if ($ownedItems && count($ownedItems) > 0) : ?>
            <?php
            $profilePictures = array_filter($ownedItems, function($item) {
                return $item['items_category'] === 'profile Picture';
            });
            ?>
            <span id="placeholder-message"></span>

            <?php if (count($profilePictures) > 0) : ?>
                <div class="picture_frame_ctn">
                    <?php foreach ($profilePictures as $item) : ?>
                        <div class="picture_frame">
                            <img src="public/images/store/<?= $item['items_picture'] ?>" alt="<?= $item['items_name'] ?>">
                            <p><?= $item['items_name'] ?></p>
                            <?php if ($item['userItems_isUsed'] === 1) : ?>
                                <button class="btn_picture_frame_remove" data-item-id="<?= $item['userItems_id'] ?>">Remove</button>
                            <?php else : ?>
                                <button class="btn_picture_frame" data-item-id="<?= $item['userItems_id'] ?>">Use</button>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php else : ?>
                <p>You don't have any profile picture frame yet</p>
                <a href="/store" class="btn_picture_frame">Go to the store</a>
            <?php endif; ?>
        <?php else : ?>
            <p>You don't have any items yet</p>
            <a href="/store" class="btn_picture_frame">Go to the store</a>
        <?php endif; ?>
        <button id="closeButton_user_picture">X</button>
    </dialog>
</section>

<script src="public/js/swiping/profile_nav.js"></script>
<script src="public/js/swiping/dialog_picture_social.js?nocache=<%= Date.now() %>"></script>
<script src="public/js/swiping/friendrequest.js?nocache=<%= Date.now() %>"></script>
<script src="public/js/swiping/bonusPictures.js?nocache=<%= Date.now() %>"></script>
<script src="public/js/swiping/socialLinks.js?nocache=<%= Date.now() %>"></script>
<script src="public/js/swiping/gender-icon.js"></script>
<script src="public/js/swiping/copy_username.js"></script>