<section id="user-container"> <!--Flex column -->
    <div id="user-top-container"> <!--Flex column -->
        <?php if  (($user['user_isVip']) || ($user['user_isPartner']) || ($user['user_isCertified'])) : ?>
            <span id="badge-container">
                <?php if ($user['user_isVip']) : ?>
                        <span class="vip-badge" title="Premium badge"><img src="/public/images/premium-badge.png" alt="Premium"></span>
                <?php endif; ?>
                <?php if ($user['user_isPartner']) : ?>
                        <span class="vip-badge" title="Partner badge"><img src="/public/images/partner-badge.png" alt="Premium"></span>
                <?php endif; ?>  
                <?php if ($user['user_isCertified']) : ?>
                        <span class="vip-badge" title="Certified badge"><img src="/public/images/certified-badge.png" alt="Premium"></span>
                <?php endif; ?>  
            </span>
        <?php endif; ?>
        <span id="edit-profile-container"><i class="fa-solid fa-pen-to-square"></i>Edit Profile</span>
        <div id="user-top-content"> <!--Flex column -->
            <div id="profile-picture-container">
                <?php if (isset($user['user_picture']) && $user['user_picture'] !== null): ?>
                    <img id="image_users" src="public/upload/<?= $user['user_picture'] ?>" alt="Picture of <?= $user['user_username'] ?>" />  
                <?php else :?>
                    <img id="image_users" src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                <?php endif; ?>
                
                <?php if ($ownedItems && count($ownedItems) > 0) : ?>
                    <?php
                    $profilePictures = array_filter($ownedItems, function($item) {
                        return $item['items_category'] === 'profile Picture';
                    });
                    ?>
                    <?php if (count($profilePictures) > 0) : ?>
                        <?php foreach ($profilePictures as $item) : ?>
                            <?php if ($item['userItems_isUsed'] === 1) : ?>
                                <img class="frame_around_picture" src="public/images/store/<?= str_replace('.jpg', '.png', $item['items_picture']) ?>" alt="<?= $item['items_name'] ?>">
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>

            <div id="user-info"> <!--Flex row -->
                <h2><?= ucfirst($user['user_username']) ?></h2>
                <p>,<?= ucfirst($user['user_age']) ?></p>
            </div>
    </div>
    <div id="user-bottom-container"> <!--Flex column -->
        <nav id="user-bottom-nav"> <!--Flex row with JS -->
            <button type="button" id="aboutme-btn" class="focused">About me</button>
            <button type="button" id="pictures-btn">Pictures</button>
            <button type="button" id="socials-btn">Socials</button>
            <button type="button" id="requests-btn">Requests</button>
        </nav>
        <hr id="hr-user-bottom-nav">
        <div id="loading-indicator" style="display: none; text-align: center;">
            <img src="public/images/loading.svg" alt="Loading..." />
        </div>
        <div id="aboutme-container"> <!--Flex row with -->
            <h3>About me</h3>
        </div>
        <div id="pictures-container"> <!--Flex row with -->
            <?php if ($user['user_bonusPicture'] !== NULL && $user['user_bonusPicture'] !== "[]"): ?>
                <div class="bonusPicture_ctn">
                        <button class="btn_newPicture" id="opendialog_bonuspicture">Add a picture</button>
                    <div class="bonusPicture_row">
                        <?php 
                        if (!empty($user['user_bonusPicture'])): 
                            $pictures = json_decode($user['user_bonusPicture'], true);
                            if (!empty($pictures)): 
                                foreach ($pictures as $picture): 
                                    $picturePath = "public/upload/" . htmlspecialchars($picture);
                        ?>
                                    <div class="bonusPicture_wrapper">
                                        <img src="<?= $picturePath ?>" class="user_bonuspicture" alt="User Picture">
                                        <button class="bonusPicture_delete" data-filename="<?= htmlspecialchars($picture) ?>">&times;</button>
                                    </div>
                        <?php 
                                endforeach; 
                            endif;
                        endif; 
                        ?>
                    </div>
                </div>
            <?php endif; ?>
            <dialog id="favDialogBonusPicture">
                <form action="/addBonusPicture&username=<?= urlencode($user['user_username']) ?>" method="post" enctype="multipart/form-data" class="form-picture">
                    <p class="title_generalbox">Add a profile picture or update it</p>
                    <p>Accepted format : JPG, JPEG and PNG</p>
                    <div class="file-input-container">
                        <input type="file" id="file" name="file" class="file-input">
                        <label for="file" class="file-label">Choose a file</label>
                        <span id="file-name" class="file-name">No file selected</span>
                    </div>
                    <input type="submit" name="submit" value="Upload" id="send-button">
                </form>
                <button id="closeButton_user_picture_bonus">X</button>
            </dialog>
        </div>
        <div id="socials-container"> <!--Flex row with -->
        <div class="user_page_update_row">
                <?php if (!empty($user['user_twitter'])): ?>  
                    <a target="_blank" href="https://twitter.com/<?= $user['user_twitter'] ?>">
                    <img class="social_picture" src="public/images/twitter_user.png" alt="twitter_user"></a>
                <?php endif; ?>   
                
                <?php if (!empty($user['user_discord'])): ?>  
                    <div class="user_page_discord">
                        <img class="social_picture" id="discord_picture" src="public/images/discord_user.png" alt="discord_user">
                        <p id="hidden_p">Discord : <?= $user['user_discord'] ?></p>
                    </div>
                <?php endif; ?>   
                
                <?php if (!empty($user['user_instagram'])): ?>
                    <a target="_blank" href="https://www.instagram.com/<?= $user['user_instagram'] ?>">
                    <img class="social_picture" src="public/images/instagram_user.png" alt="instagram_user"></a>  
                <?php endif; ?>   

                <?php if (!empty($user['user_twitch'])): ?>
                    <a target="_blank" href="https://www.twitch.tv/<?= $user['user_twitch'] ?>">
                    <img class="social_picture" src="public/images/twitch_user.png" alt="twitch_user"></a>  
                <?php endif; ?>    
                
                <?php if (!empty($user['user_bluesky'])): ?>  
                    <a target="_blank" href="https://bsky.app/profile/<?= $user['user_bluesky'] ?>">
                    <img class="social_picture" src="public/images/bluesky_user.png" alt="bluesky_user"></a>
                <?php endif; ?> 
            </div>
        </div>
        <div id="requests-container"> <!--Flex row with -->
            <?php if(!empty($friendRequest)) :?>
            <div id="friendRequestData" style="display: none;">
                <?= json_encode($friendRequest); ?>
            </div>
                <span id="friendrequest-backend"></span>
                    <?php foreach ($friendRequest as $request) :?>
                        <div class="friend_request_ctn" data-fr-id="<?= $request['fr_id'] ?>">
                            <p>
                                <a target="_blank" href="/anotherUser&username=<?= urlencode($request['user_username']) ?>">
                                <?php if (isset($request['user_picture']) && $request['user_picture'] !== null): ?>
                                    <img id="image_users_small" src="public/upload/<?= $request['user_picture'] ?>" alt="Picture of <?= $request['user_username'] ?>" />  
                                <?php else :?>
                                    <img id="image_users_small" src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                                <?php endif; ?>
                                    <span class="clickable"><?= $request['user_username'] ?>, <?= $request['user_age'] ?>, <?= $request['user_gender'] ?></span>
                                </a>   
                            </p><br>
                            <div class="friend_request_ctn_btn">
                            <a href="#" class="accept_friend_button" 
                                data-fr-id="<?= $request['fr_id'] ?>" 
                                data-user-id="<?= $user['user_id'] ?>" 
                                data-status="accepted">
                                <button>Accept</button>
                            </a>
                            <a href="#" class="refuse_friend_button" 
                                data-fr-id="<?= $request['fr_id'] ?>"
                                data-user-id="<?= $user['user_id'] ?>"  
                                data-status="rejected">
                                <button>Refuse</button>
                            </a>
                            </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</section>

<script src="public/js/swiping/profile_nav.js"></script>
<script src="public/js/swiping/friendrequest.js?nocache=<%= Date.now() %>"></script>
<script src="public/js/swiping/bonusPictures.js?nocache=<%= Date.now() %>"></script>