<section id="setting-page">
<div class="page-header">
    <a href="#"><?= $this->_('settings') ?></a>
</div>

    <div id="userInfo" data-user-id="<?= $user['user_id']; ?>" data-chat-filter="<?= $user['user_hasChatFilter']; ?>" data-random-chat-permission="<?= $user['user_randomChatPermission']; ?>"></div>

    <div class="setting-option">
        <span>
            <i class="fas fa-comment-slash"></i> 
            <span><?= $this->_('chat_filter') ?></span>
        </span>
        <div class="toggle-container-filter">
            <div id="toggleChatFilter" class="filter-button"></div>
        </div>
    </div>

    <div class="setting-option">
        <span>
            <i class="fas fa-moon"></i> 
            <span><?= $this->_('dark_mode') ?></span>
        </span>
        <div class="toggle-container">
            <div title="Dark mode" id="toggle-button" class="toggle-button"></div>
        </div>
    </div>

    <div class="setting-option">
        <span>
            <i class="fa-solid fa-headphones"></i> 
            <span><?= $this->_('sound_notifications') ?></span>
        </span>
        <div class="toggle-container-sound" id="toggle-container-sound">
            <div id="toggle-button-sound"></div>
        </div>
    </div>

    <div class="setting-option">
        <span>
            <i class="fa-solid fa-people-group"></i> 
            <span><?= $this->_('random_chat_permission') ?></span>
        </span>
        <div class="toggle-container-random-chat">
            <div id="toggleRandomChatPermission" class="filter-button"></div>
        </div>
    </div>

    <form method="POST" action="/changeLanguage" class="language-switcher">
        <div class="setting-option">
            <span>
                <label for="lang"><i class="fa-solid fa-earth-americas"></i></label>
                <span><?= $this->_('language') ?></span>
            </span>
            <select name="lang" id="lang" onchange="this.form.submit()">
                <option value="en" <?= ($_SESSION['lang'] ?? 'en') === 'en' ? 'selected' : '' ?>>EN</option>
                <option value="fr" <?= ($_SESSION['lang'] ?? 'en') === 'fr' ? 'selected' : '' ?>>FR</option>
                <option value="de" <?= ($_SESSION['lang'] ?? 'en') === 'de' ? 'selected' : '' ?>>DE</option>
                <option value="es" <?= ($_SESSION['lang'] ?? 'en') === 'es' ? 'selected' : '' ?>>ES</option>
            </select>
        </div>
    </form>

    <a href="/deleteAccount">
        <div class="setting-option">
            <span>
                <i class="fa-solid fa-trash"></i> 
                <span><?= $this->_('delete_account') ?></span>
            </span>
        </div>
    </a>
</section>

<script src="public/js/swiping/switchChatFilter.js?<?= time(); ?>"></script>
<script src="public/js/swiping/switchSoundNotification.js?<?= time(); ?>"></script>
<script src="public/js/swiping/settings.js?<?= time(); ?>"></script>