<section id="setting-page">
<div class="page-header">
    <a href="#">Settings</a>
</div>

    <div id="userInfo" data-user-id="<?= $user['user_id']; ?>" data-chat-filter="<?= $user['user_hasChatFilter']; ?>"></div>

    <div class="setting-option">
        <span>
            <i class="fas fa-comment-slash"></i> 
            <span>Chat Filter</span>
        </span>
        <div class="toggle-container-filter">
            <div id="toggleChatFilter" class="filter-button"></div>
        </div>
    </div>

    <div class="setting-option">
        <span>
            <i class="fas fa-moon"></i> 
            <span>Dark Mode</span>
        </span>
        <div class="toggle-container">
            <div title="Dark mode" id="toggle-button" class="toggle-button"></div>
        </div>
    </div>

    <div class="setting-option">
        <span>
            <i class="fa-solid fa-headphones"></i> 
            <span>Sound Notification</span>
        </span>
        <div class="toggle-container-sound" id="toggle-container-sound">
            <div id="toggle-button-sound"></div>
        </div>
    </div>

    <a href="/deleteAccount">
        <div class="setting-option">
            <span>
                <i class="fa-solid fa-trash"></i> 
                <span>Delete account</span>
            </span>
        </div>
    </a>
</section>

<script src="public/js/swiping/switchChatFilter.js?<?= time(); ?>"></script>
<script src="public/js/swiping/switchSoundNotification.js?<?= time(); ?>"></script>