<div class="page-header">
    <a href="/store" class="active">Store</a>
    <a href="/leaderboard">Leaderboard</a>
    <p id="earnpoints">?</p>
</div>

<!-- Modal -->
<div class="modal-overlay" id="modalOverlay">
    <div class="modal store" id="modalEarnPoints">
        <h2>Earn Points</h2>
        <p>You can earn points by being online on the app. More options will be added later!</p>
        <button id="closeModalEarnPoints">Close</button>
    </div>
</div>

<div class="filter-section">
    <label for="category-filter">Filter by category:</label>
    <select id="category-filter">
        <option value="all">All Categories</option>
        <?php
        $categories = array_unique(array_column($items, 'items_category'));
        foreach($categories as $category) : ?>
            <option value="<?= $category ?>"><?= ucfirst($category) ?></option>
        <?php endforeach; ?>
    </select>
</div>


<div class="item-grid">
    <?php foreach($items as $item) : ?>
        <div class="item-card" data-category="<?= $item['items_category'] ?>">
        <img src="<?= $item['items_picture'] ? '/public/images/store/' . $item['items_picture'] : '/public/images/store/defaultpicture.jpg'; ?>" alt="<?= $item['items_name'] ?>">
        <div class="item-info">
            <h3><?= $item['items_name'] ?></h3>
            <?php if ($user['user_isVip']) : ?>
                <p class="price_display"><span class="old-price"><?= $item['items_price']?></span><?= $item['items_price'] * 0.8 ?><img src="public/images/soulhard.png" alt="soulhard"></p>
            <?php else : ?>
                <p class="price_display"><?= $item['items_price'] ?><img src="public/images/soulhard.png" alt="soulhard"></p>
            <?php endif; ?>  
            <p><?= preg_replace('/[\.:](\s|$)/', '$0<br>', $item['items_desc']) ?></p>
            <div class="buy-button-container">
                <?php   if (($item['items_category'] === 'role' && $user['user_isVip'] === 1) || 
        in_array($item['items_id'], array_column($ownedItems, 'items_id'))) : ?>
                    <button class="buy-button-owned" disabled>Owned</button>
                <?php else : ?>
                    <button class="buy-button" data-item-id="<?= $item['items_id'] ?>">Buy</button>
                <?php endif; ?>
            </div>
        </div>
        <span class="placeholder-message" id='placeholder-message-<?= $item['items_id'] ?>'></span>
    </div>
    <?php endforeach; ?>
</div>

<script src="public/js/swiping/store.js?<?= time(); ?>"></script>
<script src="public/js/swiping/modalStore.js?<?= time(); ?>"></script>