<div id="overlay"></div>
<section id="user-container"> <!--Flex column -->
    <div class="swiping-buttons" style="margin: 20px;"> <!-- Buttons (report, filter) Display row -->
        <button class="swiping-buttons-report" id="report-button" type="button">
            <img src="public/images/report.svg" alt="Report an user">
        </button>
    </div>
    <div id="user-top-container"> <!--Flex column -->
        <input id="receiverId" type="hidden" name="receiver_id" value="<?= $anotherUser['user_id'] ?>">
            <!-- Modal Structure -->
            <div id="report-modal" class="modal report-modal-hidden">
                <div class="modal-content">
                    <span id="close-modal" class="close">&times;</span>
                    <h2>Report User</h2>
                    <p class="report-modal-p">Please let us know why you are reporting this user</p>
                    <div class="user-info">
                    <?php if (isset($anotherUser['user_picture']) && $anotherUser['user_picture'] !== null): ?>
                            <img id="image_users" src="public/upload/<?= $anotherUser['user_picture'] ?>" alt="Picture of <?= $anotherUser['user_username'] ?>" />  
                        <?php else :?>
                            <img id="image_users" src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                        <?php endif; ?>
                        <span id="report-username"><?= $anotherUser['user_username'] ?></span>
                    </div>
                    <div class="report-textarea">
                        <div class="label-container">
                            <label for="report-description">Description <span class="low-opacity">(optional)</span></label>
                        </div>
                        <textarea id="report-description" placeholder="Provide details here..."></textarea>
                    </div>
                    <button id="submit-report">Report</button>
                </div>
            </div>
        <div id="user-top-content"> <!--Flex column -->
            <div id="profile-picture-container">
                <?php if (isset($anotherUser['user_picture']) && $anotherUser['user_picture'] !== null): ?>
                    <img id="image_users" src="public/upload/<?= $anotherUser['user_picture'] ?>" alt="Picture of <?= $anotherUser['user_username'] ?>" />  
                <?php else :?>
                    <img id="image_users" src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                <?php endif; ?>
                
                <?php if ($ownedItems && count($ownedItems) > 0) : ?>
                    <?php
                    $profilePictures = array_filter($ownedItems, function($item) {
                        return $item['items_category'] === 'profile Picture';
                    });
                    ?>
                    <?php if (count($profilePictures) > 0) : ?>
                        <?php foreach ($profilePictures as $item) : ?>
                            <?php if ($item['userItems_isUsed'] === 1) : ?>
                                <img class="frame_around_picture" src="public/images/store/<?= str_replace('.jpg', '.png', $item['items_picture']) ?>" alt="<?= $item['items_name'] ?>">
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>

            <div id="user-info"> <!--Flex row -->
                <h2><?= ucfirst($anotherUser['user_username']) ?></h2>
                <p>,<?= ucfirst($anotherUser['user_age']) ?></p>
            </div>
            <?php if  (($anotherUser['user_isVip']) || ($anotherUser['user_isPartner']) || ($anotherUser['user_isCertified'])) : ?>
            <span id="badge-container">
                <?php if ($anotherUser['user_isVip']) : ?>
                        <span class="vip-badge" title="Premium badge"><img src="/public/images/premium-badge.png" alt="Premium"></span>
                <?php endif; ?>
                <?php if ($anotherUser['user_isPartner']) : ?>
                        <span class="vip-badge" title="Partner badge"><img src="/public/images/partner-badge.png" alt="Premium"></span>
                <?php endif; ?>  
                <?php if ($anotherUser['user_isCertified']) : ?>
                        <span class="vip-badge" title="Certified badge"><img src="/public/images/certified-badge.png" alt="Premium"></span>
                <?php endif; ?>  
            </span>
        <?php endif; ?>
    </div>
    <div id="user-bottom-container"> <!--Flex column -->
        <nav id="user-bottom-nav"> <!--Flex row with JS -->
            <button type="button" id="aboutme-btn" class="focused">About me</button>
            <button type="button" id="pictures-btn">Pictures</button>
            <button type="button" id="socials-btn">Socials</button>
        </nav>
        <hr id="hr-user-bottom-nav">
        <div id="loading-indicator" style="display: none; text-align: center;">
            <img src="public/images/loading.svg" alt="Loading..." />
        </div>
        <div id="aboutme-container"> <!--Flex row with -->
            <div class="aboutme-match">
            <?php if ($anotherUser['user_game'] == 'League of Legends'): ?> 
                <div class="profile">
                    <?php if ($lolUser['lol_verified'] === 1): ?>
                        <img id="profilepicture_lol" data-icon-id="<?= $lolUser['lol_sProfileIcon']?>" src="https://ddragon.leagueoflegends.com/cdn/15.6.1/img/profileicon/<?= $lolUser['lol_sProfileIcon']?>.png" alt="You">
                    <?php else : ?>
                        <img src="https://ddragon.leagueoflegends.com/cdn/15.6.1/img/profileicon/7.png" alt="You">
                    <?php endif; ?>
                    <?php if ($lolUser['lol_verified'] === 1): ?>
                        <p class="profile-level"><?= $lolUser['lol_sLevel']?></p>
                    <?php endif; ?>
                </div>

                <div class="icons you">
                    <?php if ($lolUser['lol_verified'] === 1): ?>
                        <div class="rank-image" style="position: relative;">
                            <img src="public/images/ranks/<?= ucfirst(strtolower(explode(" ", $lolUser['lol_sRank'])[0])) ?>.png" alt="Rank">
                            <i class="fa-solid fa-check" style="position: absolute; top: -10px; right: -5px; font-size: 14px; color: green;"></i>
                        </div>
                    <?php else : ?>
                        <div class="rank-image" style="position: relative;">
                            <img src="public/images/ranks/<?= str_replace(' ', '', $lolUser['lol_rank']) ?>.png" alt="Rank">
                            <i class="fa-solid fa-xmark" style="position: absolute; top: -10px; right: -5px; font-size: 14px; color: red;"></i>
                        </div>
                    <?php endif; ?>
                    
                    <!-- Role image (not affected by verification) -->
                    <img src="public/images/roles/<?= str_replace(' ', '', $lolUser['lol_role']) ?>.png" alt="Role">
                </div>


                <!-- Dotted Line -->
                <div class="match-divider"></div>

                <!-- Right Player -->
                <div class="icons mate">
                <img src="public/images/ranks/<?= str_replace(' ', '', $lfUser['lf_lolrank']) ?>.png" alt="Rank">
                <img src="public/images/roles/<?= str_replace(' ', '', $lfUser['lf_lolrole']) ?>.png" alt="Role">
                </div>
                <div class="profile profile-mate">
                    ?
                </div>
            </div>

            <!-- Champions Row -->
            <?php if($lolUser['lol_noChamp'] === 0 || $lfUser['lf_lolNoChamp'] === 0) : ?>
                <div class="aboutme-match champions-row">
                    <div class="champions you" style="<?= $lolUser['lol_noChamp'] === 0 ? '' : 'visibility: hidden;' ?>">
                        <?php if ($lolUser['lol_verified'] === 1): ?>
                            <div class="lol-account">
                                <p id="lolUserText"><strong><?= $lolUser['lol_account']?></strong><i class="fa-solid fa-copy"></i></p>
                            </div>
                        <?php endif; ?>
                        <img src="public/images/champions/<?= $lolUser['lol_main1']?>.png" alt="Champion">
                        <img src="public/images/champions/<?= $lolUser['lol_main2']?>.png" alt="Champion">
                        <img src="public/images/champions/<?= $lolUser['lol_main3']?>.png" alt="Champion">
                    </div>

                    <div class="champions mate" style="<?= $lfUser['lf_lolNoChamp'] === 0 ? '' : 'visibility: hidden;' ?>">
                        <img src="public/images/champions/<?= $lfUser['lf_lolmain1']?>.png" alt="Champion">
                        <img src="public/images/champions/<?= $lfUser['lf_lolmain2']?>.png" alt="Champion">
                        <img src="public/images/champions/<?= $lfUser['lf_lolmain3']?>.png" alt="Champion">
                    </div>
                </div>
            <?php else : ?>
                <div class="aboutme-match champions-row">
                    <?php if ($lolUser['lol_verified'] === 1): ?>
                        <div class="lol-account" style="margin : 10px 0 0 0;">
                            <p id="lolUserText"><strong><?= $lolUser['lol_account']?></strong><i class="fa-solid fa-copy"></i></p>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <?php else : ?> <!-- Valorant -->
                <div class="profile">
                    <?php if (isset($anotherUser['user_picture']) && $anotherUser['user_picture'] !== null): ?>
                        <img src="public/upload/<?= $anotherUser['user_picture'] ?>" alt="Picture of <?= $anotherUser['user_username'] ?>" />  
                    <?php else :?>
                        <img src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                    <?php endif; ?>
                    </div>
                    <div class="icons you">
                    <img src="public/images/valorant_ranks/<?= str_replace(' ', '', $valorantUser['valorant_rank']) ?>.png" alt="Rank">
                    <img src="public/images/valorant_roles/<?= str_replace(' ', '', $valorantUser['valorant_role']) ?>.webp" alt="Role">
                    </div>

                    <!-- Dotted Line -->
                    <div class="match-divider"></div>

                    <!-- Right Player -->
                    <div class="icons mate">
                    <img src="public/images/valorant_ranks/<?= str_replace(' ', '', $lfUser['lf_valrank']) ?>.png" alt="Rank">
                    <img src="public/images/valorant_roles/<?= str_replace(' ', '', $lfUser['lf_valrole']) ?>.webp" alt="Role">
                    </div>
                    <div class="profile profile-mate">
                        ?
                    </div>
                </div>

                <!-- Champions Row -->
                <?php if($valorantUser['valorant_noChamp'] === 0 || $lfUser['lf_valNoChamp'] === 0) : ?>
                    <div class="aboutme-match champions-row">
                        <div class="champions you" style="<?= $valorantUser['valorant_noChamp'] === 0 ? '' : 'visibility: hidden;' ?>">
                            <img src="public/images/valorant_champions/<?= $valorantUser['valorant_main1']?>_icon.webp" alt="Champion">
                            <img src="public/images/valorant_champions/<?= $valorantUser['valorant_main2']?>_icon.webp" alt="Champion">
                            <img src="public/images/valorant_champions/<?= $valorantUser['valorant_main3']?>_icon.webp" alt="Champion">
                        </div>

                        <div class="champions mate" style="<?= $lfUser['lf_valNoChamp'] === 0 ? '' : 'visibility: hidden;' ?>">
                            <img src="public/images/valorant_champions/<?= $lfUser['lf_valmain1']?>_icon.webp" alt="Champion">
                            <img src="public/images/valorant_champions/<?= $lfUser['lf_valmain2']?>_icon.webp" alt="Champion">
                            <img src="public/images/valorant_champions/<?= $lfUser['lf_valmain3']?>_icon.webp" alt="Champion">
                        </div>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
                <!-- Left Player -->
            <div class="other-data-profile">
                <div class="about_you_users"><br>
                    <div class=""top-part-about style="flex-direction: column;">
                    <div class="gender about-users-containers">
                        <p class="about-users-title"><strong>Gender</strong></p>
                        <?php if ($anotherUser['user_gender'] == "Female") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-selected" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                            </p>
                        <?php elseif ($anotherUser['user_gender'] == "Male") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-selected" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                            </p>
                        <?php elseif ($anotherUser['user_gender'] == "Non Binary" || $anotherUser['user_gender'] == "Non binary") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-selected" />
                                <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                            </p>
                        <?php elseif ($anotherUser['user_gender'] == "Trans Man" || $anotherUser['user_gender'] == "Trans Man") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/trans-man.jpg" alt="Trans Man" class="about-users-selected" />
                            </p>
                        <?php elseif ($anotherUser['user_gender'] == "Trans Woman" || $anotherUser['user_gender'] == "Trans Woman") : ?>
                            <p class="about-users-box">
                                <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                <img src="public/images/trans-woman.jpg" alt="Trans Woman" class="about-users-selected" />
                            </p>
                        <?php elseif ($anotherUser['user_gender'] == "Trans") : ?>
                                <p class="about-users-box">
                                    <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                    <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                    <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                    <img src="public/images/transexual.png" alt="Trans" class="about-users-selected" />
                                </p>
                        <?php endif; ?>
                    </div>
                        <div class="queues about-users-containers">
                        <p class="about-users-title"><strong>Queues</strong></p>
                            <?php if($anotherUser['user_kindOfGamer'] == "Chill") :?>
                                <p class="about-users-box"><span class="about-users-selected">Chill      </span><span class="about-users-low-opacity">Competition</span></p>
                            <?php elseif($anotherUser['user_kindOfGamer'] == "Competition") :?>
                                <p class="about-users-box"><span class="about-users-low-opacity">Chill</span>      <span class="about-users-selected">Competiton</span></p>
                            <?php else  :?>
                                <p class="about-users-box"><span class="about-users-selected">Chill      </span><span class="about-users-selected">Competiton</span></p>
                            <?php endif; ?>
                        </div>
                        <div class="servers about-users-containers">
                        <p class="about-users-title"><strong>Server</strong></p>
                        <?php if ($anotherUser['user_game'] == 'League of Legends'): ?> 
                            <p class="about-users-box about-users-selected"><?= strtoupper($lolUser['lol_server']) ?></p>
                        <?php else : ?>
                            <p class="about-users-box about-users-selected"><?= strtoupper($valorantUser['valorant_server']) ?></p>                   
                        <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="about_you_users"><br>
                    <div class="top-part-about" style="flex-direction: column;">
                        <div class="gender about-users-containers">
                            <p class="about-users-title"><strong>Gender</strong></p>
                                <?php if ($lfUser['lf_gender'] == "Female") : ?>
                                    <p class="about-users-box">
                                        <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                        <img src="public/images/femenine.png" alt="femenine" class="about-users-selected" />
                                        <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                        <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                                    </p>
                                <?php elseif ($lfUser['lf_gender'] == "Male") : ?>
                                    <p class="about-users-box">
                                        <img src="public/images/male.png" alt="Male" class="about-users-selected" />
                                        <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                        <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                        <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                                    </p>
                                <?php elseif ($lfUser['lf_gender'] == "Non Binary" || $lfUser['lf_gender'] == "Non binary") : ?>
                                    <p class="about-users-box">
                                        <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                        <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                        <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-selected" />
                                        <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                                    </p>
                                <?php elseif ($lfUser['lf_gender'] == "Trans") : ?>
                                    <p class="about-users-box">
                                        <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                        <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                        <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                        <img src="public/images/transexual.png" alt="Trans" class="about-users-selected" />
                                    </p>
                                <?php elseif ($lfUser['lf_gender'] == "Male and Female") : ?>
                                    <p class="about-users-box">
                                        <img src="public/images/male.png" alt="Male" class="about-users-selected" />
                                        <img src="public/images/femenine.png" alt="femenine" class="about-users-selected" />
                                        <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                        <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                                    </p>
                                <?php elseif ($lfUser['lf_gender'] == "All") : ?>
                                    <p class="about-users-box">
                                        <img src="public/images/male.png" alt="Male" class="about-users-selected" />
                                        <img src="public/images/femenine.png" alt="femenine" class="about-users-selected" />
                                        <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-selected" />
                                        <img src="public/images/transexual.png" alt="Trans" class="about-users-selected" />
                                    </p>
                                <?php else : ?>
                                    <p class="about-users-box">
                                        <img src="public/images/male.png" alt="Male" class="about-users-low-opacity" />
                                        <img src="public/images/femenine.png" alt="femenine" class="about-users-low-opacity" />
                                        <img src="public/images/non-binary.png" alt="Non-Binary" class="about-users-low-opacity" />
                                        <img src="public/images/transexual.png" alt="Trans" class="about-users-low-opacity" />
                                    </p>
                                <?php endif; ?>
                            </div>
                        <div class="queues about-users-containers">
                        <p class="about-users-title"><strong>Queues</strong></p>
                            <?php if($lfUser['lf_kindofgamer'] == "Chill") :?>
                                <p class="about-users-box"><span class="about-users-selected">Chill      </span><span class="about-users-low-opacity">Competition</span></p>
                            <?php elseif($lfUser['lf_kindofgamer'] == "Competition") :?>
                                <p class="about-users-box"><span class="about-users-low-opacity">Chill</span>      <span class="about-users-selected">Competiton</span></p>
                            <?php else  :?>
                                <p class="about-users-box"><span class="about-users-selected">Chill      </span><span class="about-users-selected">Competiton</span></p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div> <!-- YOU OR MATE  -->
            </div>
            <div class="about-users-bio" style="width: 95%;">
                <p class="about-users-box-bio">
                    <?= htmlspecialchars(htmlspecialchars_decode($anotherUser['user_shortBio'], ENT_QUOTES), ENT_QUOTES, 'UTF-8') ?>
                </p>
            </div>
        </div>
        <div id="pictures-container"> <!--Flex row with -->
            <?php if ($anotherUser['user_bonusPicture'] !== NULL && $anotherUser['user_bonusPicture'] !== "[]"): ?>
                <div class="bonusPicture_ctn">
                    <div class="bonusPicture_row">
                        <?php 
                        if (!empty($anotherUser['user_bonusPicture'])): 
                            $pictures = json_decode($anotherUser['user_bonusPicture'], true);
                            if (!empty($pictures)): 
                                foreach ($pictures as $picture): 
                                    $picturePath = "public/upload/" . htmlspecialchars($picture);
                        ?>
                                    <div class="bonusPicture_wrapper">
                                        <img src="<?= $picturePath ?>" class="user_bonuspicture" alt="User Picture">
                                    </div>
                        <?php 
                                endforeach; 
                            endif;
                        endif; 
                        ?>
                    </div>
                </div>
            <?php else : ?>
                <p style="text-align: center; width: 100%;">This user has no pictures</p>
            <?php endif; ?>
        </div>
        <div id="socials-container">
            <?php 
            // Define social platforms and their URLs
            $socials = [
                'twitter' => 'https://twitter.com/',
                'discord' => 'https://discord.com/users/',
                'instagram' => 'https://www.instagram.com/',
                'twitch' => 'https://www.twitch.tv/',
                'bluesky' => 'https://bsky.app/profile/'
            ];

            foreach ($socials as $key => $url) :
                $anotherUsername = $anotherUser["user_$key"] ?? '';
                $imgSrc = "public/images/{$key}_user.png";
            ?>
                <div class="social-container-column" data-platform="<?= $key ?>">
                    <?php if (!empty($anotherUsername)): ?>  
                        <div class="social-container-right">
                            <a target="_blank" href="<?= $url . htmlspecialchars($anotherUsername) ?>">
                                <img class="social_picture" src="<?= $imgSrc ?>" alt="<?= $key ?>_user">
                                <p><?= htmlspecialchars($anotherUsername) ?></p>
                            </a>
                        </div>
                    <?php else: ?>
                        <div class="social-container-right">
                            <img class="social_picture" src="<?= $imgSrc ?>" alt="<?= $key ?>_user">
                            <p class="shadow">UNKNOWN</p>
                        </div>
                    <?php endif; ?>
                </div>  
            <?php endforeach; ?>
        </div>
</section>

<script src="public/js/swiping/profile_nav.js?<?= time(); ?>"></script>
<script src="public/js/swiping/gender-icon.js?<?= time(); ?>"></script>
<script src="public/js/swiping/copy_username.js?<?= time(); ?>"></script>
<script src="public/js/swiping/profile_updateRiotPic.js?<?= time(); ?>"></script>
<script src="public/js/swiping/report.js?<?= time(); ?>"></script>