<div class="friendlist-page">
    <div class="chat-interface"><br>
        <div class="chat_box"><br>
            <h1 id="title_generalbox">Friends</h1><br>       
            <?php if(empty($getFriendlist)): ?>
                <section class="no_friend"><br><br>     
                    <img src="public/images/sadbee.webp" alt="jhinshrug">
                    <h2 id="title_generalbox">You have no friends yet, wait until they accept your request or swipe more!</h2>
                </section>  
            <?php else :?>
                <?php foreach($getFriendlist as $friend) : ?>
                    <?php
                        if ($user['user_id'] == $friend['sender_id']) {
                            $friendId = $friend['receiver_id'];
                            $friendUsername = $friend['receiver_username'];
                            $friendPicture = $friend['receiver_picture'];
                        } else {
                            $friendId = $friend['sender_id'];
                            $friendUsername = $friend['sender_username'];
                            $friendPicture = $friend['sender_picture'];
                        }
                    ?>
                    <div class="friend" data-sender-id="<?= $friendId ?>">
                        <div class="friend-avatar">
                            <a href="index.php?action=anotherUser&username=<?= $friendUsername ?>">
                                <?php if ($friendPicture !== NULL) : ?>
                                    <img src="public/upload/<?= $friendPicture ?>" alt="Avatar <?= $friendUsername ?>"></a>
                                <?php else : ?>
                                    <img src="public/images/defaultprofilepicture.jpg" alt="Avatar <?= $friendUsername ?>"></a>
                                <?php endif; ?>
                        </div>
                        <div class="friend-details">
                            <span class="friendlist-name">
                                <a href="index.php?action=anotherUser&username=<?= $friendUsername ?>">
                                    <p class="person_button"><?= $friendUsername ?></a>
                                    <button class="block_user" onclick="openConfirmationPopup('confirmationPopup_<?= $friendId ?>', '<?= $friendUsername ?>')">Block</button>
                                </p>
                            </span>
                        </div>
                    </div>                
                        <dialog id="confirmationPopup_<?= $friendId ?>" class="confirmationPopup">
                            <div class="popup-content">
                                <button id="closeButton" onclick="closeConfirmationPopup('confirmationPopup_<?= $friendId ?>')">X</button>
                                <h2 id="title_generalbox">Are you sure you want to block <span><?= $friendUsername ?></span>?</h2>
                                <form action="index.php?action=blockPerson" method="post">
                                    <input type="hidden" name="senderId" value="<?= $user['user_id'] ?>">
                                    <input type="hidden" name="receiverId" value="<?= $friendId ?>">
                                    <div class="button_container">
                                        <button class="confirmation-button" name="submit" type="submit">Yes</button>
                                        <button class="confirmation-button" onclick="closeConfirmationPopup('confirmationPopup_<?= $friendId ?>')">No</button>
                                    </div>
                                </form>
                            </div>
                        </dialog>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>

    <div class="chat-interface"><br>
        <div class="chat_box"><br>  
            <h2 id="title_generalbox">Blocked Users</h2><br>
            <?php if(empty($getBlocklist)): ?>
                <section class="no_friend"><br><br>     
                <img src="public/images/jhinshrug.png" alt="jhinshrug" class="blocked-users-image">
                    <h2>You have no blocked users.</h2>
                </section>              
            <?php else : ?>
                <?php foreach($getBlocklist as $blocked) :?>
                    <div class="friend-avatar">
                        <a href="index.php?action=anotherUser&username=<?= $blocked['user_username'] ?>">
                        <?php if($blocked['user_picture'] !== NULL) :?>
                            <img src="public/upload/<?= $blocked['user_picture'] ?>" alt="Avatar <?= $blocked['user_username'] ?>"></a>
                        <?php else :?>
                            <img src="public/images/defaultprofilepicture.jpg" alt="Avatar <?= $blocked['user_username'] ?>"></a>
                        <?php endif; ?>
                    </div>                
                    
                    <div class="friend-details">
                        <span class="chat-name">
                            <a href="index.php?action=anotherUser&username=<?= $blocked['user_username'] ?>"> 
                                <p class="person_button"><?=  $blocked['user_username'] ?></a>   
                                <button class="unblock_user" onclick="openConfirmationPopup2('confirmationPopup2_<?= $blocked['block_id'] ?>', '<?= $blocked['user_username'] ?>')">Unblock</button>
                            </p>                    
                        </span>
                    </div>

                    <dialog id="confirmationPopup2_<?= $blocked['block_id'] ?>" class="confirmationPopup2">
                        <div class="popup-content">
                            <button id="closeButton" onclick="closeConfirmationPopup2('confirmationPopup2_<?= $blocked['block_id'] ?>')">X</button>
                            <h2 id="title_generalbox">Are you sure you want to unblock <span><?= $blocked['user_username'] ?></span>?</h2>
                            <form action="index.php?action=unblockPerson" method="post">
                                <input type="hidden" name="blockId" value="<?= $blocked['block_id'] ?>">
                                <div class="button_container">
                                    <button class="confirmation-button" name="submit" type="submit">Yes</button><br>
                                    <button class="confirmation-button" onclick="closeConfirmationPopup2('confirmationPopup2_<?= $blocked['block_id'] ?>')">No</button>
                                </div>
                            </form>
                        </div>
                    </dialog>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>                              
    </div>
</div>

<script src="public/js/swiping/friendlist.js"></script>
