<section class="user_page">
    <div class="user_page_update">
        <div class="user_page_main_content_row">
            <div class="main_box">
                <div class="user_page_picture">
                    <?php if (isset($user['user_picture']) && $user['user_picture'] !== null): ?>
                        <img id="image_users" src="public/upload/<?= $user['user_picture'] ?>" alt="Picture of <?= $user['user_username'] ?>" />  
                    <?php else :?>
                        <img id="image_users" src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                    <?php endif; ?>
                    <div class="user_page_update_name">
                        <span id="user_page_username"><?= ucfirst($user['user_username']) ?></span>, <span id="age_user"><?= ucfirst($user['user_age']) ?></span>     
                        <div class="user_page_update_row_buttons">
                            <a href="index.php?action=updateProfilePage"><button class="btn_user_updates" id="opendialog_update_profile"><i class="fa-solid fa-info"></i>UPDATE PROFILE</button></a> 
                            <a href="index.php?action=updateLeaguePage"><button class="btn_user_updates" id="opendialog_update_profile"><i class="fa-solid fa-gamepad"></i>UPDATE LEAGUE OF LEGENDS</button></a> 
                            <a href="index.php?action=updateLookingForPage"><button class="btn_user_updates" id="opendialog_update_looking"><i class="fa-solid fa-heart"></i>UPDATE INTERESTS</button></a> 
                            <a href="index.php?action=updateLeagueAccount"><button class="btn_user_updates" id="opendialog_update_looking"><i class="fa-solid fa-link"></i>BIND LEAGUE ACCOUNT</button></a> 
                            <?php if(isset($user['user_picture']) && $user['user_picture'] !== null) : ?>
                                <button class="btn_user_updates" id="opendialog_update_picture"><i class="fa-solid fa-image"></i> UPDATE PICTURE</button>
                            <?php else : ?>
                                <button class="btn_user_updates" id="opendialog_update_picture"><i class="fa-solid fa-image"></i> ADD PICTURE</button>
                            <?php endif; ?>     
                            <button class="btn_user_updates" id="opendialog_add_social_links"><i class="fa-brands fa-discord"></i>ADD SOCIAL LINKS</button>
                        </div><br>
                        
                        <div class="user_page_update_row">
                            <?php if (!empty($user['user_twitter'])): ?>  
                                <a target="_blank" href="https://twitter.com/<?= $user['user_twitter'] ?>">
                                <img class="social_picture" src="public/images/twitter_user.png" alt="twitter_user"></a>
                            <?php endif; ?>   
                            
                            <?php if (!empty($user['user_discord'])): ?>  
                                <div class="user_page_discord">
                                    <img class="social_picture" id="discord_picture" src="public/images/discord_user.png" alt="discord_user">
                                    <p id="hidden_p">Discord : <?= $user['user_discord'] ?></p>
                                </div>
                            <?php endif; ?>   
                            
                            <?php if (!empty($user['user_instagram'])): ?>
                                <a target="_blank" href="https://www.instagram.com/<?= $user['user_instagram'] ?>">
                                <img class="social_picture" src="public/images/instagram_user.png" alt="instagram_user"></a>  
                            <?php endif; ?>   

                            <?php if (!empty($user['user_twitch'])): ?>
                                <a target="_blank" href="https://www.twitch.tv/<?= $user['user_twitch'] ?>">
                                <img class="social_picture" src="public/images/twitch_user.png" alt="twitch_user"></a>  
                            <?php endif; ?>                             
                        </div><br>
                    </div>
                </div>
            </div>
        </div>        
    </div>

    <?php if(!empty($friendRequest)) :?>
        <div class="friendrequest_box"><br>
            <h2 id="title_generalbox">Friend requests</h2><br>
            <?php foreach ($friendRequest as $request) :?>
                <div class="friend_request_ctn">
                    <p> From: 
                        <a target="_blank" href="user.php?action=anotherUser&username=<?= urlencode($request['user_username']) ?>">
                        <?php if (isset($user['user_picture']) && $user['user_picture'] !== null): ?>
                            <img id="image_users_small" src="public/upload/<?= $request['user_picture'] ?>" alt="Picture of <?= $request['user_username'] ?>" />  
                        <?php else :?>
                            <img id="image_users_smal" src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                        <?php endif; ?>
                            <?= strtoupper($request['user_username']) ?></a>
                        , the <?= date('d/m/y', strtotime($request['fr_date'])) ?>
                    </p><br>
                    <div class="friend_request_ctn_btn">
                        <a href='index.php?action=requestAccepted&fr_id=<?= $request['fr_id'] ?>&friend_id=<?= $request['user_id'] ?>'><button id="accept_friend_button">Accept</button></a>
                        <a href='index.php?action=requestRejected&fr_id=<?= $request['fr_id'] ?>'><button id="refuse_friend_button">Refuse</button></a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <div class="user_page_main_content">
        <div class="user_box">
            <br><h2 id="title_generalbox">About you</h2><br>
            <?php if ($user['user_game'] !== 'valorant'): ?> 
                <?php if (!empty($lolUser['lol_sUsername']) && $lolUser['lol_verified'] === 1): ?>
                    <div class="box_league_account">
                        <div class="box_league_account_main_row">
                            <img id="profilepicture_lol" src="public/images/profileicon/<?= $lolUser['lol_sProfileIcon'] ?>.png" alt="icon_league">
                            <div class="box_league_account_main_row_column">
                                <p id="lolUserText"><strong><?= $lolUser['lol_account']?></strong><i class="fa-solid fa-copy"></i></p>
                                <p class="small_text"><?= strtoupper($lolUser['lol_server']) ?></p>
                                <p class="small_text"> <?= strtoupper($lolUser['lol_sRank']) ?></p>
                                <p class="small_text">Level : <?= strtoupper($lolUser['lol_sLevel']) ?></p> 
                            </div>
                        </div>
                    </div><br>
                <?php endif; ?>
                <?php if (!empty($lolUser['lol_account']) && empty($lolUser['lol_sUsername'])): ?>
                    <div class="box_league_account">
                        <div class="box_league_account_main_row">
                            <p><?= strtoupper($lolUser['lol_server']) ?></p> 
                        </div>
                    </div>
                <? endif; ?>
                    <?php include 'views/swiping/lol_perso_champions.phtml' ?><br>
            <?php endif; ?>

            <div class="about_you_users"><br>
                <p><strong>Gender</strong>: <?= ucfirst($user['user_gender']) ?></p><br>
                <p><strong>Kind of gamer</strong>: <?= ucfirst($user['user_kindOfGamer']) ?></p><br>
                <p><strong>Your short bio</strong>: <?= htmlspecialchars_decode($user['user_shortBio'], ENT_QUOTES) ?></p><br>
            </div>
        </div>

        <div class="user_box">
            <br><h2 id="title_generalbox">Looking for</h2><br>
                <?php if ($user['user_game'] !== 'valorant'): ?>
                    <?php include 'views/swiping/lol_lf_champions.phtml' ?><br>
                <?php endif; ?>    
                <div class="about_you_users"><br>
                    <p><strong>Gender</strong>: <?= ($lfUser['lf_gender']) ?></p><br>
                    <p><strong>Kind of gamer</strong>: <?= ($lfUser['lf_kindofgamer']); ?></p><br>
                </div> 
            </div>
        </div>
    </div>
   

    <dialog id="favDialogSocialLinks">
        <br><p id="title_generalbox">Your social links:</p><br>  
        <form action="index.php?action=updateSocial&username=<?= urlencode($user['user_username']) ?>" method="post">
        <label for="discord">Discord:</label><br><br>
            <?php if (!empty($user['user_discord'])): ?>  
                <input type="text" id="discord" name="discord" value="<?= $user['user_discord'] ?>"><br><br>
            <?php else : ?>
                <input type="text" id="discord" name="discord" placeholder="Your Discord username.."><br><br>
            <?php endif; ?>   
            <label for="twitter">Twitter:</label><br><br>
            <?php if (!empty($user['user_twitter'])): ?>  
                <input type="text" id="twitter" name="twitter" value="<?= $user['user_twitter'] ?>"><br><br>
            <?php else : ?>
                <input type="text" id="twitter" name="twitter" placeholder="Your Twitter link.."><br><br>
            <?php endif; ?>  


            <label for="instagram">Instagram:</label><br><br>
            <?php if (!empty($user['user_instagram'])): ?>  
                <input type="text" id="instagram" name="instagram" value="<?= $user['user_instagram'] ?>"><br><br>
            <?php else : ?>
                <input type="text" id="instagram" name="instagram" placeholder="Your Instagram link.."><br><br>
            <?php endif; ?> 


            <label for="instagram">Twitch:</label><br><br>
            <?php if (!empty($user['user_twitch'])): ?>  
                <input type="text" id="twitch" name="twitch" value="<?= $user['user_twitch'] ?>"><br><br>
            <?php else : ?>
                <input type="text" id="twitch" name="twitch" placeholder="Your Twitch link.."><br><br>
            <?php endif; ?> 


            <br><br><input name="submit" type="submit" value="Save" id="send-button">
        </form>
        <button id="closeButton_social_links">X</button>
    </dialog>

    <dialog id="favDialogPicture">
        <form action="index.php?action=updatePicture&username=<?= urlencode($user['user_username']) ?>" method="post" enctype="multipart/form-data" class="form-picture">
            <p id="title_generalbox">Add a profile picture or update it</p>
            <p>Accepted format : JPG, JPEG and PNG</p>
            <div class="file-input-container">
                <input type="file" id="file" name="file" class="file-input">
                <label for="file" class="file-label">Choose a file</label>
                <span id="file-name" class="file-name">No file selected</span>
            </div>
            <input type="submit" name="submit" value="Upload" id="send-button">
        </form>
    <button id="closeButton_user_picture">X</button></dialog>
</section>

<script src="public/js/swiping/dialog_picture_social.js"></script>