<?php if ($user): ?>
        <script>
            window.user = <?= $userData ?>;
            window.usersAll = <?= $usersAllData ?>;
        </script>

    <script type="module" src="public/js/algo.js"></script>
    <?php if ($user['user_game'] === 'League of Legends'): ?>
        <script type="module" src="public/js/swiping/get_userMatching.js"></script>
    <?php else : ?>
        <script type="module" src="public/js/swiping/get_userMatchingValorant.js"></script>
    <?php endif; ?>

    <section class="user_page" id="swipe-area" style="display: none;">
        <div class="user_page_main_content_row swiping_row">
            <div class="main_box-swiping-main">
                <div class="user_page_picture">
                    <img id="image_users" alt="" />
                </div>

                <div class="user_page_update_name">
                    <span id="user_page_username"></span>
                    <span id="age_user"></span>
                </div>
            </div>
        </div>

        <div class="user_page_main_content">
            <div class="user_box">
                <br><h2 id="title_generalbox">About them</h2><br>
                <div class="box_league_account" style="display: none;">
                    <div class="box_league_account_main_row">
                        <img id="profilepicture_lol" alt="icon_league">
                        <div class="box_league_account_main_row_column">
                            <p id="lolsUsername"><strong></strong></p>
                            <p class="small_text" id="lolsRank"></p>
                        </div>
                    </div>
                </div><br>
                <div class="box_league_account" style="display: none;">
                    <div class="box_league_account_main_row">
                        <p id="lolAccount"></p>
                    </div>
                </div>
                <?php if ($user['user_game'] === 'League of Legends'): ?>
                    <?php include 'views/swiping/lol_all_champions.phtml' ?><br>
                <?php else : ?>
                    <?php include 'views/swiping/valorant_all_champions.phtml' ?><br>
                <?php endif; ?>

                <div class="about_you_users"><br>
                    <p id="gender"><span class="font-weight-600">Gender</span>: </p><br>
                    <p id="kindOfGamer"><span class="font-weight-600">Kind of gamer</span>: </p><br>
                    <p id="shortBio"><span class="font-weight-600">Their bio</span>: </p><br>
                </div>
            </div>
        </div>

            <input type="hidden" name="sender_id" value="<?= $_SESSION['userId'] ?>">
            <input id="receiverId" type="hidden" name="receiver_id">
            <div class="row_buttons_swipe">
                <button id="swipe_no" class="button_swiping" name="swipe_no"><i class="fa-solid fa-xmark"></i></button>
                <button id="swipe_yes" class="button_swiping" name="swipe_yes"><i class="fa-solid fa-heart"></i></button>
            </div>
    </section>

    <section class="noUserToSee" style="display: none;">
        <img src="public/images/vayne_emote.png" alt="jhinshrug">
        <h2>You have seen all available profiles.</h2>
    </section>

<?php endif; ?>
