<div class="chat-interface"> <br>
  <div class="chat_box"><br>
    <h1 id="title_generalbox">Chat</h1>    <br>

        <?php if (empty($getFriendlist)) :?>
            <section class="google_needed"><br><br>
                <img src="public/images/sadbee.webp" alt="jhinshrug">
                <h2>You have no friends yet, wait until they accept your request or swipe more!<h2>
            </section>
        <?php else :?>
            <?php foreach($getFriendlist as $friend) : ?>
                <?php
                    if ($user['user_id'] == $friend['sender_id']) {
                        $friendId = $friend['receiver_id'];
                        $friendUsername = $friend['receiver_username'];
                        $friendPicture = $friend['receiver_picture'];
                    } else {
                        $friendId = $friend['sender_id'];
                        $friendUsername = $friend['sender_username'];
                        $friendPicture = $friend['sender_picture'];
                    }
                ?>

            <div class="friend" data-sender-id="<?= $friendId ?>">
                <div class="friend-avatar">
                    <?php if (!empty($friendPicture)): ?>  
                        <a href="index.php?action=persoChat&friend_id=<?=  $friendId ?>&mark_as_read=true">  
                        <img src="public/upload/<?= $friendPicture ?>" alt="Avatar <?= $friendUsername?>">
                        </a>
                    <?php else :?>
                        <a href="index.php?action=persoChat&friend_id=<?=  $friendId ?>&mark_as_read=true">
                        <img src="public/images/defaultprofilepicture.jpg" alt="Avatar <?= $friendUsername ?>">
                        </a>
                    <?php endif; ?>        
                </div>

                <div class="friend-details">
                    <span class="chat-name">
                        <a href="index.php?action=persoChat&friend_id=<?= $friendId ?>&mark_as_read=true"><?= $friendUsername ?></a>
                        <a href="index.php?action=persoChat&friend_id=<?= $friendId ?>&mark_as_read=true">    
                        <?php if (isset($unreadCount) && $unreadCount > 0) :?>
                            <?= "<span style='margin-left: 10px' class='unread-count'><button id='unread_message'> " . $unreadCount . "</button></span>" ?>
                        <?php endif; ?>   
                        </a>         
                    </span>
                </div>
            </div>

            <?php endforeach; ?>
        <?php endif; ?>
    </div>   
</div>