<section class="user_page">
    <div class="user_page_update">
        <div class="user_page_main_content_row">
            <div class="main_box">
                <div class="user_page_picture">
                <div class="profile-picture-container">
                        <?php if (isset($anotherUser['user_picture']) && $anotherUser['user_picture'] !== null): ?>
                            <img id="image_users" src="public/upload/<?= $anotherUser['user_picture'] ?>" alt="Picture of <?= $anotherUser['user_username'] ?>" />  
                        <?php else :?>
                            <img id="image_users" src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                        <?php endif; ?>
                        
                        <?php if ($ownedItems && count($ownedItems) > 0) : ?>
                            <?php
                            $profilePictures = array_filter($ownedItems, function($item) {
                                return $item['items_category'] === 'profile Picture';
                            });
                            ?>
                            <?php if (count($profilePictures) > 0) : ?>
                                <?php foreach ($profilePictures as $item) : ?>
                                    <?php if ($item['userItems_isUsed'] === 1) : ?>
                                        <img class="frame_around_picture" src="public/images/store/<?= str_replace('.jpg', '.png', $item['items_picture']) ?>" alt="<?= $item['items_name'] ?>">
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                    <div class="user_page_update_name">
                    <span id="user_page_username"><?= ucfirst($anotherUser['user_username']) ?></span>, <span id="age_user"><?= ucfirst($anotherUser['user_age']) ?></span>     
                    
                    <div class="user_page_update_row">
                        <?php if (!empty($anotherUser['user_twitter'])): ?>  
                            <a target="_blank" href="https://twitter.com/<?= $anotherUser['user_twitter'] ?>">
                            <img class="social_picture" src="public/images/twitter_user.png" alt="twitter_user"></a>
                        <?php endif; ?>   
                        
                        <?php if (!empty($anotherUser['user_discord'])): ?>  
                            <div class="user_page_discord">
                                <img class="social_picture" id="discord_picture" src="public/images/discord_user.png" alt="discord_user">
                                <p id="hidden_p">Discord : <?= $anotherUser['user_discord'] ?></p>
                            </div>
                        <?php endif; ?>   
                        
                        <?php if (!empty($anotherUser['user_instagram'])): ?>
                            <a target="_blank" href="https://www.instagram.com/<?= $anotherUser['user_instagram'] ?>">
                            <img class="social_picture" src="public/images/instagram_user.png" alt="instagram_user"></a>  
                        <?php endif; ?>   

                        <?php if (!empty($anotherUser['user_twitch'])): ?>
                            <a target="_blank" href="https://www.twitch.tv/<?= $anotherUser['user_twitch'] ?>">
                            <img class="social_picture" src="public/images/twitch_user.png" alt="twitch_user"></a>  
                        <?php endif; ?>                             
                    </div>
                </div>
            </div>
        </div>        
    </div>
    </div>

    <div class="user_page_main_content">
        <div class="user_box">
            <br><h2 class="title_generalbox">About them</h2><br>
            <?php if ($anotherUser['user_game'] !== 'valorant'): ?> 
                <?php if (!empty($lolUser['lol_sUsername']) && $lolUser['lol_verified'] === 1): ?>
                    <div class="box_league_account">
                        <div class="box_league_account_main_row">
                            <img id="profilepicture_lol" src="public/images/profileicon/<?= $lolUser['lol_sProfileIcon'] ?>.png" alt="icon_league" onerror="this.onerror=null; this.src='public/images/profileicon/7.png';">
                            <div class="box_league_account_main_row_column">
                                <p id="lolUserText"><strong><?= $lolUser['lol_account']?></strong><i class="fa-solid fa-copy"></i></p>
                                <p class="small_text"><?= strtoupper($lolUser['lol_server']) ?></p>
                                <p class="small_text"> <?= strtoupper($lolUser['lol_sRank']) ?></p>
                                <p class="small_text">Level : <?= strtoupper($lolUser['lol_sLevel']) ?></p> 
                            </div>
                        </div>
                    </div><br>
                <?php endif; ?>
                <?php if (!empty($lolUser['lol_account']) && empty($lolUser['lol_sUsername'])): ?>
                    <div class="box_league_account">
                        <div class="box_league_account_main_row">
                            <p><?= strtoupper($lolUser['lol_server']) ?></p> 
                        </div>
                    </div>
                <?php endif; ?>
                    <?php include 'views/swiping/lol_perso_champions.phtml' ?><br>
            <?php endif; ?>

            <div class="about_you_users"><br>
                <p><strong>Gender</strong>: <?= ucfirst($anotherUser['user_gender']) ?></p><br>
                <p><strong>Kind of gamer</strong>: <?= ucfirst($anotherUser['user_kindOfGamer']) ?></p><br>
                <p><strong>Your short bio</strong>: <?= htmlspecialchars_decode($anotherUser['user_shortBio'], ENT_QUOTES) ?></p><br>
            </div>
        </div>
    </div>

    <dialog id="favDialogSocialLinks">
        <br><h2 class="title_generalbox">Your social links:</h2><br>  
        <form action="/updateSocial&username=<?= urlencode($anotherUser['user_username']) ?>" method="post">
        <label for="discord">Discord:</label><br><br>
            <input type="text" id="discord" name="discord" placeholder="Your Discord username.."><br><br>
            <label for="twitter">Twitter:</label><br><br>
            <input type="text" id="twitter" name="twitter" placeholder="Your Twitter link.."><br><br>
            <label for="instagram">Instagram:</label><br><br>
            <input type="text" id="instagram" name="instagram" placeholder="Your Instagram link.."><br><br>
            <label for="instagram">Twitch:</label><br><br>
            <input type="text" id="twitch" name="twitch" placeholder="Your Instagram link.."><br><br>
            <br><br><input name="submit" type="submit" value="Save">
        </form>
        <button id="closeButton_social_links">X</button>
    </dialog>

    <dialog id="favDialogPicture">
        <form action="/updatePicture&username=<?= urlencode($anotherUser['user_username']) ?>" method="post" enctype="multipart/form-data">
            <br><p class="title_generalbox">Add a profile picture or update it</p><br>
            <input type="file" name="file"><br>
            <input type="submit" name="submit" value="Upload">
        </form>
    <button id="closeButton_user_picture">X</button></dialog>
</section>

<script src="public/js/swiping/button_otherUser.js"></script>