<section class="user_page">
    <div class="user_page_update">
        <div class="user_page_main_content_row">
            <div class="main_box">
                <div class="user_page_picture">
                    <?php if (isset($user['user_picture']) && $user['user_picture'] !== null): ?>
                        <img id="image_users" src="public/images/users/<?= $user['user_picture'] ?>" alt="Picture of <?= $user['user_username'] ?>" />  
                    <?php else :?>
                        <img id="image_users" src="public/images/defaultprofilepicture.jpg" alt="defaultprofilepicture" />
                    <?php endif; ?>
                    <div class="user_page_update_name">
                        <span id="user_page_username"><?= ucfirst($user['user_username']) ?></span>, <span id="age_user"><?= ucfirst($user['user_age']) ?></span>     
                        <div class="user_page_update_row">
                            <a href="update_profile.pfp"><button class="btn_user_updates" id="opendialog_update_profile">UPDATE PROFILE</button></a> 
                            <a href="update_looking.pfp"><button class="btn_user_updates" id="opendialog_update_looking">UPDATE LOOKING FOR</button></a>      
                            <button class="btn_user_updates" id="opendialog_update_picture">UPDATE PICTURE</button>
                            <button class="btn_user_updates" id="opendialog_add_social_links">ADD SOCIAL LINKS</button>
                        </div><br>
                        
                        <div class="user_page_update_row">
                            <?php if (!empty($user['user_twitter'])): ?>  
                                <a target="_blank" href="<?= $user['user_twitter'] ?>">
                                    <img class="social_picture" src="public/images/twitter_user.png" alt="twitter_user"></a>
                            <?php endif; ?>   
                            
                            <?php if (!empty($user['user_discord'])): ?>  
                                    <a target="_blank" href="<?= $user['user_discord'] ?>">
                                    <img class="social_picture" src="public/images/discord_user.png" alt="discord_user"></a>
                            <?php endif; ?>   
                            
                            <?php if (!empty($user['user_instragram'])): ?>
                                    <a target="_blank" href="<?= $user['user_instagram'] ?>">
                                    <img class="social_picture" src="public/images/instagram_user.png" alt="instagram_user"></a>  
                            <?php endif; ?>   

                            <?php if (!empty($user['user_twitch'])): ?>
                                    <a target="_blank" href="<?= $user['user_twitch'] ?>">
                                    <img class="social_picture" src="public/images/twitch_user.png" alt="twitch_user"></a>  
                            <?php endif; ?>                             
                        </div><br>
                    </div>
                </div>
            </div>
        </div>        
    </div>

    <?php if(!empty($friendRequest)) :?>
        <div class="friendrequest_box"><br>
            <h2 id="title_generalbox">Friend requests</h2><br>
            <?php foreach ($friendRequest as $request) :?>
                <div class="friend_request_ctn">
                    <p> From: <a target="_blank" href="user.php?username=<?= urlencode($request['fr_senderId']) ?>"><?= strtoupper($request['user_username']) ?></a>, the <? date('m/d H:i', strtotime($request['fr_date'])) ?></p><br>
                    <div class="friend_request_ctn_btn">
                        <a href='index.php?action=requestAccepted&fr_id=<?= $request['fr_id'] ?>&username=<?= urlencode($user['user_username']) ?>'><button id="accept_friend_button">Accept</button></a>
                        <a href='index.php?action=requestRefused&fr_id=<?= $request['fr_id'] ?>&username=<?= urlencode($user['user_username']) ?>'><button id="refuse_friend_button">Refuse</button></a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <div class="user_page_main_content">
        <div class="general_box">
            <br><h2 id="title_generalbox">About you</h2><br>
            <?php if ($user['user_game'] !== 'valorant'): ?> 
                <?php if (!empty($lolUser['lol_account'])): ?>
                    <div class="box_league_account">
                        <div class="box_league_account_main_row">
                            <img id="profilepicture_lol" src="public/images/profileicon/<?= $lolUser['lol_sProfileIcon'] ?>.png" alt="icon_league">
                            <div class="box_league_account_main_row_column">
                                <p><strong><?= $lolUser['lol_sUsername']?></strong></p> 
                                <p><?= strtoupper($lolUser['lol_server']) ?>, <?= strtoupper($lolUser['lol_sRank']) ?>, <?= strtoupper($lolUser['lol_sLevel']) ?> </p> 
                            </div>
                        </div>
                    </div><br>
                <?php endif; ?>
                    <?php include 'views/swiping/lol_perso_champions.phtml' ?><br>
            <?php endif; ?>

            <div class="about_you_users"><br>
                <p><strong>Gender</strong>: <?= ucfirst($user['user_gender']) ?></p><br>
                <p><strong>Kind of gamer</strong>: <?= ucfirst($user['user_kindOfGamer']) ?></p><br>
                <p><strong>Your short bio</strong>: <?= $user['user_shortBio'] ?></p><br>
            </div>
        </div>
    </div>

    <div class="lookingfor_box">
        <br><h2 id="title_generalbox">Looking for</h2><br>
            <?php if ($user['user_game'] !== 'valorant'): ?>
                <?php include 'views/swiping/lol_lf_champions.phtml' ?><br>
            <?php endif; ?>    
        </div>
    </div>
</section>