<div class="form_container"> 
    <button id="closeButton" type="button">X</button>
    <form class="form_signup" method="post" action="/updateProfile">

        <?php if (isset($_GET['error'])) : ?>
        <p class="errorsForm"><?= $_GET['error'] ?></p>
        <?php endif; ?>

        <label for="gender">Gender</label>
        <select id="gender" name="gender" required>
            <option value="<?= $user['user_gender'] ?>" ><?= $user['user_gender'] ?></option>
            <?php foreach ($genders as $value => $label) : ?>
                <?php if ($label !== $user['user_gender']) : ?>
                    <option value="<?= $label ?>"><?= $label ?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>  

        <label for="age">Age</label>
        <input type="text" id="age" name="age" value="<?= $user['user_age'] ?>" maxlength="2" required>

        <label for="kindofgamer">What kind of gamer are you?</label>
        <select id="kindofgamer" name="kindofgamer" required>
            <option value="<?= $user['user_kindOfGamer'] ?>" ><?= $user['user_kindOfGamer'] ?></option>
            <?php foreach ($kindofgamers as $value => $label) : ?>
                <?php if ($value !== $user['user_kindOfGamer']) : ?>
                    <option value="<?= $value ?>"><?= $label ?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>

        <label for="game">Game</label>
            <p>More games will be available later</p>
        <select id="game" name="game" required>
            <option value="<?= $user['user_game']?>" ><?= $user['user_game']?></option>
        </select>

        <label for="short_bio">Short bio about you</label>
        <textarea id="short_bio" name="short_bio" required><?= htmlspecialchars_decode($user['user_shortBio'], ENT_QUOTES) ?></textarea>

        <?php if($this->isConnectWebsite()) : ?>
            <input type="hidden" name="userId" value="<?= $_SESSION['userId'] ?>">  
        <?php endif ; ?>

        <input name="submit" id="send-button" type="submit" value="Send">
    </form>
    <img class="picture_with_form" src="public/images/Ahri.png" alt="Ahri from League of legends">
</div>

<script type="module" src="public/js/basicinfo.js"></script>
<script type="module" src="public/js/swiping/closebutton.js"></script>
