<div class="form_container"> 
    <button id="closeButton" type="button">X</button>
    <form class="form_signup" method="post" action="/updateLeague">

        <?php if (isset($_GET['error'])) : ?>
        <p class="errorsForm"><?= $_GET['error'] ?></p>
        <?php endif; ?>

        <h2>Pick your 3 mains</h2>
            <label for="main1" class="label-container">Main 1</label>
            <button type="button" id="btnMain1">Select main 1</button>
            <img id="main1Pic" src="public/images/champions/<?= trim($lolUser['lol_main1']) ?>.png" alt="<?= trim($lolUser['lol_main1']) ?>">
            <div id="popupMain1">
                    <input type="text" id="search1" autocomplete="no-autofill" value="<?= $lolUser['lol_main1'] ?>" class="notranslate">
                    <ul class="main1Ul">
                        <?php include 'views/signup/options_champion_league.phtml' ?>
                    <ul>
            </div>

            <input type="hidden" id="main1" name="main1" value="<?= $lolUser['lol_main1'] ?>" class="notranslate">

            <label for="main2" class="label-container">Main 2</label>
            <button type="button" id="btnMain2">Select main 2</button>
            <img id="main2Pic" src="public/images/champions/<?= trim($lolUser['lol_main2']) ?>.png" alt="<?= trim($lolUser['lol_main2']) ?>">
            <div id="popupMain2">
                    <input type="text" id="search2" autocomplete="no-autofill" value="<?= $lolUser['lol_main2'] ?>" class="notranslate">
                    <ul class="main2Ul">
                        <?php include 'views/signup/options_champion_league.phtml' ?>
                    <ul>
            </div>

            <input type="hidden" id="main2" name="main2" value="<?= $lolUser['lol_main2'] ?>" class="notranslate">

            <label for="main3" class="label-container">Main 3</label>
            <button type="button" id="btnMain3">Select main 3</button>
            <img id="main3Pic" src="public/images/champions/<?= trim($lolUser['lol_main3']) ?>.png" alt="<?= trim($lolUser['lol_main3']) ?>">
            <div id="popupMain3">
                    <input type="text" id="search3" autocomplete="no-autofill" value="<?= $lolUser['lol_main3'] ?>" class="notranslate">
                    <ul class="main3Ul">
                        <?php include 'views/signup/options_champion_league.phtml' ?>
                    <ul>
            </div>

            <input type="hidden" id="main3" name="main3" value="<?= $lolUser['lol_main3'] ?>" class="notranslate">


                <script src="public/js/champions.js"></script>


            <label for="rank_lol">Your rank</label>
            <select id="rank_lol" name="rank_lol">
                <option value="<?= $lolUser['lol_rank'] ?>" data-image="public/images/ranks/<?= $lolUser['lol_rank'] ?>.png"><?= $lolUser['lol_rank'] ?></option>
                <?php foreach ($lol_ranks as $rank) : ?>
                    <?php if ($rank !== $lolUser['lol_rank']) : ?>
                        <option value="<?= $rank ?>" data-image="public/images/ranks/<?= $rank ?>.png"><?= $rank ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <div id="selected-ranks-lol"></div>

            <script src="public/js/ranks.js"></script>

            <label for="role_lol">Your role</label>
            <select id="role_lol" name="role_lol">
                <option value="<?= $lolUser['lol_role'] ?>" data-image="public/images/roles/<?= strtolower(str_replace(' ', '', $lolUser['lol_role'])) ?>.png"><?= $lolUser['lol_role'] ?></option>
                <?php foreach ($lol_roles as $role) : ?>
                    <?php if ($role !== $lolUser['lol_role']) : ?>
                        <option value="<?= $role ?>" data-image="public/images/roles/<?= strtolower(str_replace(' ', '', $role)) ?>.png"><?= $role ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <div id="selected-roles"></div>

            <script src="public/js/roles.js"></script>

            <label for="server">Select your server</label>
            <select id="server" name="server">
                <option value="<?= $lolUser['lol_server'] ?>" ><?= $lolUser['lol_server'] ?></option>
                <?php foreach ($lol_servers as $server_key => $server_name) : ?>
                    <?php if ($server_name !== $lolUser['lol_server']) : ?>
                        <option value="<?= $server_name ?>"><?= $server_name ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

        <?php if($this->isConnectWebsite()) : ?>
            <input type="hidden" name="userId" value="<?= $_SESSION['userId'] ?>">  
        <?php endif ; ?>

        <input name="submit" id="send-button" type="submit" value="Send">
    </form>
    <img class="picture_with_form" src="public/images/Ahri.png" alt="Ahri from League of legends">
</div>

<script type="module" src="public/js/signupLol.js"></script>
<script type="module" src="public/js/leagueoflegendsinfo.js"></script>
<script type="module" src="public/js/swiping/closebutton.js"></script>