<div class="form_container"> 
    <button id="closeButton" type="button" aria-label="<?= $this->_('close') ?>">X</button>
    <form class="form_signup" method="post">

        <?php if (isset($_GET['error'])) : ?>
        <p class="errorsForm"><?= $_GET['error'] ?></p>
        <?php endif; ?>

            <div id="verification_code"></div>

            <label for="account_lol"><?= $this->_('update_league_link_label') ?></label>
            <input type="text" id="account_lol" name="account_lol" placeholder="<?= $this->_('update_league_link_placeholder') ?>">

            <label for="server"><?= $this->_('update_league_confirm_server') ?></label>
            <select id="server" name="server">
                <option value="<?= $lolUser['lol_server'] ?>" ><?= $lolUser['lol_server'] ?></option>
                <?php foreach ($lol_servers as $server_key => $server_name) : ?>
                    <?php if ($server_name !== $lolUser['lol_server']) : ?>
                        <option value="<?= $server_name ?>"><?= $server_name ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

        <?php if($this->isConnectWebsite()) : ?>
            <input type="hidden" name="userId" value="<?= $_SESSION['userId'] ?>">  
        <?php endif ; ?>

        <input name="submit" id="send-button" type="submit" value="<?= $this->_('send') ?>">
    </form>
    <img class="picture_with_form" src="public/images/Ahri.png" alt="Ahri from League of legends">
</div>

<script type="module" src="public/js/swiping/closebutton.js?<?= time(); ?>"></script>
<script type="module" src="public/js/swiping/send_accountData.js?<?= time(); ?>"></script>
