<div class="form_container"> 
    <form class="form_signup" method="post" action="/updateValorant">

    <?php if (isset($_GET['error'])) : ?>
    <p class="errorsForm"><?= $_GET['error'] ?></p>
    <?php endif; ?>

    <h2>Pick your 3 mains</h2>
    <label for="main1" class="label-container">Main 1 (Actual: <img class="images_update" src="public/images/valorant_champions/<?= trim($valorantUser['valorant_main1']) ?>_icon.webp">)</label>
        <button type="button" id="btnMain1">Select main 1</button>
        <div id="popupMain1">
                <input type="text" id="search1" autocomplete="no-autofill" placeholder="Search..." class="notranslate">
                <ul class="main1Ul">
                    <?php include 'views/signup/options_champion_valorant.phtml' ?>
                <ul>
        </div>

        <input type="hidden" id="main1" name="main1" value="" class="notranslate">

        <label for="main2" class="label-container">Main 2 (Actual: <img class="images_update" src="public/images/valorant_champions/<?= trim($valorantUser['valorant_main2']) ?>_icon.webp">)</label>
        <button type="button" id="btnMain2">Select main 2</button>
        <div id="popupMain2">
                <input type="text" id="search2" autocomplete="no-autofill" placeholder="Search..." class="notranslate">
                <ul class="main2Ul">
                    <?php include 'views/signup/options_champion_valorant.phtml' ?>
                <ul>
        </div>

        <input type="hidden" id="main2" name="main2" value="" class="notranslate">

        <label for="main3" class="label-container">Main 3 (Actual: <img class="images_update" src="public/images/valorant_champions/<?= trim($valorantUser['valorant_main3']) ?>_icon.webp">)</label>
        <button type="button" id="btnMain3">Select main 3</button>
        <div id="popupMain3">
                <input type="text" id="search3" autocomplete="no-autofill" placeholder="Search..." class="notranslate">
                <ul class="main3Ul">
                    <?php include 'views/signup/options_champion_valorant.phtml' ?>
                <ul>
        </div>

        <input type="hidden" id="main3" name="main3" value="" class="notranslate">


        <script src="public/js/champions.js"></script>


        <label for="rank_valorant">Your rank</label>
        <select id="rank_valorant" name="rank_valorant">
                <option value="<?= $valorantUser['valorant_rank'] ?>" data-image="public/images/valorant_ranks/<?= $valorantUser['valorant_rank'] ?>.png"><?= $valorantUser['valorant_rank'] ?></option>
                <?php foreach ($valorant_ranks as $rank) : ?>
                    <?php if ($rank !== $valorantUser['valorant_rank']) : ?>
                        <option value="<?= $rank ?>" data-image="public/images/valorant_ranks/<?= $rank ?>.png"><?= $rank ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

        <div id="selected-ranks-valorant"></div>

        <script src="public/js/ranks-valorant.js"></script>

        <label for="role_valorant">Your role</label>
        <select id="role_valorant" name="role_valorant">
                <option value="<?= $valorantUser['valorant_role'] ?>" data-image="public/images/valorant_roles/<?= $valorantUser['valorant_role']?>.webp"><?= $valorantUser['valorant_role'] ?></option>
                <?php foreach ($valorant_roles as $role) : ?>
                    <?php if ($role !== $valorantUser['valorant_role']) : ?>
                        <option value="<?= $role ?>" data-image="public/images/valorant_roles/<?=  $role ?>.webp"><?= $role ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

        <div id="selected-roles-valorant"></div>

        <script src="public/js/roles-valorant.js"></script>

        <label for="server">Select your server</label>
        <select id="server" name="server">
                <option value="<?= $valorantUser['valorant_server'] ?>" ><?= $valorantUser['valorant_server'] ?></option>
                <?php foreach ($valorant_servers as $server_key => $server_name) : ?>
                    <?php if ($server_name !== $valorantUser['valorant_server']) : ?>
                        <option value="<?= $server_name ?>"><?= $server_name ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

        <?php if($this->isConnectWebsite()) : ?>
            <input type="hidden" name="userId" value="<?= $_SESSION['userId'] ?>">  
        <?php endif ; ?>

        <input name="submit" id="send-button" type="submit" value="Send">
    </form>
    <img class="picture_with_form" src="public/images/jett.png" alt="Jett from Valorant">
</div>


<script type="module" src="public/js/signupLol.js"></script>
<script type="module" src="public/js/valorantinfo.js"></script>
<script type="module" src="public/js/swiping/closebutton.js"></script>