<div class="form_container">
    <button id="closeButton" type="button">X</button> 
    <form class="form_signup" method="post" action="/updateValorant">

    <?php if (isset($_GET['error'])) : ?>
    <p class="errorsForm"><?= $_GET['error'] ?></p>
    <?php endif; ?>

    <div id="champion-picker">
        <div class="champions-picker-column">
            <img src="public/images/valorant_champions/<?= $valorantMain1 ?>_icon.webp" alt="<?= $valorantMain1 ?>" class="champion-picker-img picker-main1">
            <p id="main1-name"><?= $valorantMain1 ?></p>
        </div>
        <div class="champions-picker-column">
            <img src="public/images/valorant_champions/<?= $valorantMain2 ?>_icon.webp" alt="<?= $valorantMain2 ?>" class="champion-picker-img picker-main2">
            <p id="main2-name"><?= $valorantMain2 ?></p>
        </div>
        <div class="champions-picker-column">
            <img src="public/images/valorant_champions/<?= $valorantMain3 ?>_icon.webp" alt="<?= $valorantMain3 ?>" class="champion-picker-img picker-main3">
            <p id="main3-name"><?= $valorantMain3 ?></p>
        </div>
        <div class="champions-picker-column">
            <button id="skipSelection-btn">Skip</button>
        </div>
        <input type="hidden" id="main1" name="main1" value="<?= $valorantUser['valorant_main1'] ?>" class="notranslate champion-picker-input">
        <input type="hidden" id="main2" name="main2" value="<?= $valorantUser['valorant_main2'] ?>" class="notranslate champion-picker-input">
        <input type="hidden" id="main3" name="main3" value="<?= $valorantUser['valorant_main3'] ?>" class="notranslate champion-picker-input">
        <input type="hidden" id="skipSelection" name="skipSelection" value="<?= $valorantUser['valorant_noChamp'] ?>">
    </div>

    <script src="public/js/champions-picker-valorant.js"></script>

      <!-- Champion Selection Modals -->
      <div id="modal-main1" class="champion-modal">
        <div class="modal-content">
            <button type="button" class="close-btn" onclick="closeModal('modal-main1')">✖</button>
            <input type="text" placeholder="Search agent..." class="champion-search" onkeyup="filterChampions(this, 'champion-list-main1')">
            <div id="champion-list-main1" class="champion-list"></div>
        </div>
    </div>

    <div id="modal-main2" class="champion-modal">
        <div class="modal-content">
            <button type="button" class="close-btn" onclick="closeModal('modal-main2')">✖</button>
            <input type="text" placeholder="Search agent..." class="champion-search" onkeyup="filterChampions(this, 'champion-list-main2')">
            <div id="champion-list-main2" class="champion-list"></div>
        </div>
    </div>

    <div id="modal-main3" class="champion-modal">
        <div class="modal-content">
            <button type="button" class="close-btn" onclick="closeModal('modal-main3')">✖</button>
            <input type="text" placeholder="Search agent..." class="champion-search" onkeyup="filterChampions(this, 'champion-list-main3')">
            <div id="champion-list-main3" class="champion-list"></div>
        </div>
    </div>

        <label for="rank_valorant">Your rank</label>
        <select id="rank_valorant" name="rank_valorant">
                <option value="<?= $valorantUser['valorant_rank'] ?>" data-image="public/images/valorant_ranks/<?= $valorantUser['valorant_rank'] ?>.png"><?= $valorantUser['valorant_rank'] ?></option>
                <?php foreach ($valorant_ranks as $rank) : ?>
                    <?php if ($rank !== $valorantUser['valorant_rank']) : ?>
                        <option value="<?= $rank ?>" data-image="public/images/valorant_ranks/<?= $rank ?>.png"><?= $rank ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

        <div id="selected-ranks-valorant"></div>

        <script src="public/js/ranks-valorant.js"></script>

        <label for="role_valorant">Your role</label>
        <select id="role_valorant" name="role_valorant">
                <option value="<?= $valorantUser['valorant_role'] ?>" data-image="public/images/valorant_roles/<?= $valorantUser['valorant_role']?>.webp"><?= $valorantUser['valorant_role'] ?></option>
                <?php foreach ($valorant_roles as $role) : ?>
                    <?php if ($role !== $valorantUser['valorant_role']) : ?>
                        <option value="<?= $role ?>" data-image="public/images/valorant_roles/<?=  $role ?>.webp"><?= $role ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

        <div id="selected-roles-valorant"></div>

        <script src="public/js/roles-valorant.js"></script>

        <label for="server">Select your server</label>
        <select id="server" name="server">
                <option value="<?= $valorantUser['valorant_server'] ?>" ><?= $valorantUser['valorant_server'] ?></option>
                <?php foreach ($valorant_servers as $server_key => $server_name) : ?>
                    <?php if ($server_name !== $valorantUser['valorant_server']) : ?>
                        <option value="<?= $server_name ?>"><?= $server_name ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

        <?php if($this->isConnectWebsite()) : ?>
            <input type="hidden" name="userId" value="<?= $_SESSION['userId'] ?>">  
        <?php endif ; ?>

        <input name="submit" id="send-button" type="submit" value="Send">
    </form>
    <img class="picture_with_form" src="public/images/jett.png" alt="Jett from Valorant">
</div>


<script type="module" src="public/js/swiping/closebutton.js"></script>