<div class="form_container"> 
    <button id="closeButton" type="button">X</button>
    <form class="form_signup" method="post" action="/updateLookingFor">

    <?php if (isset($_GET['error'])) : ?>
        <p class="errorsForm"><?= $_GET['error'] ?></p>
        <?php endif; ?>


        <label for="gender">Gender you are looking for</label>
        <select id="gender" name="gender" required>
            <option value="<?= $lfUser['lf_gender'] ?>" ><?= $lfUser['lf_gender'] ?></option>
            <?php foreach ($genders as $value => $label) : ?>
                <?php if ($value !== $lfUser['lf_gender']) : ?>
                    <option value="<?= $label ?>"><?= $label ?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>

        <label for="kindofgamer">What kind of gamer are you looking for?</label>
        <select id="kindofgamer" name="kindofgamer" required>
            <option value="<?= $lfUser['lf_kindofgamer'] ?>" ><?= $lfUser['lf_kindofgamer'] ?></option>
            <?php foreach ($kindofgamers as $value => $label) : ?>
                <?php if ($value !== $lfUser['lf_kindofgamer']) : ?>
                    <option value="<?= $value ?>"><?= $label ?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>

        <?php if($user['user_game'] == "League of Legends") :?>

        <h2>Pick 3 mains you would like to play with</h2>
            <label for="main1" class="label-container">Main 1</label>
            <button type="button" id="btnMain1">Select main 1</button>
            <img id="main1Pic" src="public/images/champions/<?= trim($lfUser['lf_lolmain1']) ?>.png" alt="<?= trim($lfUser['lf_lolmain1']) ?>">
            <div id="popupMain1">
                    <input type="text" id="search1" autocomplete="no-autofill" value="<?= $lfUser['lf_lolmain1'] ?>" class="notranslate">
                    <ul class="main1Ul">
                        <?php include 'views/signup/options_champion_league.phtml' ?>
                    <ul>
            </div>

            <input type="hidden" id="main1" name="main1" value="<?= $lfUser['lf_lolmain1'] ?>" class="notranslate">

            <label for="main2" class="label-container">Main 2</label>
            <button type="button" id="btnMain2">Select main 2</button>
            <img id="main2Pic" src="public/images/champions/<?= trim($lfUser['lf_lolmain2']) ?>.png" alt="<?= trim($lfUser['lf_lolmain2']) ?>">
            <div id="popupMain2">
                    <input type="text" id="search2" autocomplete="no-autofill" value="<?= $lfUser['lf_lolmain2'] ?>" class="notranslate">
                    <ul class="main2Ul">
                        <?php include 'views/signup/options_champion_league.phtml' ?>
                    <ul>
            </div>

            <input type="hidden" id="main2" name="main2" value="<?= $lfUser['lf_lolmain2'] ?>" class="notranslate">

            <label for="main3" class="label-container">Main 3</label>
            <button type="button" id="btnMain3">Select main 3</button>
            <img id="main3Pic" src="public/images/champions/<?= trim($lfUser['lf_lolmain3']) ?>.png" alt="<?= trim($lfUser['lf_lolmain3']) ?>">
            <div id="popupMain3">
                    <input type="text" id="search3" autocomplete="no-autofill" value="<?= $lfUser['lf_lolmain3'] ?>" class="notranslate">
                    <ul class="main3Ul">
                        <?php include 'views/signup/options_champion_league.phtml' ?>
                    <ul>
            </div>

            <input type="hidden" id="main3" name="main3" value="<?= $lfUser['lf_lolmain3'] ?>" class="notranslate">


                <script src="public/js/champions.js"></script>


            <label for="rank_lol">Rank you are looking for</label>
            <select id="rank_lol" name="rank_lol">
                <option value="<?= $lfUser['lf_lolrank'] ?>" data-image="public/images/ranks/<?= $lfUser['lf_lolrank'] ?>.png"><?= $lfUser['lf_lolrank'] ?></option>
                <?php foreach ($lol_ranks as $rank) : ?>
                    <?php if ($rank !== $lfUser['lf_lolrank']) : ?>
                        <option value="<?= $rank ?>" data-image="public/images/ranks/<?= $rank ?>.png"><?= $rank ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <div id="selected-ranks-lol"></div>

            <script src="public/js/ranks.js"></script>

            <label for="role_lol">Role you are looking for</label>
            <select id="role_lol" name="role_lol">
                <option value="<?= $lfUser['lf_lolrole'] ?>" data-image="public/images/roles/<?= strtolower(str_replace(' ', '', $lfUser['lf_lolrole'])) ?>.png"><?= $lfUser['lf_lolrole'] ?></option>
                <?php foreach ($lol_roles as $role) : ?>
                    <?php if ($role !== $lfUser['lf_lolrole']) : ?>
                        <option value="<?= $role ?>" data-image="public/images/roles/<?= strtolower(str_replace(' ', '', $role)) ?>.png"><?= $role ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <div id="selected-roles"></div>

            <script src="public/js/roles.js"></script>

            <input type="hidden" name="game" value="League of Legends"> 
        <?php else : ?>

            <h2>Pick 3 mains you would like to play with</h2>
            <label for="main1" class="label-container">Main 1</label>
            <button type="button" id="btnMain1">Select main 1</button>
            <img id="main1Pic" src="public/images/valorant_champions/<?= trim($lfUser['lf_valmain1']) ?>_icon.webp" alt="<?= $lfUser['lf_valmain1'] ?>">
            <div id="popupMain1">
                    <input type="text" id="search1" autocomplete="no-autofill" value="<?= $lfUser['lf_valmain1'] ?>" class="notranslate">
                    <ul class="main1Ul">
                        <?php include 'views/signup/options_champion_valorant.phtml' ?>
                    <ul>
            </div>

            <input type="hidden" id="main1" name="main1" value="<?= $lfUser['lf_valmain1'] ?>" class="notranslate">

            <label for="main2" class="label-container">Main 2</label>
            <button type="button" id="btnMain2">Select main 2</button>
            <img id="main2Pic" src="public/images/valorant_champions/<?= trim($lfUser['lf_valmain2']) ?>_icon.webp" alt="<?= $lfUser['lf_valmain2'] ?>">
            <div id="popupMain2">
                    <input type="text" id="search2" autocomplete="no-autofill" value="<?= $lfUser['lf_valmain2'] ?>" class="notranslate">
                    <ul class="main2Ul">
                        <?php include 'views/signup/options_champion_league.phtml' ?>
                    <ul>
            </div>

            <input type="hidden" id="main2" name="main2" value="<?= $lfUser['lf_valmain2'] ?>" class="notranslate">

            <label for="main3" class="label-container">Main 3</label>
            <button type="button" id="btnMain3">Select main 3</button>
            <img id="main3Pic" src="public/images/valorant_champions/<?= trim($lfUser['lf_valmain3']) ?>_icon.webp" alt="<?= $lfUser['lf_valmain3'] ?>">
            <div id="popupMain3">
                    <input type="text" id="search3" autocomplete="no-autofill" value="<?= $lfUser['lf_valmain3'] ?>" class="notranslate">
                    <ul class="main3Ul">
                        <?php include 'views/signup/options_champion_league.phtml' ?>
                    <ul>
            </div>

            <input type="hidden" id="main3" name="main3" value="<?= $lfUser['lf_valmain3'] ?>" class="notranslate">


                <script src="public/js/champions.js"></script>


            <label for="rank_valorant">Rank you are looking for</label>
            <select id="rank_valorant" name="rank_valorant">
                <option value="<?= $lfUser['lf_valrank'] ?>" data-image="public/images/valorant_ranks/<?= $lfUser['lf_valrank'] ?>.png"><?= $lfUser['lf_valrank'] ?></option>
                <?php foreach ($valorant_ranks as $rank) : ?>
                    <?php if ($rank !== $lfUser['lf_valrank']) : ?>
                        <option value="<?= $rank ?>" data-image="public/images/valorant_ranks/<?= $rank ?>.png"><?= $rank ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <div id="selected-ranks-valorant"></div>

            <script src="public/js/ranks-valorant.js"></script>

            <label for="role_valorant">Role you are looking for</label>
            <select id="role_valorant" name="role_valorant">
                <option value="<?= $lfUser['lf_valrole'] ?>" data-image="public/images/valorant_roles/<?= strtolower(str_replace(' ', '', $lfUser['lf_valrole'])) ?>.png"><?= $lfUser['lf_valrole'] ?></option>
                <?php foreach ($valorant_roles as $role) : ?>
                    <?php if ($role !== $lfUser['lf_valrole']) : ?>
                        <option value="<?= $role ?>" data-image="public/images/valorant_roles/<?= strtolower(str_replace(' ', '', $role)) ?>.png"><?= $role ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <div id="selected-roles-valorant"></div>

            <script src="public/js/roles-valorant.js"></script>

            <input type="hidden" name="game" value="Valorant"> 
        <?php endif; ?>

            <?php if($this->isConnectWebsite()) : ?>
            <input type="hidden" name="userId" value="<?= $_SESSION['userId'] ?>">  
        <?php endif ; ?>

        <input name="submit" id="send-button" type="submit" value="Send">
    </form>
    <img class="picture_with_form" src="public/images/Ahri.png" alt="Ahri from League of legends">
</div>


<script type="module" src="public/js/swiping/closebutton.js"></script>
