<div class="form_container"> 
    <button id="closeButton" type="button">X</button>
    <form class="form_signup" method="post" action="/updateLookingFor">

    <?php if (isset($_GET['error'])) : ?>
        <p class="errorsForm"><?= $_GET['error'] ?></p>
        <?php endif; ?>


        <label for="gender"><?= $this->_('update_lookingfor_gender_label') ?></label>
        <select id="gender" name="gender" required>
            <option value="<?= $lfUser['lf_gender'] ?>" ><?= $lfUser['lf_gender'] ?></option>
            <?php foreach ($genders as $value => $label) : ?>
                <?php if ($value !== $lfUser['lf_gender']) : ?>
                    <option value="<?= $label ?>"><?= $label ?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>

        <label for="kindofgamer"><?= $this->_('update_lookingfor_kindofgamer_label') ?></label>
        <select id="kindofgamer" name="kindofgamer" required>
            <option value="<?= $lfUser['lf_kindofgamer'] ?>" ><?= $lfUser['lf_kindofgamer'] ?></option>
            <?php foreach ($kindofgamers as $value => $label) : ?>
                <?php if ($value !== $lfUser['lf_kindofgamer']) : ?>
                    <option value="<?= $value ?>"><?= $label ?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>

        <?php if($user['user_game'] == "League of Legends") :?>

            <div id="champion-picker">
                <div class="champions-picker-column">
                    <img src="public/images/champions/<?= $lolMain1 ?>.png" alt="<?= $lolMain1 ?>" class="champion-picker-img picker-main1">
                    <p id="main1-name"><?= $lolMain1 ?></p>
                </div>
                <div class="champions-picker-column">
                    <img src="public/images/champions/<?= $lolMain2 ?>.png" alt="<?= $lolMain2 ?>" class="champion-picker-img picker-main2">
                    <p id="main2-name"><?= $lolMain2 ?></p>
                </div>
                <div class="champions-picker-column">
                    <img src="public/images/champions/<?= $lolMain3 ?>.png" alt="<?= $lolMain3 ?>" class="champion-picker-img picker-main3">
                    <p id="main3-name"><?= $lolMain3 ?></p>
                </div>
                <div class="champions-picker-column">
                    <button id="skipSelection-btn"><?= $this->_('skip') ?></button>
                </div>
                <input type="hidden" id="main1" name="main1" value="<?= $lfUser['lf_lolmain1'] ?>" class="notranslate champion-picker-input">
                <input type="hidden" id="main2" name="main2" value="<?= $lfUser['lf_lolmain2'] ?>" class="notranslate champion-picker-input">
                <input type="hidden" id="main3" name="main3" value="<?= $lfUser['lf_lolmain3'] ?>" class="notranslate champion-picker-input">
                <input type="hidden" id="skipSelection" name="skipSelection" value="<?= $lfUser['lf_lolNoChamp'] ?>">
            </div>

            <!-- Champion Selection Modals -->
            <div id="modal-main1" class="champion-modal">
                <div class="modal-content">
                    <button type="button" class="close-btn" onclick="closeModal('modal-main1')">✖</button>
                    <input type="text" placeholder="Search champion..." class="champion-search" onkeyup="filterChampions(this, 'champion-list-main1')">
                    <div id="champion-list-main1" class="champion-list"></div>
                </div>
            </div>

            <div id="modal-main2" class="champion-modal">
                <div class="modal-content">
                    <button type="button" class="close-btn" onclick="closeModal('modal-main2')">✖</button>
                    <input type="text" placeholder="Search champion..." class="champion-search" onkeyup="filterChampions(this, 'champion-list-main2')">
                    <div id="champion-list-main2" class="champion-list"></div>
                </div>
            </div>

            <div id="modal-main3" class="champion-modal">
                <div class="modal-content">
                    <button type="button" class="close-btn" onclick="closeModal('modal-main3')">✖</button>
                    <input type="text" placeholder="Search champion..." class="champion-search" onkeyup="filterChampions(this, 'champion-list-main3')">
                    <div id="champion-list-main3" class="champion-list"></div>
                </div>
            </div>

            <script src="public/js/champions-picker.js?<?= time(); ?>"></script>

            <label for="rank_lol">Rank you are looking for</label>
            <select id="rank_lol" name="rank_lol">
                <option value="<?= $lfUser['lf_lolrank'] ?>" data-image="public/images/ranks/<?= $lfUser['lf_lolrank'] ?>.png"><?= $lfUser['lf_lolrank'] ?></option>
                <?php foreach ($lol_ranks as $rank) : ?>
                    <?php if ($rank !== $lfUser['lf_lolrank']) : ?>
                        <option value="<?= $rank ?>" data-image="public/images/ranks/<?= $rank ?>.png"><?= $rank ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <div id="selected-ranks-lol"></div>

            <script src="public/js/ranks.js?<?= time(); ?>"></script>

            <label for="role_lol">Role you are looking for</label>
            <select id="role_lol" name="role_lol">
                <option value="<?= $lfUser['lf_lolrole'] ?>" data-image="public/images/roles/<?= strtolower(str_replace(' ', '', $lfUser['lf_lolrole'])) ?>.png"><?= $lfUser['lf_lolrole'] ?></option>
                <?php foreach ($lol_roles as $role) : ?>
                    <?php if ($role !== $lfUser['lf_lolrole']) : ?>
                        <option value="<?= $role ?>" data-image="public/images/roles/<?= strtolower(str_replace(' ', '', $role)) ?>.png"><?= $role ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <div id="selected-roles"></div>

            <script src="public/js/roles.js?<?= time(); ?>"></script>

            <input type="hidden" name="game" value="League of Legends"> 
        <?php else : ?>

            <div id="champion-picker">
                <div class="champions-picker-column">
                    <img src="public/images/valorant_champions/<?= $valorantMain1 ?>_icon.webp" alt="<?= $valorantMain1 ?>" class="champion-picker-img picker-main1">
                    <p id="main1-name"><?= $valorantMain1 ?></p>
                </div>
                <div class="champions-picker-column">
                    <img src="public/images/valorant_champions/<?= $valorantMain2 ?>_icon.webp" alt="<?= $valorantMain2 ?>" class="champion-picker-img picker-main2">
                    <p id="main2-name"><?= $valorantMain2 ?></p>
                </div>
                <div class="champions-picker-column">
                    <img src="public/images/valorant_champions/<?= $valorantMain3 ?>_icon.webp" alt="<?= $valorantMain3 ?>" class="champion-picker-img picker-main3">
                    <p id="main3-name"><?= $valorantMain3 ?></p>
                </div>
                <div class="champions-picker-column">
                    <button id="skipSelection-btn">Skip</button>
                </div>
                <input type="hidden" id="main1" name="main1" value="<?= $lfUser['lf_valmain1'] ?>" class="notranslate champion-picker-input">
                <input type="hidden" id="main2" name="main2" value="<?= $lfUser['lf_valmain2'] ?>" class="notranslate champion-picker-input">
                <input type="hidden" id="main3" name="main3" value="<?= $lfUser['lf_valmain3'] ?>" class="notranslate champion-picker-input">
                <input type="hidden" id="skipSelection" name="skipSelection" value="<?= $lfUser['lf_valNoChamp'] ?>">
            </div>

            <script src="public/js/champions-picker-valorant.js?<?= time(); ?>"></script>

            <!-- Champion Selection Modals -->
            <div id="modal-main1" class="champion-modal">
                <div class="modal-content">
                    <button type="button" class="close-btn" onclick="closeModal('modal-main1')">✖</button>
                    <input type="text" placeholder="Search agent..." class="champion-search" onkeyup="filterChampions(this, 'champion-list-main1')">
                    <div id="champion-list-main1" class="champion-list"></div>
                </div>
            </div>

            <div id="modal-main2" class="champion-modal">
                <div class="modal-content">
                    <button type="button" class="close-btn" onclick="closeModal('modal-main2')">✖</button>
                    <input type="text" placeholder="Search agent..." class="champion-search" onkeyup="filterChampions(this, 'champion-list-main2')">
                    <div id="champion-list-main2" class="champion-list"></div>
                </div>
            </div>

            <div id="modal-main3" class="champion-modal">
                <div class="modal-content">
                    <button type="button" class="close-btn" onclick="closeModal('modal-main3')">✖</button>
                    <input type="text" placeholder="Search agent..." class="champion-search" onkeyup="filterChampions(this, 'champion-list-main3')">
                    <div id="champion-list-main3" class="champion-list"></div>
                </div>
            </div>

            <label for="rank_valorant">Rank you are looking for</label>
            <select id="rank_valorant" name="rank_valorant">
                <option value="<?= $lfUser['lf_valrank'] ?>" data-image="public/images/valorant_ranks/<?= $lfUser['lf_valrank'] ?>.png"><?= $lfUser['lf_valrank'] ?></option>
                <?php foreach ($valorant_ranks as $rank) : ?>
                    <?php if ($rank !== $lfUser['lf_valrank']) : ?>
                        <option value="<?= $rank ?>" data-image="public/images/valorant_ranks/<?= $rank ?>.png"><?= $rank ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <div id="selected-ranks-valorant"></div>

            <script src="public/js/ranks-valorant.js?<?= time(); ?>"></script>

            <label for="role_valorant">Role you are looking for</label>
            <select id="role_valorant" name="role_valorant">
                <option value="<?= $lfUser['lf_valrole'] ?>" data-image="public/images/valorant_roles/<?= strtolower(str_replace(' ', '', $lfUser['lf_valrole'])) ?>.png"><?= $lfUser['lf_valrole'] ?></option>
                <?php foreach ($valorant_roles as $role) : ?>
                    <?php if ($role !== $lfUser['lf_valrole']) : ?>
                        <option value="<?= $role ?>" data-image="public/images/valorant_roles/<?= strtolower(str_replace(' ', '', $role)) ?>.png"><?= $role ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>

            <div id="selected-roles-valorant"></div>

            <script src="public/js/roles-valorant.js?<?= time(); ?>"></script>

            <input type="hidden" name="game" value="Valorant"> 
        <?php endif; ?>

        <label>Filter servers</label>
        <p>You'll be seeing only servers if button is red</p>

        <div id="server-container" data-selected-servers='<?= json_encode(explode(",", $lfUser["lf_filteredServer"] ?? "")) ?>'></div>

        <input type="hidden" name="filteredServers" id="filteredServers" value='<?= htmlspecialchars($lfUser["lf_filteredServer"] ?? "[]", ENT_QUOTES, "UTF-8") ?>'>

        <?php if($this->isConnectWebsite()) : ?>
            <input type="hidden" name="userId" value="<?= $_SESSION['userId'] ?>">  
        <?php endif ; ?>

        <input name="submit" id="send-button" type="submit" value="Send">
    </form>
    <img class="picture_with_form" src="public/images/Ahri.png" alt="Ahri from League of legends">
</div>


<script type="module" src="public/js/swiping/closebutton.js?<?= time(); ?>"></script>
<script src="public/js/filteredServers.js?<?= time(); ?>"></script>