<?php
$champions = [
    "Astra" => "public/images/valorant_champions/Astra_icon.webp",
    "Breach" => "public/images/valorant_champions/Breach_icon.webp",
    "Brimstone" => "public/images/valorant_champions/Brimstone_icon.webp",
    "Chamber" => "public/images/valorant_champions/Chamber_icon.webp",
    "Clove" => "public/images/valorant_champions/Clove_icon.webp",
    "Cypher" => "public/images/valorant_champions/Cypher_icon.webp",
    "Deadlock" => "public/images/valorant_champions/Deadlock_icon.webp",
    "Fade" => "public/images/valorant_champions/Fade_icon.webp",
    "Gekko" => "public/images/valorant_champions/Gekko_icon.webp",
    "Harbor" => "public/images/valorant_champions/Harbor_icon.webp",
    "Iso" => "public/images/valorant_champions/Iso_icon.webp",
    "Jett" => "public/images/valorant_champions/Jett_icon.webp",    
    "Kayo" => "public/images/valorant_champions/Kayo_icon.webp",
    "Killjoy" => "public/images/valorant_champions/Killjoy_icon.webp",
    "Neon" => "public/images/valorant_champions/Neon_icon.webp",
    "Omen" => "public/images/valorant_champions/Omen_icon.webp",
    "Phoenix" => "public/images/valorant_champions/Phoenix_icon.webp",
    "Raze" => "public/images/valorant_champions/Raze_icon.webp",
    "Reyna" => "public/images/valorant_champions/Reyna_icon.webp",
    "Sage" => "public/images/valorant_champions/Sage_icon.webp",
    "Skye" => "public/images/valorant_champions/Skye_icon.webp",
    "Sova" => "public/images/valorant_champions/Sova_icon.webp",
    "Viper" => "public/images/valorant_champions/Viper_icon.webp",
    "Vyse" => "public/images/valorant_champions/Vyse_icon.webp",
    "Yoru" => "public/images/valorant_champions/Yoru_icon.webp"
];

$ranks = [
    "Iron" => "public/images/valorant_ranks/Iron.png",
    "Bronze" => "public/images/valorant_ranks/Bronze.png",
    "Silver" => "public/images/valorant_ranks/Silver.png",
    "Gold" => "public/images/valorant_ranks/Gold.png",
    "Platinum" => "public/images/valorant_ranks/Platinum.png",
    "Diamond" => "public/images/valorant_ranks/Diamond.png",
    "Ascendant" => "public/images/valorant_ranks/Ascendant.png",
    "Immortal" => "public/images/valorant_ranks/Immortal.png",
    "Radiant" => "public/images/valorant_ranks/Radiant.png",
    "Any" => "public/images/valorant_ranks/Any.png",
    "Unranked" => "public/images/valorant_ranks/Unranked.png"
];

$roles = [
    "Controller" => "public/images/valorant_roles/Controller.webp",
    "Duelist" => "public/images/valorant_roles/Duelist.webp",
    "Initiator" => "public/images/valorant_roles/Initiator.webp",
    "Sentinel" => "public/images/valorant_roles/Sentinel.webp",
    "Any" => "public/images/valorant_roles/Any.png",
    "fill" => "public/images/valorant_roles/fill.png",
    "Fill" => "public/images/valorant_roles/fill.png"
];
?>


<div class="user_page_main_league">
    <?php if ($user['user_game'] !== 'League of Legends'): ?>
        <div class="league_of_legends_user">
            <?php if (isset($champions[$lfUser['lf_valmain1']])): ?>
                <div class="league_of_legends_user_column">
            <img class="league_champions_user" src="<?= $champions[$lfUser['lf_valmain1']] ?>" alt="<?= $lfUser['lf_valmain1'] ?>">
            <p class="no_display_phone"><?= $lfUser['lf_valmain1']; ?></p>
            </div>
            <?php endif; ?>
            <?php if (isset($champions[$lfUser['lf_valmain2']])): ?>
                <div class="league_of_legends_user_column">
                <img class="league_champions_user" src="<?= $champions[$lfUser['lf_valmain2']] ?>" alt="<?= $lfUser['lf_valmain2'] ?>">
                <p class="no_display_phone"><?= $lfUser['lf_valmain2']; ?></p>
                </div>
            <?php endif; ?>
            <?php if (isset($champions[$lfUser['lf_valmain3']])): ?>
                <div class="league_of_legends_user_column">                        
                <img class="league_champions_user" src="<?= $champions[$lfUser['lf_valmain3']] ?>" alt="<?= $lfUser['lf_valmain3'] ?>">
                <p class="no_display_phone"><?= $lfUser['lf_valmain3']; ?></p>
                </div>
            <?php endif; ?>
            <?php if (isset($ranks[$lfUser['lf_valrank']])): ?>
                <div class="league_of_legends_user_column">
                    <img class="league_champions_user" src="<?= $ranks[$lfUser['lf_valrank']] ?>" alt="<?= $lfUser['lf_valrank'] ?>">
                    <p class="no_display_phone"><?= $lfUser['lf_valrank'] ?></p>
                </div>  
            <?php endif; ?>
            <?php if (isset($roles[$lfUser['lf_valrole']])): ?>
                <div class="league_of_legends_user_column">
                    <img class="league_champions_user" src="<?= $roles[$lfUser['lf_valrole']] ?>" alt="<?= $lfUser['lf_valrole'] ?>">
                    <p class="no_display_phone"><?= $lfUser['lf_valrole'] ?></p>
                </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
