<?php
$champions = [
    "Astra" => "public/images/valorant_champions/Astra_icon.webp",
    "Breach" => "public/images/valorant_champions/Breach_icon.webp",
    "Brimstone" => "public/images/valorant_champions/Brimstone_icon.webp",
    "Chamber" => "public/images/valorant_champions/Chamber_icon.webp",
    "Cypher" => "public/images/valorant_champions/Cypher_icon.webp",
    "Fade" => "public/images/valorant_champions/Fade_icon.webp",
    "Gekko" => "public/images/valorant_champions/Gekko_icon.webp",
    "Harbor" => "public/images/valorant_champions/Harbor_icon.webp",
    "Jett" => "public/images/valorant_champions/Jett_icon.webp",    
    "Kayo" => "public/images/valorant_champions/Jett_icon.webp",
    "Killjoy" => "public/images/valorant_champions/Killjoy_icon.webp",
    "Neon" => "public/images/valorant_champions/Neon_icon.webp",
    "Omen" => "public/images/valorant_champions/Omen_icon.webp",
    "Phoenix" => "public/images/valorant_champions/Phoenix_icon.webp",
    "Raze" => "public/images/valorant_champions/Raze_icon.webp",
    "Reyna" => "public/images/valorant_champions/Reyna_icon.webp",
    "Sage" => "public/images/valorant_champions/Sage_icon.webp",
    "Skye" => "public/images/valorant_champions/Skye_icon.webp",
    "Sova" => "public/images/valorant_champions/Sova_icon.webp",
    "Viper" => "public/images/valorant_champions/Viper_icon.webp",
    "Yoru" => "public/images/valorant_champions/Yoru_icon.webp"
];

$ranks = [
    "Iron" => "public/images/valorant_ranks/Iron.png",
    "Bronze" => "public/images/valorant_ranks/Bronze.png",
    "Silver" => "public/images/valorant_ranks/Silver.png",
    "Gold" => "public/images/valorant_ranks/Gold.png",
    "Platinum" => "public/images/valorant_ranks/Platinum.png",
    "Diamond" => "public/images/valorant_ranks/Diamond.png",
    "Ascendant" => "public/images/valorant_ranks/Ascendant.png",
    "Immortal" => "public/images/valorant_ranks/Immortal.png",
    "Radiant" => "public/images/valorant_ranks/Radiant.png"
];

$roles = [
    "Controller" => "public/images/valorant_roles/Controller.webp",
    "Duelist" => "public/images/valorant_roles/Duelist.webp",
    "Initiator" => "public/images/valorant_roles/Initiator.webp",
    "Sentinel" => "public/images/valorant_roles/Sentinel.webp"
];
?>



<div class="user_page_main_league">
    <div class="league_of_legends_user">
        <div class="league_of_legends_user_column">
            <img id="lolMain1Pic" class="league_champions_user">
            <p id="lolMain1P" class="no_display_phone"></p>
        </div>
        <div class="league_of_legends_user_column">
            <img id="lolMain2Pic" class="league_champions_user">
            <p id="lolMain2P" class="no_display_phone"></p>
        </div>
        <div class="league_of_legends_user_column">                        
            <img id="lolMain3Pic" class="league_champions_user">
            <p id="lolMain3P" class="no_display_phone"></p>
        </div>
        <div class="league_of_legends_user_column">
            <img id="lolRankPic" class="league_champions_user">
            <p id="lolRankP" class="no_display_phone"></p>
        </div>  
        <div class="league_of_legends_user_column">
            <img id="lolRolePic" class="league_champions_user">
            <p id="lolRoleP" class="no_display_phone"></p>
        </div>
    </div>
</div>
